### ISSUE TITLE
[Request] Option to let the Studio plugin display updates in console

### ISSUE THREAD

**Issue by Validark** [rojo-rbx/rojo#138]
It would be nice to have a feature built-in to the plugin whereby a developer could see in the Roblox console how Rojo is updating files. I am on `Rojo 0.5.0-alpha.6`

**Comment by LPGhatguy** [comment]
It should be pretty straightforward to expand/curate the log output to be more useful for users of Rojo. It'd also be great to have documentation for how to _get_ at that log output!

For the time being, to get the maximum amount of debug information, you can:

1. Run the Rojo server with `RUST_LOG=librojo=trace rojo serve`, which will dump tons of diagnostics to the terminal
2. Run `_G.ROJO_DEV_CREATE()` in your Studio command bar, which will create a Rojo developer settings object in your game. By default, it will tell the plugin to be as verbose as possible.

**Comment by LPGhatguy** [comment]
Starting in Rojo 6, we've increased the verbosity of logging when `_G.ROJO_DEV_CREATE()` is called. From here, it's just a matter of documenting this feature. We should also expose this in the plugin settings,.
