### ISSUE TITLE
'rojo build' crashes cli 

### ISSUE THREAD

**Issue by ZachCurtis** [rojo-rbx/rojo#140]
thread 'main' panicked at 'not yet implemented', C:\Users\user\.cargo\registry\src\github.com-1ecc6299db9ec823\rbx_binary-0.4.0\src\serializer.rs:160:18
stack backtrace:
   0 - 17: < unknown >
  18: BaseThreadInitThunk
  19: RtlUserThreadStart
[ERROR rojo] Rojo crashed!
[ERROR rojo] This is a bug in Rojo.
[ERROR rojo]
[ERROR rojo] Please consider filing a bug: https://github.com/LPGhatguy/rojo/issues
[ERROR rojo]
[ERROR rojo] Details: not yet implemented

rustc 1.33.0

Resulting .rbxl opens with error: "17:34:09.317 - Serializer::load can't read header"

default.package.json [here ](https://hastebin.com/novotejupa.json) because github won't let me upload.

I'm very torn between "oh that's just not implemented yet" and "it told me to open an issue". Better safe than sorry so apologies in advance if this is expected behavior.

**Comment by ZachCurtis** [comment]
Possibly related: 17:59:38.837 - [Rojo-Warn] Plugin_1997686364.Rojo.Plugin.Reconciler:59: Invalid property Technology on class Lighting: Technology is not a valid member of Lighting

**Comment by LPGhatguy** [comment]
Thanks for filing an issue like the CLI asked you to! 😄

In this particular case, your project contains properties that aren't implemented in Rojo's implementation of the binary format yet. It should probably gracefully fail, so I opened a related issue on the library Rojo uses for this: LPGhatguy/rbx-dom#26. The binary format implementation really needs some love, I'm hoping to get back to it in the next couple weeks.

The binary format (rbxl, rbxm) implementation is pretty sparse right now. You might want to use the XML format (rbxlx, rbxmx) instead, at least in the meantime, which has much better coverage: https://github.com/LPGhatguy/rbx-dom#property-type-coverage

Your second note is a different, known bug. I just opened up a new issue (#141) that has more details on that!

**Comment by Faunsce** [comment]
I also got the same error

PS H:\RbxDev\TreasureTrove> rojo build --output TreasureTrove.rbxl
thread 'main' panicked at 'not yet implemented', C:\Users\domin\.cargo\registry\src\github.com-1ecc6299db9ec823\rbx_binary-0.4.0\src\serializer.rs:160:18
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
[ERROR rojo] Rojo crashed!
[ERROR rojo] This is a bug in Rojo.
[ERROR rojo]
[ERROR rojo] Please consider filing a bug: https://github.com/LPGhatguy/rojo/issues
[ERROR rojo]
[ERROR rojo] Details: not yet implemented

**Comment by LPGhatguy** [comment]
I've added a warning about support for the binary format now in `rojo build`. While the main issue remains (bad binary format support) I think this issue is closable.
