### ISSUE TITLE
Failure to reconcile when moving files to different folder

### ISSUE THREAD

**Issue by Quenty** [rojo-rbx/rojo#150]
```
11:10:57.642 - [Rojo-Warn] Plugin_1997686364.Rojo.Plugin.Reconciler:213: Rojo NYI: Instances with parents that weren't mentioned in an update payload
```

Occurs when moving files (rename operation). It doesn't _always_ show this warning, but it does fail to sync the files.

### Untested repo

1. Make a new file `ParentFolder/Folder/MyFile.lua`
1. Make a new empty folder `ParentFolder/Folder/ChildFolder/`
1. Launch Roblox studio
1. Start rojo syncing
1. Open sublime text and install "Sidebar enhancements" (May be able to do this with a drag file around)
1. Move `MyFile.lua` using SublimeText3 "Move file" command to `ParentFolder/Folder/ChildFolder/MyFile.lua`
     1. Alternatively use window's file explorer to move file
1. Expected behavior: File syncs and moves properly
1. Actual behavior: File does not sync, and does not exist in rojo!

### Notes
* Occurring for me in deep file structure with lots of files
* Only moving one file at a time
* Have to restart rojo serve to fix it

### Why
I suspect it has to do with quick changes (double changes), and therefore rojo fails to get proper state in a long-poll.

Let me know if you need a better repo.

**Comment by LPGhatguy** [comment]
I believe this may still sporadically appear in 0.5.4, but should be fixed in the Rojo master branch.

If you try 0.6.0-alpha.3 (not yet released!) or the master branch after this writing and still hit this, feel free to re-open this issue!

**Comment by Quenty** [comment]
Thank you for looking into this!
