### ISSUE TITLE
Plugin autostart

### ISSUE THREAD

**Issue by LPGhatguy** [rojo-rbx/rojo#151]
I'd like to be able to generate place files that have a special marker that the plugin recognizes, causing it to automatically try to connect to a running Rojo session.

It's really two tightly-coupled features:
- A flag to `rojo build` that injects a non-archivable instance into the `DataModel` with a special name
- A plugin feature that looks for that special instance on startup and automatically starts a session. This should probably have a filter on the project's name or maybe use an ephemeral port to avoid an accidental collision.

This would lay the groundwork for projects to use a single command to build a place file, open it in studio, and start live syncing. We could bundle that together into a command with a name like `rojo start` if it proves ubiquitous enough!

**Comment by boatbomber** [comment]
Superseded by #305.
