### ISSUE TITLE
Improve error messaging when project.json has invalid paths

### ISSUE THREAD

**Issue by Kylaaa** [rojo-rbx/rojo#159]
Rojo says that the system cannot find the path specified, but it is not clear that the path it is referring to is pulled from the project file and not somewhere else in the project. A little more information in the error message would go a long way for debugging.

**Comment by LPGhatguy** [comment]
Thanks for the report!

We should be able to fix this by wrapping the errors coming from where Rojo reads the project's files into the in-memory filesystem.

**Comment by LPGhatguy** [comment]
Errors should be much better in the `master` branch. When the next release rolls around (or if you try the in-development version out), let me know if you still have issues!
