### ISSUE TITLE
Test command

### ISSUE THREAD

**Issue by jeparlefrancais** [rojo-rbx/rojo#192]
If I have a project and I have written some tests, I'd like to be able to run:
```rojo test```

And then rojo would sync my code, run my tests, send me back the output results and clean the place it has used to run the tests.

This approach is more reliable since you're testing in a more realistic environment than Lemur! It can not run in CI services, but who knows maybe one day?

**Comment by LPGhatguy** [comment]
I'm not super sure if this is in scope for Rojo, or whether it should be a feature of another project I've been tinkering with, [run-in-roblox](https://github.com/LPGhatguy/run-in-roblox).

Definitely seems like it should be possible to compose Rojo together with other tools to accomplish something like this.

**Comment by jeparlefrancais** [comment]
Oh, I had not seen this one!

That seems fair, building with rojo and then running the place with run-in-roblox.

**Comment by LPGhatguy** [comment]
I think I'm going to say that this issue is out-of-scope for what Rojo is trying to do, but someone could definitely use Rojo as part of another tool to do this!
