### ISSUE TITLE
Ending folder name w/ .lua causes rojo to become unresponsive in specific cases

### ISSUE THREAD

**Issue by zoebasil** [rojo-rbx/rojo#193]
Updating the name of a folder to "[filename].lua" with an actual lua file with the name '[filename]' causes changes to stop being synced from the filesystem to studio, but doesn't throw an error

**Comment by LPGhatguy** [comment]
Weird! Definitely something that should be in our test suite, since it's a funky edge case.

**Comment by Kampfkarren** [comment]
Couldn't reproduce in the test suite?

**Comment by zoebasil** [comment]
my bad, i recalled the bug incorrectly. having a folder named '[filename].lua' in the same directory as an actual lua file named '[filename]' caused the bug for me

**Comment by LPGhatguy** [comment]
Should be resolved in `master`, what will be the 0.6.0 release!
