### ISSUE TITLE
Support longer filepaths

### ISSUE THREAD

**Issue by Kylaaa** [rojo-rbx/rojo#195]
The project stops being able to find files if their path is longer than 250 characters.

**Comment by Kampfkarren** [comment]
Do you mean 260? If so, [I believe this is a normal behavior of Windows](https://www.howtogeek.com/266621/how-to-make-windows-10-accept-file-paths-over-260-characters/), so it's going to be annoying to fix. ☹️

**Comment by LPGhatguy** [comment]
I'm not sure that this issue is actionable!

If we end up finding a more specific case that we can resolve, I'm up for reopening this issue or opening a new one.
