### ISSUE TITLE
Install plugin from CLI

### ISSUE THREAD

**Issue by Kampfkarren** [rojo-rbx/rojo#200]
Rojo should be able to install the plugin from the CLI. This would make #169 easier since there wouldn't need to be any special procedure for installing the built in plugin side (maybe even the whole plugin can be built in?). 

The weird part is how to actually accomplish this. There's many possibilities but none are that great. The ideas I can think of off the top of my head are:

- Downloading from online. This is the easiest to do but has complications with versions and local development. 

- Bundling the plugin somehow, like with `include_str!` or some build script mumbo jumbo. This has issued with `cargo install`, but maybe Rojo should release its own binaries anyway, asking people to install Rust to use Rojo is a bit clunky. The docs denounce other syncing tools for having to have the user install their language's environment: "I think that this tool needs to be built in a compiled language without a runtime, for easy distribution and good performance.".

**Comment by LPGhatguy** [comment]
The original approach I took was to use a Cargo feature to `include_bytes!` an `rbxm` containing the plugin. It was okay, and actually stuck around for a long time before I axed that part of the codebase.

Hurting the `cargo install` approach is kind of sad, though I would like to start distributing binaries through more avenues!

**Comment by Kampfkarren** [comment]
@LPGhatguy Build scripts could package an rbxmx (and in the future, rbxm) automatically, is that a reasonable approach?

**Comment by LPGhatguy** [comment]
A build script would need a copy of Rojo to bundle in. They run when you `cargo install`, not at publish time, so I don't follow how they'd help!

**Comment by Kampfkarren** [comment]
If `cargo install` is scrapped in favor of direct binary builds, then the build script should work?

**Comment by LPGhatguy** [comment]
I don't think we're dropping `cargo install`, since without an OS-level package manager it's by far the easiest way to install/upgrade Rojo.

**Comment by Kampfkarren** [comment]
Actually, I don't believe crates on Cargo have to be exclusively Rust code. All they *really* need is a `Cargo.toml` file in them, the rest is just tarballs. Any way we could use this to our advantage here?

**Comment by LPGhatguy** [comment]
Cargo rejects things that aren't checked into source control by default when you `cargo upload`.

@jeparlefrancais had a good idea, which is to include the plugin _source_ in some sort of tarball-y thing, like by generating some bincode in `build.rs` and using `include_bytes!` on it.

We could take this idea a step further and split apart Rojo's library and binary parts more. Then we can consume the library part from Rojo's `build.rs` script, programmatically build the plugin, and include it in the binary portion!

**Comment by Kampfkarren** [comment]
> We could take this idea a step further and split apart Rojo's library and binary parts more. Then we can consume the library part from Rojo's build.rs script, programmatically build the plugin, and include it in the binary portion!
Does the new reconciler make this easier?
