### ISSUE TITLE
Alpha 12?

### ISSUE THREAD

**Issue by Kampfkarren** [rojo-rbx/rojo#204]
Lot of unreleased features (notably meta files) in this build, when can we release alpha 12?

**Comment by LPGhatguy** [comment]
I keep meaning to build a new release but have been in/out for dental surgery during the past couple weeks. 🙁 

I wanted to make a couple final tweaks to meta files before they hit a release:
- Unknown fields should be rejected
- `className` and `properties` shouldn't be allowed for model files of any kind
