### ISSUE TITLE
Make Name property on model.json optional, use filename if missing

### ISSUE THREAD

**Issue by Kampfkarren** [rojo-rbx/rojo#206]
Specifying a `Name` property feels redundant if the filename that's what the file is going to be named anyway.

**Comment by LPGhatguy** [comment]
This kind of depends on the resolution from #171. If we end up going with the route that the name from the model file is picked over the name of the file (in order to support multiple top-level instances), then maybe name shouldn't be optional?

**Comment by LPGhatguy** [comment]
This has landed in both master and reconciler-mk5.
