### ISSUE TITLE
Support other init.lua convention

### ISSUE THREAD

**Issue by jeparlefrancais** [rojo-rbx/rojo#209]
It would be nice if rojo was able to turn a folder into a script using a specified file name. 

It could be done by offering a field to specify into the datamodel tree, that would apply to all sub-instances. So for example, everything under datamodel would convert when named `__init__.lua`, `__init__.server.lua` and `__init__.client.lua`

```json
{
    "tree": {
        "$className": "DataModel",
        "$moduleFile": "__init__",
        "ReplicatedStorage": {
            "$className": "ReplicatedStorage",
            "Something": {
                "$path": "src/something"
            }
        }
    }
}
```

If a project include a sub project, the field should return to default and then apply the project settings.

I don't think we should include the `.lua` in the name because it would not be that clear that it would work with `.server.lua` and `.client.lua` too.

That way, I could have a project that uses `__init__` as a convention and still be able to use Roact or any project that does not have the same convention.

I am not sure if the `$moduleFile` should be a global field outside the tree, or something inside a node of the tree, that can be overridden within instances in the tree.

**Comment by LPGhatguy** [comment]
I'm not sure about this since it hurts composability!

Code that uses a setting like adding support for `__init__` isn't portable if someone tries to pull it into another project without also having that non-default setting.

**Comment by Kampfkarren** [comment]
I mostly just don't see the point of this, why do you want a different init format? Do you have an actual script named init or something?

**Comment by jeparlefrancais** [comment]
About the compatibility, I think it can work if we 'reset' the setting when importing another project. So if you add a sub project that has it's own json file, we stop using the current project module file name and uses the one specified for the sub project (so the default one if not provided)

And yes, I'm using rojo for my new project, before I was using another tool I've made so all my previous libraries use the `__init__` convention. I think it stands out more from the rest of the files and it sends a clear message to a new user that this file does something special.

**Comment by LPGhatguy** [comment]
For consistency, I don't think I'm going to pursue this idea for now.
