### ISSUE TITLE
Don't allow multiple `rojo serve` on the same port

### ISSUE THREAD

**Issue by Kampfkarren** [rojo-rbx/rojo#211]
Regularly I'll have multiple `rojo serve` open without even realizing it. Would be nice for Rojo to abort if there's something else on that port.

**Comment by LPGhatguy** [comment]
Hm, I thought I fixed this with the move to a different HTTP server (see #65), but it looks like I didn't, oof. 🙁

**Comment by LPGhatguy** [comment]
Seems like this is a known issue with Hyper, see [this issue with Rocket](https://github.com/SergioBenitez/Rocket/issues/209).

In the current 0.6.0 alpha, Rojo's main thread panics, but then deadlocks when trying to join our Notify message converter thread. There's a comment in the code about this scenario, but I'm unsure how to fix it.

**Comment by LPGhatguy** [comment]
It looks like on current master at least, Rojo no longer has this bug!

Instead, we get a crash, which is... better than nothing, but stops issues from running into this at least.
