### ISSUE TITLE
Deleting file in VSCode does not sync with Studio

### ISSUE THREAD

**Issue by andrewdkim** [rojo-rbx/rojo#213]
Not sure if I am doing something wrong, but looks like syncing works fine for creating new files or modifying the file, but when it comes to deleting the file in VSCode, it does not sync with studio (meaning the file is deleted in VSCode, but not in Roblox Studio). Also, it seems like default.project.json file does not sync with studio either. 

However, deleting files and updating project.json file works when I kill rojo serve and restart. Am I doing something wrong, or is this a bug?

**Comment by LPGhatguy** [comment]
It looks like there are a couple other reports of issues like this!

Note that modifying the `.project.json` file _will not_ automatically update in Rojo, see #10.

**Comment by LPGhatguy** [comment]
I believe this should be solved in Rojo master, released in the recent 0.6.0 alphas or upcoming 6.0.0 release candidates.
