### ISSUE TITLE
"supplied instant is later than self"

### ISSUE THREAD

**Issue by Kampfkarren** [rojo-rbx/rojo#215]
I just had a Rojo server running in the background for a longtime (no longer than 12 hours?) without even anything syncing when I noticed this panic:

```
thread 'tokio-runtime-worker-1' panicked at 'supplied instant is later than self', src/libcore/option.rs:1034:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
thread 'thread 'tokio-runtime-worker-0tokio-runtime-worker-3' panicked at '' panicked at 'supplied instant is later than selfsupplied instant is later than self', ', src/libcore/option.rssrc/libcore/option.rs::10341034::55
```

The server continued to run.

**Comment by LPGhatguy** [comment]
I'm going to bet this is a Tokio bug!

**Comment by Kampfkarren** [comment]
I can start using RUST_BACKTRACE from now on to see if that's right.

**Comment by Kampfkarren** [comment]
I've left Rojo on for several nights in a row, but have yet to experience this again, strange.

**Comment by LPGhatguy** [comment]
Since we never found a repro, I'm going to close this.

We'll migrate to a newer version of Tokio eventually, which might help resolve any future weirdness.
