### ISSUE TITLE
Preserve PackageLink without defining in default.project.json

### ISSUE THREAD

**Issue by oniich-n** [rojo-rbx/rojo#222]
I would like to use Packages in my current project because of how I can write my code in one place and have it update across multiple places that use it, but rojo **deletes the PackageLink regardless.** ~~makes it tedious to support using said feature because I'd have to define every single PackageLink for every script that I would want to use as a Package. Otherwise, the PackageLink would be deleted every time I sync to Studio.~~ Am I missing or doing something wrong?

**Comment by oniich-n** [comment]
I forgot that `$ignoreUnknownInstances` existed.

**Comment by oniich-n** [comment]
#223

**Comment by oniich-n** [comment]
#223

**Comment by LPGhatguy** [comment]
Based on the comment I left in the PR (#223), I think we can close this issue in favor of using `init.meta.json` or JSON model objects as the preferred solution.
