### ISSUE TITLE
Plugin errors are unclear in the UI

### ISSUE THREAD

**Issue by Jaguar-515** [rojo-rbx/rojo#229]
![EkdoUrfn5h](https://user-images.githubusercontent.com/48777426/62977886-cc4fa980-bdd4-11e9-9265-809a59db2eb8.gif)

As seen in the GIF, I cannot click on the connect button in the plugin.
Has something broke in one of the plugin's scripts?

**Comment by Jaguar-515** [comment]
Oops, I realized I didn't enable HTTP requests in my game. My mistake.

**Comment by LPGhatguy** [comment]
This is an important problem actually, we should create an error state for the plugin to draw attention to errors that Rojo hits!

**Comment by Jaguar-515** [comment]
Oh, I did not realize that. Thanks for reminding me about that!

**Comment by LPGhatguy** [comment]
This is fixed in the master branch, which will be the 0.6.0 release!
