### ISSUE TITLE
Pull auth cookie from registry for Rojo upload

### ISSUE THREAD

**Issue by LPGhatguy** [rojo-rbx/rojo#231]
Roblox Studio stores the user's auth cookie in plaintext in the registry with a little metadata attached. We might be able to grab the user's cookie from there to do asset operations!

**Comment by Kampfkarren** [comment]
> Roblox Studio stores the user's auth cookie in plaintext in the registry with a little metadata attached
Is it just me, or is that scary? O_o

**Comment by LPGhatguy** [comment]
Done in master. Yep, it's scary.
