### ISSUE TITLE
Plugin Dark Theme

### ISSUE THREAD

**Issue by Sleitnick** [rojo-rbx/rojo#241]
It would be nice for the plugin to match Studio's theme. Currently the light theme sticks out quite a bit in Studio. I know this isn't a super high priority, but would be a "nice to have" feature in my opinion.

Screenshot example:

![rojo_theme](https://user-images.githubusercontent.com/5747014/63943245-3acf7100-ca3d-11e9-93d0-04716e640054.PNG)

**Comment by Jaguar-515** [comment]
We could implement that by adding an if/else statement that detects the user's theme on Studio, then the plugin uses the dark theme whenever a user is on dark mode, else, a user is on light mode, the plugin uses it's default theme.
