### ISSUE TITLE
`Name` field required only when building

### ISSUE THREAD

**Issue by vocksel** [rojo-rbx/rojo#244]
`.model.json` files require a `Name` field when using `rojo build`, however they do not require one when syncing in through the plugin.

If possible, using that same behavior for building would be preferable, as the `Name` field feels redundant to have to include when the filename gives the same info.

**Comment by LPGhatguy** [comment]
That's strange, I didn't encounter that when I made this change for 0.5.0!

They should not require a name field in either case.

**Comment by LPGhatguy** [comment]
Do you have a small repro project that we can use to test for this?

**Comment by vocksel** [comment]
Sure, here's a repro project: [repro.zip](https://github.com/rojo-rbx/rojo/files/3905698/repro.zip)

When attempting to build the project, this is what I get:

```
$ rojo build -o test.rbxlx
[ERROR rojo] Malformed .model.json model: missing field `Name` at line 1 column 30 in path c:\projects\repro\src/Test.model.json
```

However, if you create a new place, turn on `HttpEnabled`, and sync the project, the file syncs in fine without the Name field.

**Comment by LPGhatguy** [comment]
This appears to be fixed in Rojo master. If it's still broken in the latest 0.5.0 stable release, I can look into backporting a fix as well.
