### ISSUE TITLE
Allow init scripts to be prepended with an underscore

### ISSUE THREAD

**Issue by Nimblz** [rojo-rbx/rojo#246]
For libraries with many child modules I find myself having to search for init.lua

Rojo should recognize init scripts with a name like `_init`

This sorts these files at the very top of their directory (when sorting alphabetically) and better visually groups them with their parent directory when viewed as a tree (see images).

Without underscore:
![Code_v9m871atqK](https://user-images.githubusercontent.com/5900406/65173990-dc2a6100-da04-11e9-8935-acc53776c7b8.png)

With underscore:
![image](https://user-images.githubusercontent.com/5900406/65173928-b8ffb180-da04-11e9-834a-ad8564b1967d.png)

**Comment by LPGhatguy** [comment]
This makes sense, but I'm unsure if this feature is worthwhile from a duplication and consistency perspective.

A comparison of equivalent features from other languages:
* Lua outside Roblox: `Foo/init.lua`
* Python: `Foo/__init__.py`
* Rust: `Foo/mod.rs` OR `Foo.rs` next to `Foo/`

**Comment by osyrisrblx** [comment]
What happens if you have both `_init.lua` and `init.lua`? Rojo explodes?

**Comment by Nimblz** [comment]
It could skip over that script and warn the user that the source is ambiguous and it cant reconcile that portion.

**Comment by LPGhatguy** [comment]
We already have to face that problem when `init.lua`, `init.server.lua`, `init.client.lua`, and `init.meta.json` are specified together. Right now, we just do Something Unspecified, but we should probably tell the user something is up.

**Comment by LPGhatguy** [comment]
I'm going to go ahead and close this issue. We can revisit it at a later time, but I think consistency is more important right now.
