### ISSUE TITLE
LSP-like protocol

### ISSUE THREAD

**Issue by Kampfkarren** [rojo-rbx/rojo#247]
This was briefly talked about on Discord, but it'd help for projects like roblox-lua-autofills if they could connect to the Rojo server and use it to receive useful information similar to an LSP.

Currently, roblox-lua-autofills attempts to recreate the entire file structure based on projects itself, and will sometimes make mistakes for multiple project files since it's not possible for it to figure out which project you're working on. However, Rojo always knows what files it has knowledge of and where, making these problems obsolete.

I'm not sure what in specific is needed, but it is a neat idea.

**Comment by LPGhatguy** [comment]
We should be able to cover this by expanding and stabilizing the Rojo HTTP API!

**Comment by Dekkonot** [comment]
Sourcemaps resolve this
