### ISSUE TITLE
Rojo Live Sync page should be updated in terms of design

### ISSUE THREAD

**Issue by Jaguar-515** [rojo-rbx/rojo#255]
Whenever you successfully execute `rojo serve` and you go to localhost:34872, the page currently looks like this:
![image](https://user-images.githubusercontent.com/48777426/66360869-6f362700-e931-11e9-92fc-1c4c2a4d1688.png)
Why not give this page some love and make it somewhat detailed?

**Comment by MichaelMcDonnell** [comment]
What kind of love and detail do you think it should have?

**Comment by Nimblz** [comment]
It would make sense to align the styling with rojo.space

**Comment by Jaguar-515** [comment]
@MichaelMcDonnell I would love to have the page similar to rojo.space's design...
@Nimblz I agree!

**Comment by LPGhatguy** [comment]
This page is already updated in the master branch (what will be 0.6.0) with some fairly detailed diagnostic information!

![image](https://user-images.githubusercontent.com/654598/67057597-035c7700-f106-11e9-80c4-51b44765160d.png)

![image](https://user-images.githubusercontent.com/654598/67057586-f3449780-f105-11e9-957f-b6916b87ea0c.png)

It could definitely use a design uplift, but it's much much more useful than the current page.

**Comment by LPGhatguy** [comment]
The page has been improved even a little more yet. I'm going to consider this issue resolved, for any other changes, take a look at the master branch and we can go from there!
