### ISSUE TITLE
Model files named init.model.json results in an instance named "init" instead of the name of the parent directory

### ISSUE THREAD

**Issue by Phalanxia** [rojo-rbx/rojo#263]
Model files named init.model.json results in an instance named "init" instead of the name of the parent directory.

**Steps to reproduce:**
1. Create a new Rojo project.
2. Create a project file with a StarterGui folder.
3. Create a folder named "MainScreenGui" inside of the StarterGui folder.
4. Inside the MainScreenGui folder create two instances. One `init.model.json` file with the ScreenGui ClassName. And an empty script named `TestScript.client.lua`.
5. Rojo sync these into an empty baseplate.

Repro project file: [RojoModelRepro.zip](https://github.com/rojo-rbx/rojo/files/3806494/RojoModelRepro.zip)

**Expected results:**
A ScreenGui named "MainScreenGui" is created, with the "TestScript" being a child of this instance.

![image](https://user-images.githubusercontent.com/513906/68165747-14cebd00-ff15-11e9-8f43-941fa4122d58.png)

**Actual results:**
A ScreenGui named "init" is created. Both TestScript and the ScreenGui are parented to a folder named "MainScreenGui".

![image](https://user-images.githubusercontent.com/513906/68165724-041e4700-ff15-11e9-8a5b-6b5a0a0723a6.png)

Tested in Rojo 0.5.3

**Comment by LPGhatguy** [comment]
Resolved offline!

We don't support `init.model.json` anymore as of 0.5.0: https://rojo.space/docs/0.5.x/guide/migrating-to-epiphany/#migrating-initmodeljson-files
