### ISSUE TITLE
Ignore paths starting with a dot (like .git)

### ISSUE THREAD

**Issue by Kampfkarren** [rojo-rbx/rojo#264]
When I check `localhost:34872`, I see Rojo is tracking a lot in my `.git` folder.

![image](https://user-images.githubusercontent.com/3190756/68655172-60b8cd80-04e4-11ea-8c6a-7ae039d655be.png)

This seems at best unnecessary, at worst inoptimal. I would like these to be ignored by default. What's weird is they're not even in any of my partitions, is this an issue of something else?

**Comment by Kampfkarren** [comment]
![image](https://user-images.githubusercontent.com/3190756/68656002-dc674a00-04e5-11ea-8fe1-6c7ccc8af70c.png)
Oh no!

**Comment by LPGhatguy** [comment]
Do you have a project file? This should only be happening if you don't have one, or it's pointing to a Git repo as part of its path!

**Comment by Kampfkarren** [comment]
This was because I didn't specify a project file.
