### ISSUE TITLE
Rojo on master will sometimes not delete old scripts when restarted

### ISSUE THREAD

**Issue by Kampfkarren** [rojo-rbx/rojo#290]
I am not using `.meta.json` with `ignoreUnknownProperties` or anything similar. Occasionally, scripts will not get deleted and will then be duplicated when I use Rojo on master. I believe this happens when I restart the server sometimes. I have no repro case. I regularly have to run a script to search for duplicated script names because of this.

**Comment by LPGhatguy** [comment]
Are you still able to reproduce this on the latest master?

**Comment by Kampfkarren** [comment]
Doesn't seem to happen anymore.

**Comment by LPGhatguy** [comment]
Looking for the smallest repro possible on this bug! Duplication bugs like this are top priority.

**Comment by LPGhatguy** [comment]
This issue is likely resolved on Rojo master now that #332 has merged. If you're able to reproduce this when the next release candidate is released, please re-open this issue and we can track this down.
