### ISSUE TITLE
Children of scripts are removed upon commit of edit

### ISSUE THREAD

**Issue by TheFortex** [rojo-rbx/rojo#292]
If i put a bindable event parented to a script or a local script and edit that script from VS through Rojo it updates normally but all children are gone...

**Comment by Kampfkarren** [comment]
Intended behavior--you can use a meta.json file to tell an instance to keep its unknown children.

Create a file named `YourScriptName.meta.json` with:

```json
{
    "ignoreUnknownInstances": true
}
```
