### ISSUE TITLE
Rojo 0.6.0-alpha1 crashes when using rojo init

### ISSUE THREAD

**Issue by Jaguar-515** [rojo-rbx/rojo#298]
![image](https://user-images.githubusercontent.com/48777426/75742032-438d5200-5cc1-11ea-8172-62ef0c6e8f31.png)

I attempted to initalize a project in an empty folder, however, it appears Rojo crashes when using `rojo init`.

**Comment by Jaguar-515** [comment]
I realized that rojo init is not yet implemented... this is really poor UX.

**Comment by LPGhatguy** [comment]
It's an alpha! I intended to finish the command before the release but decided some larger changes needed to happen.

Thanks for your report, though, this is a good reminder.
