### ISSUE TITLE
C stackoverflow plugin error

### ISSUE THREAD

**Issue by DarrenVs** [rojo-rbx/rojo#299]
## Description
Got a C stackoverflow error in the v0.5.4 Rojo Roblox Studio plugin:
![image](https://user-images.githubusercontent.com/2780639/75804380-23709800-5d80-11ea-9e17-2d60b13d700b.png)

## Cause
Error appeared after long period of pc idle time *(check error log timestamps)*.
Might be another reason but I have no clues to what else it could be as my pc was idle the entire time.
I had to restart studio to get the plugin syncing again. Visual Studio reports no issues from the Rojo addon.

I hope this helps

**Comment by LPGhatguy** [comment]
Thanks for the bug report!

I think this might be a bug deep down in Rojo's promise implementation. Generally it's tough to track these kinds of bugs down and they might disappear with just about any change :(

**Comment by boatbomber** [comment]
We use evaera's promise lib that is very battle tested and we haven't seen this issue for years now.
