### ISSUE TITLE
Source mappings don't accept the wrong kind of slash

### ISSUE THREAD

**Issue by zjturner** [rojo-rbx/rojo#301]
I'm on Windows and I was following the installation guide to set up a new repository.  While serving, I decided to change my `ReplicatedStorage` folder from `src` to `src/ReplicatedStorage`.  This results in the following error:

```
thread 'ChangeProcessor thread' panicked at 'snapshot failed: SnapshotError { detail: IoError { inner: Os { code: 2, kind: NotFound, message: "The system cannot find the file specified." } }, path: Some("C:\\roblox\\src/ReplicatedStorage") }', src\libcore\result.rs:1188:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
thread 'tokio-runtime-worker-0' panicked at 'called `Result::unwrap()` on an `Err` value: "PoisonError { inner: .. }"', src\libcore\result.rs:1188:5
```

The problem appears to be the use of a forward slash in the path `Some("C:\\roblox\\src/ReplicatedStorage")`

Changing to a backslash fixes the problem.

**Comment by LPGhatguy** [comment]
Have you been able to make a smaller repro for this?

**Comment by LPGhatguy** [comment]
If you're able to create a repro case for this, feel free to re-open this issue and I can take a look!
