### ISSUE TITLE
Rojo Not Opening

### ISSUE THREAD

**Issue by BattleXGamer** [rojo-rbx/rojo#306]
I try to run but it close

**Comment by LPGhatguy** [comment]
Hi, thanks for filing an issue!

Rojo is a command line application, which means you need to run it from a terminal on your system, like `cmd.exe` on Windows or Bash on Linux or macOS.

Check out the Rojo 0.5 guide for a quick introduction on how to use Rojo: https://rojo.space/docs/0.5.x/guide/new-game/
