### ISSUE TITLE
Rojo plugin should differentiate between "connection initializing" state and "connected" state

### ISSUE THREAD

**Issue by Quenty** [rojo-rbx/rojo#309]
A common issue with using Rojo is pressing the "Connect" button and not having the actual server running in the background. This is ok, but sometimes it's not clear this is the case, because as soon as you press the "Connect" button, the plugin window shows "Connected" with a call to action "Disconnect" instead of a "Connecting" state.

Rojo should differentiate between connecting pending, and connection initialized, so that this confusion can be avoided.

**Comment by LPGhatguy** [comment]
This is already the case in the Rojo master branch, and is available in the Rojo 0.6 alphas as well!
