### ISSUE TITLE
Rojo crashes while using serve

### ISSUE THREAD

**Issue by Jayz2** [rojo-rbx/rojo#310]
when I try to use serve, it says:
[ERROR] Rojo crashed!
[ERROR] This is probably a Rojo bug.
[ERROR]
[ERROR] Please consider filing an issue: https://github.com/rojo-rbx/rojo/issues
[ERROR]
[ERROR] Details: TODO: Handle csv errors: Error(UnequalLengths { pos: Some(Position { byte: 59, line: 3, record: 2 }), expected_len: 1, len: 2 })
[ERROR] in file src\libcore\result.rs on line 1188
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

**Comment by LPGhatguy** [comment]
Thank you for the report! You should be able to fix this in your own project by ensuring that your CSV files are correctly formatted.
