### ISSUE TITLE
Rojo 6 is unreliable at deleting files

### ISSUE THREAD

**Issue by LouieK22** [rojo-rbx/rojo#312]
In Rojo 6, if a file is deleted while the server is running, but the plugin is not, the file will not be removed from the DataModel. If that file is re-added to the filesystem, it will create a second instance in the DataModel and crash Rojo.

Using the same project setup with Rojo 0.5.x the file is removed when the plugin connects to the server.

Two-way sync is **not** enabled.

**Repro steps**
1. Start both server and plugin
2. Stop plugin
3. Delete a file
4. Start plugin
5. File won't be deleted
6. Undo the delete (e.g. with Git)
7. Rojo crash

**Comment by LPGhatguy** [comment]
Thanks for the report, I'm glad we could find a repro for this issue. I've seen a couple reports but generally no reproduction steps!

**Comment by LPGhatguy** [comment]
This issue should now be fixed on the Rojo master branch.
