### ISSUE TITLE
The system cannot find the file specified. (os error 2)

### ISSUE THREAD

**Issue by VaneHD** [rojo-rbx/rojo#318]
I have rust and rojo fully setup and installed, when I press CTRL + SHIFT + P and go to start the server I get that error.

**Comment by Masken8** [comment]
Do you have Server, Client and Shared folders with at least one file in each?

**Comment by VaneHD** [comment]
![image](https://user-images.githubusercontent.com/50462086/81281831-43f3f180-9052-11ea-9f7c-fc9f573841bb.png)

![image](https://user-images.githubusercontent.com/50462086/81281848-4c4c2c80-9052-11ea-8dbd-a75d8260b00d.png)

![image](https://user-images.githubusercontent.com/50462086/81281909-6128c000-9052-11ea-9ee6-6de92c24a48a.png)

@Masken8 , not sure.

**Comment by Masken8** [comment]
Can I see default.project.json

**Comment by VaneHD** [comment]
there is two default.project.json, which one?

**Comment by VaneHD** [comment]
still don't know what the issue is, Ive tried many many things.

**Comment by Reshiram110** [comment]
@VaneHD This error occurs when you specify a non-existent file in your `*.project.json` configuration file. This is not a bug - you are specifying a file that doesn't exist. Check your config file for any typos or missing folders.

**Comment by LPGhatguy** [comment]
This error message should be much more clear as of Rojo 6.0, which has a release candidate available now.
