### ISSUE TITLE
Add a support of JSONC

### ISSUE THREAD

**Issue by ViniDalvino** [rojo-rbx/rojo#322]
The support of json for making module script could be improved by adding a jsonc. json c is a varient of json that allow comment. adding the support for JSONC would improve rojo as it would allow commenting part of the json to note some extra information on what the module contain.

**Comment by LPGhatguy** [comment]
I believe this falls under #207! There are a couple different ways we can allow comments. The JSON variant that I looked into is **JSON5**, but JSONC is also an option I think.

I'm going to close this issue in favor of discussion on #207, since we have multiple options for tackling this idea.
