### ISSUE TITLE
Exclude patterns for rojo build

### ISSUE THREAD

**Issue by amoss-roblox** [rojo-rbx/rojo#325]
Feature Request for the ability to specify exclusion patterns for rojo build (maybe should also apply to sync, dependent on workflow).

Use case: Exclude .spec.lua files from release RBXMs.

Similar ideas: npmignore, dockerignore etc.

**Comment by Jaguar-515** [comment]
Couldn't a .gitignore file do the job (if you are using Git)? You'll still be able to release model files without including .spec.lua files/etc. if you tell Git to ignore the files in the .gitignore.

**Comment by amoss-roblox** [comment]
> Couldn't a .gitignore file do the job (if you are using Git)? You'll still be able to release model files without including .spec.lua files/etc. if you tell Git to ignore the files in the .gitignore.

Not in this case - the .spec.lua files (aka the unit tests) are checked in alongside the rest of the source.

**Comment by LPGhatguy** [comment]
If you build Rojo from the master branch from source, you can enable the `unstable_glob_ignore_paths` Cargo feature. This enables the `glob-ignore-paths` key in your project file, which is a list of globs to ignore.

Can you give this feature a try? I want to remove the flag and enable it by default in the next release candidate as part of the Rojo 6.

**Comment by LPGhatguy** [comment]
`globIgnorePaths` has now been enabled by default and the `unstable_glob_ignore_paths` feature flag has been removed. Expect to see it in the next prerelease!
