### ISSUE TITLE
Roblox: String too long

### ISSUE THREAD

**Issue by thenerdie** [rojo-rbx/rojo#328]
https://i.imgur.com/FdQvmZ3.png

Whenever I start the server, the plugin spits out an error saying that a script's source is too long to be copied. I have ModuleScripts in this game that are absolutely huge (note data) and there is nothing I am able to do about it. Are there any workarounds available or are there plans to fix this? Since this is a Lua plugin I would be happy to start on this.

**Comment by Kampfkarren** [comment]
Fixed in 0.6.0 by #199

**Comment by LPGhatguy** [comment]
Closing as a duplicate of #199.

I was hoping that Roblox would fix this issue before we needed to address it in Rojo/
