### ISSUE TITLE
Two-Way Sync causing instant crash upon connecting

### ISSUE THREAD

**Issue by Meqolo** [rojo-rbx/rojo#329]
When connecting to a rojo server with two-way sync enabled, it results in the server crashing with this error 100% of the time: 
![image](https://user-images.githubusercontent.com/45327591/85201235-a39e1780-b2f5-11ea-8967-70d4ce4ed057.png)

**Comment by Dionysusnu** [comment]
that's this line: `fs::write(path, value).unwrap()`.
maybe your folder is read-only?

**Comment by kennethloeffler** [comment]
Closing this as a duplicate of #790 since there's more information there
