### ISSUE TITLE
Generating scripts depending on command line

### ISSUE THREAD

**Issue by GlowingUmbreon** [rojo-rbx/rojo#334]
A feature request I have which may be helpful in some situations
```
print('scripts before this go uneffected')

--if flag_test = "true" (custom flag for use with rojo build or rojo serve)
local debugMode = true 
print('debug mode forced to true by command line')
--if flag_test = "false"
local debugMode = false
print('debug mode forced to false by command line')
--elseif buildType == 'build' (For if it is being build by the rojo build command)
local subCommand = false
print('Script generated by build subcommand')
--elseif subCommand = 'serve' (For if the script is being synced to roblox)
local debugMode = true
print('Script generated by serve subcommand')
--else
local debugMode = false
print('Unsure of build type, debugmode reverting to false')
--end

print('scripts after this go uneffected')
```

Example outputs:
rojo serve
`(debugMode = true, 'Script generated by serve subcommand')`

rojo serve --test false
`(debugMode = false, 'debug mode forced to false by command line')`

rojo build
 `(debugMode = false, 'Script generated by build subcommand')`

rojo serve --test true
`(debugMode = true, 'debug mode forced to true by command line')`

rojo upload
`(debugMode = false, 'Unsure of build type, debugmode reverting to false')`

Sorry if this is hard to understand, I tried to make it as understandable as possible.

**Comment by LPGhatguy** [comment]
I believe this issue is similar in spirit to #160. Does that line up with what you're proposing? If so, I'd love to expand on that feature idea to include this idea and close this issue.

**Comment by GlowingUmbreon** [comment]
> I believe this issue is similar in spirit to #160. Does that line up with what you're proposing? If so, I'd love to expand on that feature idea to include this idea and close this issue.

While that idea is kind of similar to this idea it isn't the same. This idea is about having the outputted script diffrent depending on diffrent factors, So if it is built as a model a snippet of a script can be diffrent than if it is live synced.

If I was to give an example it would be c/c++'s #if #elseif directives [Link](https://docs.microsoft.com/en-us/cpp/preprocessor/hash-if-hash-elif-hash-else-and-hash-endif-directives-c-cpp?view=vs-2019)
```c
#if flag_debug == 'true'
-- This part only gets built if a variable with flag_debug is true
#else
--This part gets built if it is something else
#endif
```

**Comment by Kampfkarren** [comment]
This sounds like something that should be solved with plugins more than made an official thing by Rojo.

**Comment by GlowingUmbreon** [comment]
> This sounds like something that should be solved with plugins more than made an official thing by Rojo.

Yeah I thought something similar before I made this issue.
