### ISSUE TITLE
Rojo VSC & Studio plugin will not sync; powershell 'rojo' string not found

### ISSUE THREAD

**Issue by itsyaaboyray** [rojo-rbx/rojo#338]
I've been trying to install Rojo onto my PC for about 3 days now, I've asked several DevForum members on the Roblox Discord for help on this problem. They have no clue how to troubleshoot this.

I followed the documentation pages on the rojo.space website. I've also followed the VSC guide on the plugin, and tried multiple reinstalls / resets. I've gone as far as reformatting my hard drive to fix this problem.

**If this is not the place to post this issue, then I don't know where else to post because this is the only page on the internet that has direct contact to the developers of rojo.**

### Starting rojo on Visual Studio Code:
`[ERROR rojo] c:\Users\Admin\Documents\AloneInADarkHouse\src: The system cannot find the file specified. (os error 2)`

### rojo Studio Plugin outputs after attempting to connect:
`18:51:39.323 - [Rojo-Warn] Rojo session terminated because of an error:
18:51:39.325 - [Rojo-Warn] Couldn't connect to the Rojo server.
18:51:39.326 - [Rojo-Warn] Make sure the server is running -- use 'rojo serve' to run it!`

### Entering 'rojo serve' into terminal / powershell:
`rojo : The term 'rojo' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ rojo serve
+ ~~~~
    + CategoryInfo          : ObjectNotFound: (rojo:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException`

### Using 'Rojo Initialize' command prompt:
`Command 'Rojo: Initialize' resulted in an error (Command failed: c:\Users\Admin\AppData\Roaming\Code\User\globalStorage\evaera.vscode-rojo\rojo-v0.5.4.exe init [ERROR rojo] Project init error: Path c:\Users\Admin\Documents\AloneInADarkHouse\default.project.json already exists )`

**Comment by LPGhatguy** [comment]
Hello! I just transferred this repository from the [rojo.space repository](https://github.com/Roblox/rojo.space) to the [Rojo repository](https://github.com/Roblox/rojo). The first repository is where Rojo's website is hosted, while this repository is for Rojo itself.

**Comment by itsyaaboyray** [comment]
After creating the 'src' folder in the directory, rojo can start.
Rojo doesn't sync files from the game to the editor, though.

**Comment by OverHash** [comment]
Looks like your place file has some missing files. Can you show us your file tree in Visual Studio Code's explorer and your `default.project.json`?

For the "Entering 'rojo serve' into terminal / powershell" problem, if you have the rojo extension installed (which it looks like you do, as you ran the `Rojo: Initialize` function which is a part of the Visual Studio Code extension), you can just press "start server" at the bottom status bar of Visual Studio Code.

**Comment by LPGhatguy** [comment]
The first-time user experience of initializing a project has been fixed, which is the first issue you ran into. Rojo is telling you that a folder doesn't exist; you need to make it.

The second issue is something that trips up users who are new to terminals. Basically, you can install Rojo for use on the command line, or you can use the VS Code extension. Installing the VS Code extension does not make Rojo available for use on your terminal, which is the error you're getting.
