### ISSUE TITLE
Missing EnumItem for Enum.Technology.Future

### ISSUE THREAD

**Issue by VernandoGames** [rojo-rbx/rojo#341]
![image](https://user-images.githubusercontent.com/30465911/87202704-b38e9300-c2c6-11ea-9309-22a988e88f49.png)

**Comment by LPGhatguy** [comment]
This will require an update to Rojo's reflection database, `rbx_reflection`.

In the meantime, you can use an [explicit property declaration](https://rojo.space/docs/6.x/project-format/#instance-property-value) to assign an enum value directly. This is less clear than Rojo's detection of strings as enums, but should always work.

**Comment by LPGhatguy** [comment]
Going to close this issue; gracefully handling this is fixed as part of Rojo 6.0 and the actual property should be fixed as part of the next natural Rojo release.
