### ISSUE TITLE
Create selene.toml for Roblox projects when rojo init is run

### ISSUE THREAD

**Issue by unix-system** [rojo-rbx/rojo#342]
Reasoning behind this: we already ``git init`` and create a repository, so I don't see why we shouldn't extend this utility to selene as the command is already not tooling agnostic.

Pain Point: I have to create a new selene.toml every time I ``rojo init``, and due to how the selene VSCode extension works (I'm going to make a PR to fix this on their side) I have to restart VSCode after that. It's annoying and I'm sure a lot of people who use selene have encountered the same issue.

I'll make a PR for this, but I'll link it back to here if anyone has any points to bring up about if this is the approach that would be most effective.

**Comment by Jaguar-515** [comment]
This should be an optional flag to `rojo init` since there are some people who don't use selene in their Rojo projects.

**Comment by Kampfkarren** [comment]
There's also people who don't use git in their Rojo projects, but those are still created on init. Adding things like this behind configuration basically just ensures they go unused.

**Comment by unix-system** [comment]
I agree with @Kampfkarren here - if we have a flag set here, then it should be a positive "I don't want selene, kthx" flag (perhaps rojo init --basic) for no git/selene?

Another solution - we could detect other popular linting solutions already in the project, and if present, don't create the selene.toml file. Would require some market research though - anyone got any pointers as to common lua linter config files?

**Comment by Kampfkarren** [comment]
`.luacheckrc` is the only other one in use.

**Comment by LPGhatguy** [comment]
I do not agree that Rojo initializing a Git repository should be considered not tooling agnostic. I would accept a flag for skipping initialization of a Git repo if that is something users would want to skip in practice.

Git is likely the only VCS in use by Rojo users. However, as far as linters go, there exists Luacheck, Selene, and the eventual Roblox script analyzer CLI. If that market settles down, I would be interested in auto-initializing those projects, maybe all optionally, but for now I'm not.

One example is that Roblox internally does not use Selene, but they use Git. Having the same flag that skips Selene also skip Git would be inappropriate for them, as well as other teams in a similar boat.

**Comment by Kampfkarren** [comment]
I think Luacheck specifically will/should be phased out simply because of how much new incompatible syntax is being added. I can see the thinking behind the rest, though.

**Comment by LPGhatguy** [comment]
I won't be pursuing this issue for now, but might be something that gets revisited later.
