### ISSUE TITLE
"Cannot update an instance that does not exist in the reconciler's state"

### ISSUE THREAD

**Issue by optimisticside** [rojo-rbx/rojo#348]
I was connecting to my server with Rojo, when I had gotten this error. It stated that it was unable to "update an instance that does not exist in the reconciler's state". Below is a screenshot of what appeared in the output window.
![image](https://user-images.githubusercontent.com/47266822/88483060-51669c80-cf1a-11ea-9e04-0d4a24c18d00.png)

**Comment by LPGhatguy** [comment]
Hello, thank you for the bug report!

I've seen this pop up from time to time, but I don't have a good reproduction case for it. I'm hoping a lot of this will be solved by #332, but we can't know for sure.

**Comment by Minstrix** [comment]
Happens for me any time I edit a file in studio with two-way sync enabled.

**Comment by LPGhatguy** [comment]
This bug should be fixed in the Rojo master branch.
