### ISSUE TITLE
cloud_4048317704.Rojo.Plugin.Reconciler:161: unwritable property

### ISSUE THREAD

**Issue by nievadev** [rojo-rbx/rojo#353]
I get this error whenever I want to connect. I can't connect anymore to the localhost.

This happened because I modified the default.project.json and added a simple Workspace to the tree. I removed the Workspace of the default config because I didn't want some stuff to be overwritten, since I'm porting this project. Everything worked as a charm. However, now that I added it again, it doesn't, it doesn't even connect, and I tried: undoing the changes, uninstalling and installing, serving again, nothing changed :(

**Comment by nievadev** [comment]
It seems that the Workspace got somehow "broken"? I don't know, but it must be something internal in Roblox Studio that makes Rojo crash. God damn it.

**Comment by nievadev** [comment]
Well, turns out the Workspace thing was not the "causer" of the problem. I had a .rbxmx file in some place that when connecting was trying to sync with the project, but the project in Roblox Studio already had that file, so it threw the unwritable property somehow. Phew! Thanks god I just fixed this!
By the way, LPGhatguy, you are amazing! I wrote you in Twitter, but you didn't respond :( I love you man! Thank you for such contribution to the community :)

**Comment by nievadev** [comment]
Oh, just re-opened issue, because I think that the "causer" of this problem is that Rojo can't set the PrimaryPart from a .rbxmx file (maybe, just a vague guess). I shouldn't have closed the issue though, the issue is still there, dunno why did I close it.

**Comment by LPGhatguy** [comment]
This should now be fixed on Rojo's master branch, which I'll hopefully release as part of a Rojo 6.0 release candidate soon.
