### ISSUE TITLE
I am unable to connect rojo even though it is running in vs code.

### ISSUE THREAD

**Issue by jakebball** [rojo-rbx/rojo#356]
Ever since last week I am unable to use rojo. I start out by starting the server in vs code in which no errors show up in the output and it states that rojo is listening on the same port but when I then go to roblox studio and click connect I get the error `16:47:49.804 - [Rojo-Warn] cloud_1997686364.Rojo.Plugin.Reconciler:164: attempt to index nil with 'GetFullName'.` I even reinstalled rojo on roblox and still nothing works.

**Comment by LPGhatguy** [comment]
This should now be fixed on Rojo's master branch, which I'll hopefully release as part of a Rojo 6.0 release candidate soon.
