### ISSUE TITLE
Roblox Studio crashes when opening a script while the Rojo server is running

### ISSUE THREAD

**Issue by fredgig** [rojo-rbx/rojo#357]
OS: macOS Catalina version 10.15.5
Rojo: Rojo 6.0.0-rc.1

No output is given by Rojo or Roblox Studio.

Steps to replicate:

1. Run rojo-serve
2. On Roblox Studio, open any script that is part of your Rojo project
3. Crash

**Comment by LPGhatguy** [comment]
Hi, thanks for the report. Do you have the "Open Scripts Externally" option checked in the plugin? I believe that a somewhat recent Roblox Studio update now causes the technique that feature uses to crash.

**Comment by fredgig** [comment]
Seems like this isn't an issue anymore, I haven't updated Rojo since a month or two. If the issue ever resurfaces, where exactly can I change the Roblox plugin's options?
