### ISSUE TITLE
Roblox Studio scripts do not update when the corresponding lua file is updated in the Rojo project

### ISSUE THREAD

**Issue by fredgig** [rojo-rbx/rojo#358]
OS: macOS Catalina version 10.15.5
Rojo: Rojo 6.0.0-rc.1

Scripts only update when I connect to the Rojo server from the Roblox Studio plugin.

Any changes made to the lua files within the Rojo project while the server is running will not be applied to the Roblox scripts.

Steps to replicate:

1. Run rojo-serve
2. All Roblox scripts will be updated
3. Make a change to any lua file within the Rojo project
4. The corresponding script in Roblox Studio will not be updated

**Comment by LPGhatguy** [comment]
Hello, this issue may be solved on the Rojo master branch. I will be pushing a new release candidate for Rojo 6.0 in the coming days that will make it easy for us to find out.
