### ISSUE TITLE
Rojo 5.4 Serve Issues

### ISSUE THREAD

**Issue by RazorBladedino117** [rojo-rbx/rojo#361]
Hello! I'm RazorBladedino117, a scripter. I have 2 repositories on github, which are a part of the same game (but different places). I like to have them both opened and synced, but there is an issue. Even when I change the serve port in the rojo.json file, when I go Rojo Start Serve (Or click the rojo button in the vsc extension), it always listens on the same port(34872), can someone help me fix this?! Thanks!

**Comment by LPGhatguy** [comment]
Hello, thanks for the bug report.

If you're using Rojo 0.5.4, you need to set that property in `default.project.json`. `rojo.json` is only used in very old versions of Rojo and is not relevant.

Based on [this file in this project I found on your profile](https://github.com/RazorBladedino117/AGF-Test/blob/main/default.project.json), it looks like your port is set to the default. Have you tried changing that port?

**Comment by LPGhatguy** [comment]
I'm going to go ahead and close this issue, as I don't believe it is a Rojo bug. Feel free to ask any further questions in the Discord server linked from this page in the documentation: https://rojo.space/docs/help/
