### ISSUE TITLE
'Auto-Connect' plugin setting

### ISSUE THREAD

**Issue by ilvfie** [rojo-rbx/rojo#362]
Not needing to press connect on rojo's panel would be a nice quality of life feature, and could save panel space.

**Comment by Minstrix** [comment]
I don't think this is a good idea, what happens if you're using Rojo in one place and then open another place to copy something over only to find you've now synced your entire Rojo project into it. Not worth the 5 seconds it saves.

**Comment by LPGhatguy** [comment]
This kind of feature is remarkably tricky. Users often do not want to connect all the time, and trying to connect involves sending an HTTP request, which may pop up a permission prompt.

There might be a way that we can implement this in a controlled way, but it might not be as useful as you're hoping.

**Comment by osyrisrblx** [comment]
I have a workflow where I use `rojo build` + `rojo serve`.

Would be really nice if I could add a special StringValue or something that indicates Rojo should automatically connect with default settings when that place opens.

**Comment by boatbomber** [comment]
I believe that the `rojo open` proposal covers this, so I'm going to close this issue and direct traffic to #305.
