### ISSUE TITLE
rojo warn error

### ISSUE THREAD

**Issue by dolfijn3000** [rojo-rbx/rojo#365]
i get this error when i try to connect studio with rojo.

`[Rojo-Warn] user_Rojo.rbxm.Rojo.Plugin.ApiContext:71: invalid argument #4 to 'format' (string expected, got nil)`

can someone help me please ?

**Comment by LPGhatguy** [comment]
Hello, thank you for the bug report. Looking at [the relevant section of code](https://github.com/rojo-rbx/rojo/blob/dff2df4c79202bc3b5c491b90589c75de77f1e23/plugin/src/ApiContext.lua#L70-L84), it looks like you are using the wrong server for the version of the plugin you have.

Make sure you're using the same server and plugin versions. If you're using Rojo 0.5.4 in the plugin, make sure you're using the 0.5.4 Rojo server as well.
