### ISSUE TITLE
Open Scripts Externally Causing Studio Crash

### ISSUE THREAD

**Issue by will-cs** [rojo-rbx/rojo#369]
Enabling the "Open Scripts Externally" setting will cause Studio to crash with the "An unexpected error has occurred and Roblox needs to quit." message after attempting to open a script.

Little bit of a weird part here, if you have "Open Scripts Externally" enabled and "Two-Way Sync" disabled Studio seems to crash after the **third** attempt to open a script, with nothing happening after the first two attempts. In this scenario, there are no messages in the output. 

However, if you have both "Open Scripts Externally" and "Two-Way Sync" enabled, Studio will crash on the **first** attempt to open a script and there will be a [Rojo-Warn] message in the output reading "Cannot sync non-nil Parent property changes yet."

Using version `6.0.0-rc.3` and VSCode.

**Comment by jonahnm** [comment]
I also have this issue and it has still not been fixed.

**Comment by LPGhatguy** [comment]
This should be fixed up! This will be part of 6.1.1 and 7.0.0-alpha.4.
