### ISSUE TITLE
Rojo removes uncontrolled items in target folder

### ISSUE THREAD

**Issue by vsDizzy** [rojo-rbx/rojo#370]
I'm synching only two scripts, and every other item is deleted.

![img](https://cdn.discordapp.com/attachments/596685628792373264/779841700323131442/unknown.png)

Here is how the node is defined in `default.project.json`:
```json
        "Scripts": {
          "$className": "Folder",
          "$path": "out/laser"
        }
```

**Comment by vsDizzy** [comment]
Setting `"$ignoreUnknownInstances": true` resolved this issue.

**Comment by Kampfkarren** [comment]
Not a bug, intentional behavior.
