### ISSUE TITLE
Rojo deletes scripts in studio if they are not found in the rojo folder externally

### ISSUE THREAD

**Issue by LemonDoo** [rojo-rbx/rojo#375]
**This issue starts occuring after release rc.1!** (rc.2 - 4 all have it)

For example, I have scripts within my src/server folder that is directly linked to ServerScriptService.

On the previous update, I could also store other scripts that were not part of Rojo inside ServerScriptService that would not be wiped whenever I served rojo.

However, when I updated to this latest version, when I tried to connect, a lot of my modulescripts instantly disappeared.

I purposely don't sync certain modulescripts because they are either
1. External libraries (DataStore2)
2. Roblox default folders (PlayerModules in StarterPlayerScripts)

These I have no intention of modifying with Rojo as they have submodules parented directly to the root modulescripts, a feature that Rojo cannot support with its file system. 

This is a major issue as I will have to refactor all my code so all the rojo files are within their own folders (which makes things less clean as well) if this is not fixed.

**Comment by LemonDoo** [comment]
![image](https://user-images.githubusercontent.com/18073605/102327530-b8710600-3f3a-11eb-861b-13b56985fc46.png)

For example, stuff like this. This should not be replicated under Rojo!

**Comment by LemonDoo** [comment]
Reverted to 6.0.0-rc.1 manually and created my own plugin - problem resolved for now?

**Comment by LemonDoo** [comment]
Apparently this may be a feature?

https://github.com/rojo-rbx/rojo/commit/2136da15d6d304a76eef33e9db8d84ad974409a9

**Comment by Kampfkarren** [comment]
This is intentional, and is why `$ignoreUnknownInstances` is a thing:

- For a folder
https://rojo.space/docs/6.x/sync-details/#meta-files-to-set-rojo-metadata

- For a tree path
https://rojo.space/docs/6.x/project-format/#instance-description

**Comment by LPGhatguy** [comment]
If these instances that are not managed by Rojo were not deleted before, then that was a bug in 6.0.0-rc.1 that must have been fixed since.

This is the intended behavior of Rojo, and it is how the latest stable release (0.5.4) works as well. I would recommend using the latest stable release when possible, as it is less likely to have misleading bugs than pre-release versions.
