### ISSUE TITLE
ignoreUnknownInstances is ignored in both meta and project files

### ISSUE THREAD

**Issue by RealExoctic** [rojo-rbx/rojo#376]
ignoreUnknownInstances is ignored and unknown instances are still removed on sync.
https://sharex.realexoctic.xyz/ShareX/2020/12/2020-12-16%2021-16-23.mp4

How to repo:
-   Download the repo.rar file: https://sharex.realexoctic.xyz/ShareX/2020/12/repo.rar
-    Extract it and then open it as a folder with VSCode
-    Start a Rojo server
-    Connect to the Rojo server with the plugin

**Expected result**: The part in Tools remains untouched
**Given result:** The part gets destroyed by Rojo

Version ` 6.0.0-rc.4` with the VSCode Extension

**Comment by LPGhatguy** [comment]
`$ignoreUnknownInstances` does not apply recursively, for both project and meta files. It never has; it only applies to the direct children of an instance. This confusion is known, and I am considering adding a new alias for the property along the lines of `$ignoreUnmanagedChildren`.

Do you have a repro case that applies when `$ignoreUnknownInstances` is applied directly to a container, and that container erroneously deletes children? If not, I am going to close this issue as invalid for now.

**Comment by RealExoctic** [comment]
Applying `$ignoreUnknownInstances` directly to a folder or well a "container" still removes all of it's children, even if the method used is the same as in https://rojo.space/docs/6.x/sync-details/#meta-files-to-set-rojo-metadata

Second repo project: https://sharex.realexoctic.xyz/ShareX/2020/12/repo%202.rar
(If I'm being a smooth brain and doing it wrong let me know)

**Comment by LPGhatguy** [comment]
In order to stop Rojo from deleting a file contained in the `Tools` folder, you'll need to add an `init.meta.json` file to the `Tools` folder.

I downloaded your project, and it does not appear to have anything inside the `Tools` folder. Rojo will default to synchronizing what you have on the filesystem (nothing) with Studio, thus deleting anything you put inside the folder.

**Comment by RealExoctic** [comment]
Well then, sorry for wasting your time with this dumb issue report, I'll close it for now.
