### ISSUE TITLE
Rojo Erroring When Server Disconnected

### ISSUE THREAD

**Issue by ForcyDorcy** [rojo-rbx/rojo#380]
I am currently having this issue on Rojo 6.0.0 Release Candidate 4 synced with the VSC extension. This issue doesn't really affect anything, it just presents a rather annoying error notification.

After disconnecting from the server you initially connected to (in my case localhost), you are back at the main screen where you can insert an IP address and port. However, once you stop the connection through the VSC extension, it will present the following error, even though I should no longer be connected in the first place:

![image](https://user-images.githubusercontent.com/76664256/103447041-26643f80-4c54-11eb-880d-653717ac4aa7.png)

Again, minor issue. Just presents an annoying notification and I presume it would be a rather easy fix.

**Comment by boatbomber** [comment]
This issue no longer occurs, presumably fixed by #675.
