### ISSUE TITLE
Consider adding dependency management to Rojo

### ISSUE THREAD

**Issue by blake-mealey** [rojo-rbx/rojo#381]
I'm not sure if this is the best place for this discussion, but I'd like to propose some basic dependency management with rojo. I'm thinking something somewhat similar to Go's dependency management, where it is based on URLs.

With the development of rojo, I've noticed more and more high quality frameworks/libraries emerging in the ROBLOX community on GitHub (e.g. Nevermore, Knit, and Roact). However, the installation instructions always involve copying the source into my project. While this is _ok_, it would be ideal for me to not have to include the source of my dependencies in my repo.

Proposal:

Support a `$remote` property as an alternative to the `$path` property in the project file for mounting a folder in ROBLOX from a remote dependency. The `$remote` property will contain an object with the properties:

- url
- version

Then, when the rojo server starts, it will download all the provided dependencies into a cache folder (e.g. `.rojo-cache`) which should be excluded from source control by end-users. Once downloaded, rojo will mount the project files to ROBLOX the same way it would from a standard file path.

The tricky part would be processing the remote URLs (especially if they have remote dependencies themselves), and may require a rojo project file in the remote repo to be supported.

I could perhaps see an argument that this is outside of the scope of rojo, although in that case I think a sister-project which was integrated with rojo would be a good way forward. What are your thoughts?

**Comment by Kampfkarren** [comment]
This feels like something that would be better solved by a non-Rojo tool, such as [kayak](https://github.com/ElliottLMz/kayak), or git submodules.

**Comment by blake-mealey** [comment]
Sounds good, thanks for the link to kayak, I hadn't heard of it before!
