### ISSUE TITLE
Consider adding API for Lua pre-processors

### ISSUE THREAD

**Issue by blake-mealey** [rojo-rbx/rojo#382]
rojo sits in a perfect space for offering Lua pre-processing support as it's job is to copy Lua into the Roblox place file. I would love to see a generic pre-processing API built for rojo which other developers could then build plugins for. Having some 1st party plugins that ship with rojo could be great for the ecosystem as well.

Some pre-processing use cases:

- Obfuscation & comment removal
  - Makes code harder to read and therefore gives hackers a harder time
  - Reduces file size for replication
- Smart filesystem-based requires for ModuleScripts
  - Script files could import dependencies based on the source code file path without having to worry about where they get mounted to in ROBLOX
  - Local scripts would use :WaitForChild while server scripts would not
  - If a module would not be available (e.g. a server-only module required by a client script), it would throw an error

What are your thoughts?

**Comment by Kampfkarren** [comment]
This isn't something Rojo should provide, but instead be something users can produce with plugins.

**Comment by blake-mealey** [comment]
Ahh, I didn't realize there were Rojo plugins. Could you please point me to some docs?

**Comment by Kampfkarren** [comment]
There aren't, it's just a planned feature.

**Comment by blake-mealey** [comment]
Ahh I see. Is there currently any public planning for this? Is there any way I could contribute at the moment?
