### ISSUE TITLE
Support for Optional Tree Nodes

### ISSUE THREAD

**Issue by osyrisrblx** [rojo-rbx/rojo#383]
For [roblox-ts](https://www.roblox-ts.com), we'd like to have all of our npm packages provide Rojo `default.project.json` files. Unfortunately, there's a major issue blocking our support for this.

Here's an example `default.project.json` file for package:
```json
{
	"name": "my-package-name",
	"tree": {
		"$path": "out",
		"node_modules": {
			"$path": "node_modules/@rbxts"
		}
	}
}
```

The problem is that `node_modules` may not exist when this package is installed.
When a user installs the package, npm will flatten the dependencies so that every packages is under `/node_modules/*`. However, if any packages have conflicting versions of the same dependency, those packages will be given their own `node_modules` folder.

To solve this, we need some way or marking a Rojo tree node as "optional". Maybe as a `"$optional": true,` field?

**Comment by Quenty** [comment]
I very much need this to be fixed for my use of npm too. Right now, I'm solving this in CI/CD with a Python script, but this is not great.
