### ISSUE TITLE
unable to make init.lua without disconnecting

### ISSUE THREAD

**Issue by jakebball** [rojo-rbx/rojo#386]
I attempted to put an init.lua inside a folder of mine but for some reason once I added it I get this error and then rojo disconnects.
` [Rojo-Warn] Disconnected from an error: user_Rojo.rbxm.Rojo.Plugin.Reconciler:159: TODO: Support changing class name by destroying + recreating instance. (x3)`

**Comment by LPGhatguy** [comment]
What version of Rojo are you running? This was an issue in some of the release candidates for 6.0, but should be resolved in 6.0.0.

I attempted to reproduce your bug by adding/removing an `init.lua` file from a small project, but was not able to. The [version of Reconciler.lua that shipped in 6.0.0](https://github.com/rojo-rbx/rojo/blob/27af0c841bb5f14b889a4e8a386dfef4943fc475/plugin/src/Reconciler/init.lua) doesn't have that many lines of code, either! 😅

**Comment by jakebball** [comment]
I am using rojo v6.0.0.

**Comment by LPGhatguy** [comment]
Had a conversation on Discord. If we're able to reproduce this issue on 6.0.0 stable, we can reopen this issue and look more into the problem.
