### ISSUE TITLE
Add ChangeHistoryService:SetWaypoint when syncing

### ISSUE THREAD

**Issue by RuizuKun-Dev** [rojo-rbx/rojo#387]
Currently it is impossible to undo Rojo synced changes to Roblox.

Adding this feature would be useful for when people make mistakes especially new users to Rojo.

**Comment by LPGhatguy** [comment]
Thanks for the suggestion!

I don't know if it's semantically correct for Rojo to add ChangeHistoryService waypoints. I'd instead like to encourage users to save their places regularly and use version control systems.

We can revisit this in the future if my understanding here is wrong or there's a strong case for adding these waypoints.
