### ISSUE TITLE
[FEATURE REQUEST] Load Default Configuration

### ISSUE THREAD

**Issue by yaelvalle** [rojo-rbx/rojo#388]
The ability to load a configuration and a series of folders will be auto generated to save time when initializing a project

**Comment by LPGhatguy** [comment]
This is actually already supported by Rojo, try out the `rojo init` command!

As of Rojo 6.0.0, it will create a reasonable default project for you and even initialize a Git repository:
![Default Rojo place project from DOOM Emacs](https://user-images.githubusercontent.com/654598/105548942-8717f280-5cbd-11eb-9046-1a133797fa6c.png)
