### ISSUE TITLE
Not working on macOS

### ISSUE THREAD

**Issue by shabman** [rojo-rbx/rojo#390]
this doesn't work on macOS I can't unzip it and I get weird errors in VSC when trying to start a server. also I get zsh command not found: Rojo...

rojo is broken plz fix

**Comment by LPGhatguy** [comment]
Hello. There's a lot going on in this issue, and I don't think any of these things are bugs with Rojo.

If you're looking for support, I recommend heading to the [Discord server linked in the Rojo documentation](https://rojo.space/docs/help). The folks there will likely need more information to help you than what you've given here.
