### ISSUE TITLE
Upload.ashx requires token.

### ISSUE THREAD

**Issue by Brantone** [rojo-rbx/rojo#393]
I suspect this update: https://github.com/rojo-rbx/rojo/commit/804fd3de8e32c87e0c8a73d5db70360ae216a11b#diff-917af2b8814a2f6f244ac8f95d5bff60643c42da55258e0c7512b4e41e9f1482 was to compensate for issue encountered last week?

**Comment by LPGhatguy** [comment]
What kind of token does this endpoint require? It seems like uploading is fixed again after a bit of experimentation that resulted in that patch.

It seems like the long-term solution is to migrate to one of the newer APIs. I wasn't able to get place and model publishing working with them last time I tried, but maybe it's worth revisiting.

**Comment by Brantone** [comment]
He upload.ashx endpoint requires CSRF token.

**Comment by Brantone** [comment]
Never mind : https://github.com/rojo-rbx/rojo/commit/0e89b91c38e71f49004e801abb3bf310582c3b37#diff-917af2b8814a2f6f244ac8f95d5bff60643c42da55258e0c7512b4e41e9f1482
