### ISSUE TITLE
rojo serve crash "Unkown binary chunk name SSTR"

### ISSUE THREAD

**Issue by MaxBorsch** [rojo-rbx/rojo#396]
![powershell_gmv7r3G8Ge](https://user-images.githubusercontent.com/2924585/107912847-1f4b7500-6f14-11eb-8652-357127b58ac8.png)

This project worked with the v5 rojo, but it auto-updated to v6 and now this happens when I rojo serve.

**Comment by LPGhatguy** [comment]
This is on track to be fixed for good in #377. For now, I'd recommend downgrading to Rojo 0.5.4. That's easy to do with the VS Code extension or any of the other installation methods with Rojo.
