### ISSUE TITLE
$path referred to a path that could not be turned into an instance by Rojo.

### ISSUE THREAD

**Issue by DeveloperCron** [rojo-rbx/rojo#397]
My friend gets this error over and over. We’ve tried to reinstall rojo and nothing worked, moreover he’s attempting to use Rojo 6.0. His JSon file seems good and there are no errors in his Json file. 

Error: 

![unknown](https://user-images.githubusercontent.com/79309515/108490257-363eee00-72ab-11eb-82ff-269d8d93fd26.png)

**Comment by OverHash** [comment]
Something in his project JSON file doesn't specify a `$className` or `$path`.

Could you upload the JSON project?

**Comment by DeveloperCron** [comment]
> Something in his project JSON file doesn't specify a `$className` or `$path`.
> 
> Could you upload the JSON project?

**Comment by DeveloperCron** [comment]
"name": "DefaultRojoProject",
  "servePlaceIds": [ID],
  "tree": {
    "$className": "DataModel",
    "HttpService": {
      "$className": "HttpService",
      "$properties": {
        "HttpEnabled": true
      }
    },
    "Lighting": {
      "$className": "Lighting",
      "$ignoreUnknownInstances": true
    },
    "ReplicatedStorage": {
      "$className": "ReplicatedStorage",
      "$ignoreUnknownInstances": true,
      "$path": "ReplicatedStorage"
    },
    "StarterGui": {
      "$className": "StarterGui",
      "$ignoreUnknownInstances": true,
      "$path": "StarterGui"
    },
    "ServerScriptService": {
      "$className": "ServerScriptService",
      "$ignoreUnknownInstances": true,
      "$path": "ServerScriptService"
    },
    "StarterPack": {
      "$className": "StarterPack",
      "$ignoreUnknownInstances": true,
      "$path": "StarterPack"
    },
"StarterPlayer": {
      "$className": "StarterPlayer",
      "$ignoreUnknownInstances": true,
      "$path": "StarterPlayer",
      "StarterPlayerScripts": {
        "$className": "StarterPlayerScripts",
        "$ignoreUnknownInstances": true,
        "$path": "StarterPlayerScripts"
      },
      "StarterCharacterScripts": {
        "$className": "StarterCharacterScripts",
        "$ignoreUnknownInstances": true,
        "$path": "StarterCharacterScripts"
      }
    },
    "ReplicatedFirst": {
      "$className": "ReplicatedFirst",
      "$ignoreUnknownInstances": true,
      "$path": "ReplicatedFirst"
    },
    "ServerStorage": {
      "$className": "ServerStorage",
      "$ignoreUnknownInstances": true,
      "$path": "ServerStorage"
    },
    "SoundService": {
      "$className": "SoundService",
      "$ignoreUnknownInstances": true,
      "$properties": {
        "RespectFilteringEnabled": true
      }
    },
    "Workspace": {
      "$className": "Workspace",
      "$ignoreUnknownInstances": true,
      "$properties": {
        "FilteringEnabled": true
      }
    }
  }
}

**Comment by DeveloperCron** [comment]
`"name": "DefaultRojoProject",
  "servePlaceIds": [6219745799],
  "tree": {
    "$className": "DataModel",
    "HttpService": {
      "$className": "HttpService",
      "$properties": {
        "HttpEnabled": true
      }
    },
    "Lighting": {
      "$className": "Lighting",
      "$ignoreUnknownInstances": true
    },
    "ReplicatedStorage": {
      "$className": "ReplicatedStorage",
      "$ignoreUnknownInstances": true,
      "$path": "ReplicatedStorage"
    },
    "StarterGui": {
      "$className": "StarterGui",
      "$ignoreUnknownInstances": true,
      "$path": "StarterGui"
    },
    "ServerScriptService": {
      "$className": "ServerScriptService",
      "$ignoreUnknownInstances": true,
      "$path": "ServerScriptService"
    },
    "StarterPack": {
      "$className": "StarterPack",
      "$ignoreUnknownInstances": true,
      "$path": "StarterPack"
    },
"StarterPlayer": {
      "$className": "StarterPlayer",
      "$ignoreUnknownInstances": true,
      "$path": "StarterPlayer",
      "StarterPlayerScripts": {
        "$className": "StarterPlayerScripts",
        "$ignoreUnknownInstances": true,
        "$path": "StarterPlayerScripts"
      },
      "StarterCharacterScripts": {
        "$className": "StarterCharacterScripts",
        "$ignoreUnknownInstances": true,
        "$path": "StarterCharacterScripts"
      }
    },
    "ReplicatedFirst": {
      "$className": "ReplicatedFirst",
      "$ignoreUnknownInstances": true,
      "$path": "ReplicatedFirst"
    },
    "ServerStorage": {
      "$className": "ServerStorage",
      "$ignoreUnknownInstances": true,
      "$path": "ServerStorage"
    },
    "SoundService": {
      "$className": "SoundService",
      "$ignoreUnknownInstances": true,
      "$properties": {
        "RespectFilteringEnabled": true
      }
    },
    "Workspace": {
      "$className": "Workspace",
      "$ignoreUnknownInstances": true,
      "$properties": {
        "FilteringEnabled": true
      }
    }
  }
}`

**Comment by DeveloperCron** [comment]
[Code.txt](https://github.com/rojo-rbx/rojo/files/6014096/Code.txt)

**Comment by EYYCHEEV** [comment]
I have encountered the same problem.
My `default.project.json` works fine with Rojo@0.5.x.
After grading to Rojo@6.0.2, `rojo serve` showed the same error message.
<img width="933" alt="Screen Shot 2021-03-26 at 3 00 15 AM" src="https://user-images.githubusercontent.com/24510019/112615229-73812900-8ddf-11eb-83d2-621083d42644.png">

The content in `default.project.json` :
```json
{
  "name": "Game01",
  "tree": {
    "$className": "DataModel",
    "HttpService": {
      "$className": "HttpService",
      "$properties": {
        "HttpEnabled": true
      }
    },
    "SoundService": {
      "$className": "SoundService",
      "$properties": {
        "RespectFilteringEnabled": true
      }
    },
    "Workspace": {
      "$className": "Workspace",
      "$properties": {
        "FilteringEnabled": true
      }
    },
    "ReplicatedFirst": {
      "$className": "ReplicatedFirst",
      "$path": "src/ReplicatedFirst"
    },
    "ReplicatedStorage": {
      "$className": "ReplicatedStorage",
      "Resources": {
        "$path": "src/RoStrap/Resources.lua"
      },
      "Tests": {
        "$path": "src/Tests/Client"
      },
      "Temp": {
        "$path": "src/Temp"
      }
    },
    "ServerScriptService": {
      "$className": "ServerScriptService",
      "$path": "src/ServerScriptService"
    },
    "ServerStorage": {
      "$className": "ServerStorage",
      "Repository": {
        "$className": "Folder",
        "RoStrap": {
          "$path": "src/RoStrap/Packages"
        },
        "Modules": {
          "$className": "Folder",
          "Promise": {
            "$path": "submodules/Promise/lib/init.lua"
          },
          "Roact": {
            "$path": "submodules/Roact/src"
          },
          "Rodux": {
            "$path": "submodules/Rodux/lib"
          },
          "RoactRodux": {
            "$path": "submodules/Roact-Rodux/src"
          },
          "TestEZ": {
            "$path": "submodules/TestEZ/src"
          }
        },
        "EPM": {
          "$path": "src/EPM"
        },
        "Eyyce": {
          "$path": "src/Eyyce"
        }
      },
      "Tests": {
        "$path": "src/Tests/Server"
      }
    },
    "StarterPlayer": {
      "$className": "StarterPlayer",
      "StarterPlayerScripts": {
        "$className": "StarterPlayerScripts",
        "$path": "src/StarterPlayer/StarterPlayerScripts"
      }
    }
  }
}
```

**Comment by EYYCHEEV** [comment]
> I have encountered the same problem.
> My `default.project.json` works fine with [Rojo@0.5.x](mailto:Rojo@0.5.x).
> After grading to Rojo@6.0.2, `rojo serve` showed the same error message.
> <img alt="Screen Shot 2021-03-26 at 3 00 15 AM" width="933" src="https://user-images.githubusercontent.com/24510019/112615229-73812900-8ddf-11eb-83d2-621083d42644.png">
> 
> The content in `default.project.json` :
> 
> ```json
> {
>   "name": "Game01",
>   "tree": {
>     "$className": "DataModel",
>     "HttpService": {
>       "$className": "HttpService",
>       "$properties": {
>         "HttpEnabled": true
>       }
>     },
>     "SoundService": {
>       "$className": "SoundService",
>       "$properties": {
>         "RespectFilteringEnabled": true
>       }
>     },
>     "Workspace": {
>       "$className": "Workspace",
>       "$properties": {
>         "FilteringEnabled": true
>       }
>     },
>     "ReplicatedFirst": {
>       "$className": "ReplicatedFirst",
>       "$path": "src/ReplicatedFirst"
>     },
>     "ReplicatedStorage": {
>       "$className": "ReplicatedStorage",
>       "Resources": {
>         "$path": "src/RoStrap/Resources.lua"
>       },
>       "Tests": {
>         "$path": "src/Tests/Client"
>       },
>       "Temp": {
>         "$path": "src/Temp"
>       }
>     },
>     "ServerScriptService": {
>       "$className": "ServerScriptService",
>       "$path": "src/ServerScriptService"
>     },
>     "ServerStorage": {
>       "$className": "ServerStorage",
>       "Repository": {
>         "$className": "Folder",
>         "RoStrap": {
>           "$path": "src/RoStrap/Packages"
>         },
>         "Modules": {
>           "$className": "Folder",
>           "Promise": {
>             "$path": "submodules/Promise/lib/init.lua"
>           },
>           "Roact": {
>             "$path": "submodules/Roact/src"
>           },
>           "Rodux": {
>             "$path": "submodules/Rodux/lib"
>           },
>           "RoactRodux": {
>             "$path": "submodules/Roact-Rodux/src"
>           },
>           "TestEZ": {
>             "$path": "submodules/TestEZ/src"
>           }
>         },
>         "EPM": {
>           "$path": "src/EPM"
>         },
>         "Eyyce": {
>           "$path": "src/Eyyce"
>         }
>       },
>       "Tests": {
>         "$path": "src/Tests/Server"
>       }
>     },
>     "StarterPlayer": {
>       "$className": "StarterPlayer",
>       "StarterPlayerScripts": {
>         "$className": "StarterPlayerScripts",
>         "$path": "src/StarterPlayer/StarterPlayerScripts"
>       }
>     }
>   }
> }
> ```

I found the Problem:
```json
          "Promise": {
            "$path": "submodules/Promise/lib/init.lua"
          },
```

It should be:
```json
          "Promise": {
            "$path": "submodules/Promise/lib"
          },
```

**Comment by EYYCHEEV** [comment]
I found the Problem:
```json
          "Promise": {
            "$path": "submodules/Promise/lib/init.lua"
          },
```

It should be:
```json
          "Promise": {
            "$path": "submodules/Promise/lib"
          },
```
