### ISSUE TITLE
Cannot GET /api/rojo</pre> Error

### ISSUE THREAD

**Issue by Rudy-Dev** [rojo-rbx/rojo#399]
After update I can't use Rojo anymore, it breaking and give me error: 
```
 [Rojo-Warn] Disconnected from an error: HTTP 404:
[Rojo-Warn] <!DOCTYPE html>
[Rojo-Warn] <html lang="en">
[Rojo-Warn] <head>
[Rojo-Warn] <meta charset="utf-8">
[Rojo-Warn] <title>Error</title>
[Rojo-Warn] </head>
[Rojo-Warn] <body>
[Rojo-Warn] <pre>Cannot GET /api/rojo</pre>
[Rojo-Warn] </body>
[Rojo-Warn] </html>
[Rojo-Warn] 
```
I tried version 6 and 7 still no effects, 
After I reinstalled Rojo, Visual studio code, and Roblox studio it was working for like 2 minutes after that same error showed.

**Comment by LPGhatguy** [comment]
This error occurs if there is another web server (like a very old version of Rojo!) running on the port that the Rojo Studio plugin is expecting to find the Rojo server.

There's not a whole lot Rojo can do here — make sure there aren't any old versions of Rojo running, and ensure that your Rojo plugin and server versions match.
