### ISSUE TITLE
Allow specifying default script type in instances

### ISSUE THREAD

**Issue by vladmarica** [rojo-rbx/rojo#405]
A feature that would be useful would be a meta property `$defaultScriptType` that would set the script type for all *.lua files in the subtree that do not begin with `*.server.lua` or `*.client.lua`.

Accepted values for this property would be:
- `"server"` or `"script"`
- `"client"` or `"localscript"`
- `"module"` or `"modulescript"`

 The default value of this property could be `"module"`, so to not break the default behaviour. 

Example:

```json
{
  "name": "rojo-test",
  "tree": {
    "$className": "DataModel",
    "ServerScriptService": {
      "$className": "ServerScriptService",
      "$path": "src/ServerScriptService",
      "$defaultScriptType": "server"
    }
}
```

Now, all `*.lua` files under ServerScriptService would be turned into Script instances instead of ModuleScript instances. To create a ModuleScript, you would have to name the files `*.mod.lua` or `*.module.lua`.

**Comment by Kampfkarren** [comment]
I don't see any good benefit to this, it just makes it harder to understand when looking at other codebases.

**Comment by LPGhatguy** [comment]
It's strongly recommended that your codebase consists mostly of `ModuleScript` instances. Additionally, uniformity across Rojo projects is important!

As such, we will not be pursuing this feature.
