### ISSUE TITLE
Syncing markdown files (.md) into Roblox Studio? 

### ISSUE THREAD

**Issue by rfrey-rbx** [rojo-rbx/rojo#406]
Currently, I'm naming markdown files in my git project as `example.md.txt` in order to get Rojo to sync them into Studio as `StringValue` objects. This works pretty well, however, without the correct file extension the markdown files loose formatting in editor and on in Github browsing.

What I'd like to do is tell Rojo to treat files with markdown extension `.md` the same as `.txt` files.

**Comment by LPGhatguy** [comment]
This is kind of a recurring problem! In older versions of Rojo, all files with unknown extensions were turned into `StringValue` objects by Rojo. Starting in Rojo 0.5, we started ignoring unknown files instead, and only `txt` files started turning into `StringValue` objects.

This seems like something that would be best solved with Rojo plugins, but I've been saying that for literally years at this point. We still don't have a plugin API that's fully designed, let alone shipped.

At the same time, I'm weary of adding other file extensions that work the same way as `txt`. We had a similar feature request in #148, but for JSON files. I don't think we would ever want to sync `md` files as anything _except_ `StringValue`, but I wonder what other file extensions should behave this way.

**Comment by kennethloeffler** [comment]
This is closed by #813, which will be available in Rojo 7.5.
