### ISSUE TITLE
Support assets via rbxasset loopholes

### ISSUE THREAD

**Issue by LPGhatguy** [rojo-rbx/rojo#41]
Way back when, it used to be possible to specify files on-disk for textures, sounds, etc.

It'd be cool to support using hacks like that to manage assets from within Rojo!

**Comment by Kampfkarren** [comment]
Using Roblox Studio Mod Manager (it has a consistent file directory, unlike Studio which changes every update), you can make your own custom folder inside its directory to solve this issue for now.

**Comment by LPGhatguy** [comment]
We can also make `rojo upload` automatically publish your assets for you if they change, and maybe keep a lockfile on-disk that describes how files map to assets that have been uploaded so far.

**Comment by LPGhatguy** [comment]
This might be out of scope for Rojo. I ended up starting a new project called [Tarmac](https://github.com/rojo-rbx/tarmac) that seems like it could fill this roll and interoperate with Rojo.

**Comment by LPGhatguy** [comment]
Closing in favor of planning to push people to use Tarmac.
