### ISSUE TITLE
MeshIds of MeshParts inside Model do not load properly

### ISSUE THREAD

**Issue by B-Ricey763** [rojo-rbx/rojo#410]
I had a `.rbxmx` model file exported from roblox that I want to inlcude into a `default.project.json` file. The xml looks perfectly fine, with the MeshIds all set properly, but when I sync it into roblox, the MeshIds are not replicated. I also tried using remodel to generate the `.rbxmx` file but that got the same result. However, when I manually went into studio and imported the model, it worked perfectly fine, leading me to believe that this is a rojo issue. Here is the model link if you want to download it and try it yourself: https://www.roblox.com/library/6596908493/Typhoon-Sub-Decor

Here is an image of the xml, and it looks fine
![image](https://user-images.githubusercontent.com/39998963/113319937-f9213f00-92df-11eb-8836-27a13734e205.png)

But in studio, it looks like this:
![image](https://user-images.githubusercontent.com/39998963/113320132-2968dd80-92e0-11eb-8215-0e9a3dab05d3.png)

**Comment by IanTimchak** [comment]
Did you ever find a solution? I am currently running in to the exact same problem

**Comment by Kampfkarren** [comment]
Roblox doesn't allow syncing of mesh parts easily. What you can do, however, is ensure the meshes already exists (such as with rojo build), then sync on top of that. If the meshes already exist, Rojo won't try to override them.

**Comment by ZachCurtis** [comment]
Recently moved art assets out with Remodel and I've been running into this a lot. I've been using [CreateMeshPartAsync](https://developer.roblox.com/en-us/api-reference/function/InsertService/CreateMeshPartAsync) as a hacky workaround for now. 

It wouldn't be very elegant but the plugin could call that method to construct a new MeshPart when a MeshId needs updating, possibly as a `customProperty`?

**Comment by LPGhatguy** [comment]
It's very difficult to integrate into Rojo because the method is asynchronous. Other stuff can happen to your project while we're waiting for the meshpart to me made!

I recommend making the jump to fully-managed Rojo or just dragging model files back into your place in Roblox Studio. Both of these should be a lot simpler than trying to use `CreateMeshPartAsync`.
