### ISSUE TITLE
Type: Enhancement | A way to add team create to rojo 

### ISSUE THREAD

**Issue by CertifiedRice** [rojo-rbx/rojo#411]
I think it would get a good idea to add team create to Rojo. Some people(including me) use TypeScript for most of the game's scripts and would be useful if team create was a thing in Rojo.

**Comment by Kampfkarren** [comment]
This feature request doesn't really make sense, especially with a one-way transaction like roblox-ts.

Sounds like you'd be better off with just VS Code Live Share?

**Comment by sasial-dev** [comment]
VSLS is what you'd use? That's exactly what it's designed for.

**Comment by CertifiedRice** [comment]
I mainly use Jetbrains Intellij or PyCharm

**Comment by Kampfkarren** [comment]
This still doesn't sound like something that Rojo needs to be bothering with, there's dedicated tools that do this.

**Comment by LPGhatguy** [comment]
This feature is too under-specified for us to take action. Additionally, we don't really try to support integrating with Team Create directly as Rojo and Team Create are generally incompatible styles of working. Once we have two-way sync (#164), this case will get better, but still not recommended.

If there are specific ways that Rojo can be improved for workflows like these, feel free to open a new issue.
