### ISSUE TITLE
Only validate .model.json files after content has been added

### ISSUE THREAD

**Issue by vocksel** [rojo-rbx/rojo#415]
When you create a new .model.json file Rojo immediately throws an error. This has been a longstanding cause for annoyance for me because when using the VS Code plugin it pops up an output window simply for creating a file.

It would be great if when a new .model.json file is added, Rojo only validates the contents once there's actually something in the file.

Relevant error:

```
[ERROR] Snapshot error: File is not a valid JSON model: c:\[...]/foo.model.json
        
        Caused by:
            EOF while parsing a value at line 1 column 0
[ERROR] Snapshot error: File is not a valid JSON model: c:\[...]/foo.model.json
        
        Caused by:
            EOF while parsing a value at line 1 column 0
```

Edit: This happens in Rojo v6.1.0, managed by the VS Code plugin.

**Comment by LPGhatguy** [comment]
We should be able to fix this by just ignoring files that are empty or are only whitespace.
