### ISSUE TITLE
[ERROR] Details: called `Option::unwrap()` on a `None` value

### ISSUE THREAD

**Issue by deter0** [rojo-rbx/rojo#416]
![image](https://user-images.githubusercontent.com/82973108/115620117-c2c55700-a2c2-11eb-8cf5-40f07a93f6e3.png)

**Comment by LPGhatguy** [comment]
Looks like a race condition in our message handling code. When we receive a message that we're going to send to the plugin, we assume that all the referents listed in it are still valid. That's not necessarily the case!

**Comment by LewisTehMinerz** [comment]
Just experienced this myself out of the blue, although I got this to go along with it:
`[ERROR] accept error: Either the application has not called WSAStartup, or WSAStartup failed. (os error 10093)`
Not sure if it's related but I'll add it just in case.

**Comment by Dekkonot** [comment]
If anyone experiences this issue in the future, please open a new one so that we can track it better.
