### ISSUE TITLE
Two bugs — `Requested module was required recursively` & idk bug

### ISSUE THREAD

**Issue by deter0** [rojo-rbx/rojo#417]
I don't know the exact cause for this error, I don't know if this is on my end or not but I opened a new project with `Rojo: Init` and `Rojo: Start` and got the same thing. The Roblox plugin's version is 6.1.0 and the VS Code plugin is 1.13.1. I've tried reinstalling the extension multiple times but it doesn't change anything, I've also made like 4 new projects and keep getting the same thing also with the default project rojo injects into `src` on initializing causes a weird bug where the `init.client.lua` & `init.server.lua` both aren't parented to a folder but just standalone scripts in ServerScriptService and StarterPlayer/Client; this can be fixed to renaming the files to something like "start.client.lua"

![image](https://user-images.githubusercontent.com/82973108/115629275-125e4f80-a2d0-11eb-90b3-70c211b3f2e5.png)

**Comment by Mixu78** [comment]
The recursive module requiring seems to be caused by a plugin you have.

Like [the docs](https://rojo.space/docs/6.x/sync-details/#scripts) say, if you name a script init.server.lua, init.client.lua or init.lua it will change its parent directory to a script when synced in.
