### ISSUE TITLE
Rojo Plugin should offer real-time status about sync details

### ISSUE THREAD

**Issue by BetterThanReal** [rojo-rbx/rojo#418]
It's not terribly uncommon for developers to assume that Rojo is running, connected, and working properly, even when it's not.  A great example is when resuming Roblox Studio usage after the computer has been asleep for awhile - Rojo sometimes silently fails to sync, and the user continues to develop as though their latest changes are being synced to Studio.

I personally have lost a cumulative total of at least one hour troubleshooting my code with the assumption that Rojo was syncing properly, when it wasn't.

An easy way to help Rojo be more communicative about the state of the plugin is if the plugin reports, in real-time, the status of the latest file sync that resulted in changed files.

Suggested plugin status would read something like "5 files changed 32 seconds ago", where "32 seconds" would be a counter that updates once per second until at least one minute has passed, at which point the text would change to "5 files changed 1 minute ago", and again changing when the hour and day thresholds have been exceeded.

**Comment by OverHash** [comment]
I think updating once per second would be a bit excessive and distracting. Maybe something like "A few seconds ago..." for <1m, and then you can increment once per minute after that? (Or maybe even less than once per minute).

Alternatively, maybe you could bind to window changes and refresh then? Not sure if that's possible with API exposed to plugins.

**Comment by BetterThanReal** [comment]
> I think updating once per second would be a bit excessive and distracting.

The goal of updating once per second (during the first minute only) is to prevent circumstances where the developer makes a change, comes back to Studio to test, makes a change, comes back to Studio to test, and effectively wastes a minute of their time because Rojo is not syncing.

When I'm troubleshooting, sometimes it's not uncommon for me to make and test five changes per minute.  While I agree that wasting a whole minute is trivial compared to wasting an hour, it's still something I'd like to avoid.

FWIW, the Roblox Studio Diagnostics Bar shows updates 4 or 5 times per second, and that doesn't distract me at all.
