### ISSUE TITLE
Malformed $path value error message should be more clear

### ISSUE THREAD

**Issue by NobleDraconian** [rojo-rbx/rojo#419]
Currently, as of  `6.1.0`, if a `*.project.json` file has a `$path` declaration that refers to a non-existent file, this error message is spit:

![image](https://user-images.githubusercontent.com/26460940/116454265-cb231200-a82d-11eb-8352-b0dd7a35094f.png)

The error message should state at which line in the JSON file it errored, to make it more obvious what the problematic line is. Currently, the developer has to read through the entirety of the JSON file, potentially spending in excess of 10 minutes trying to find the problem before being able to fix it.

**Comment by LPGhatguy** [comment]
The error listed here is not from `$path` pointing to the wrong place, it's from `$path` not being specified at all. We have a different error for when the `$path` is pointing to as of Rojo 7 that's much more clear.

That said, this error is fixed on the master branch.

**Comment by NobleDraconian** [comment]
> The error listed here is not from `$path` pointing to the wrong place, it's from `$path` not being specified at all. We have a different error for when the `$path` is pointing to as of Rojo 7 that's much more clear.
> 
> That said, this error is fixed on the master branch.

The issue wasn't confusion between path not being specified at all vs. pointing to bad instance, the confusion was because it didn't tell you what line in the JSON file the problem was occurring on.
