### ISSUE TITLE
rojo upload doesn't appear to work

### ISSUE THREAD

**Issue by pracplayopen** [rojo-rbx/rojo#425]
hello thanks for your rojo contribution.

am able to use rojo (v6 and v7) using rojo sync/serve.  thx

unable to get 'rojo upload' working, even though per your docs it's much simpler than sync.

attempted this using a project with one asset and one script.   always get error:

```
[ERROR] The Roblox API returned an unexpected error:
Bad Request
400 |There was a problem with your request
```

Since all that's being done is provide two roblox-supplied parameters via two args to 'roblox upload', this has to be rojo upload simply not working.    I've verified asset id and security cookie.  Tried many different interpretations of your docs, always get this error.

Then I looked at your source here: https://github.com/rojo-rbx/rojo/blob/c7ab6c435c3b66b7fa857ebb5553f262f9fbbe01/src/cli/upload.rs

I noticed you're using this url to upload:

```
let url = format!(        "https://data.roblox.com/Data/Upload.ashx?assetid={}",        asset_id    );
```

I tried to locate the roblox api docs and these show this being the correct asset upload url: https://publish.roblox.com/docs#!/Items/post_v1_assets_upload

When I rebuild rojo using this url, I get:

```
[ERROR] The Roblox API returned an unexpected error: {"errors":[{"code":0,"message":"The requested resource does not support http method 'POST'."}]}
```

Which is odd because the docs clearly show post as supported.

Will continue to look and post PR if fixing.

Also if something else is wrong please advise.

thx for sync.

**Comment by LPGhatguy** [comment]
Thanks for the report!

This API is very temperamental. There are a few common issues:
1. The cookie has been invalidated. This can happen if you pressed "Log Out" on the website or if the cookie expired after ~6 months.
2. You are publishing to a universe/game/experience instead of a place. It's important to use the place ID.
3. You're using the wrong account. This happens a lot to me when I switch between accounts in Studio.

I recommend not specifying the upload cookie yourself if possible. On Windows, `rojo upload` can find your cookie from Roblox Studio for you.

**Comment by pracplayopen** [comment]
thanks for follow up.

yes, based on the way they've implemented the login token... it's pretty clear api is a work in progress. :)

that said i'm certain i'm using right place id.

i was able to patch the upload command slightly so it outputs the status code of the error, which was helpful to fix one issue.
(previously it was spitting out response.text, which is basically a ton of useless javascript/css and no actual error code).

i then ran it with tracing enabled and now i'm getting status code 400, bad request.  it does appear to be logging in tho- based on trace and source.  i get status code 403 in the trace, then it hits the part of code that deals with X-CSRF-Token...

At this point it's building a token and sending request but getting bad request.

I will push this as a PR, and also push a PR to update the upload docs.

I'm still not sure what is causing this issue.  I'm presently running on ubuntu using grapejuice's wine config (grapejuice is a very well-maintained and updated tool to run roblox studio on linux).

I will try and see if I can run rojo on a windows machine later today and see if I learn anything else.

I'm happy to help improve project and do both code and doc PRs, so any little bit of extra info you can provide would be very helpful.

**Comment by pracplayopen** [comment]
uploaded a pull request for clearer upload logging:  https://github.com/rojo-rbx/rojo/pull/431

it's a pretty minor change so would be great if you could approve.

will do docs next, and report back on this issue when look at it next.

**Comment by pracplayopen** [comment]
update:got a quick PR review on mentioned debugging-only improvement... response speed was positive  cc: @Kampfkarren.  

no approval tho so holding off comment otherwise.

regarding 'rojo upload' issues here... to continue to isolate root cause, was able to confirm:

 * even tho it's 10+ years old since update, [this rojo guide is still the most accurate, comprehensive and useful resource relative to any other bit of code or website](https://devforum.roblox.com/t/accessing-the-roblox-api-the-comprehensive-tutorial/1161932)
 * based on roblox guide, was able to:
    * get info from any public endpoint
    * login and retrieve information from authenication-required endpoints, using same place and security token that is failing for rojo examples mentioned here

This elimates the place id and roblox security token from being the problem in the request.

On this side only a few people to spend small bits of time on rojo, but will continue to try to isolate it down to whatever the discrepency/confusion/mismatched assumption is for rojo vs public api examples.    Any assistance or tips appreciated.

Based on what works in rojo for us and what works using only public apis, it seems to be likely to be some slight difference in fields in the request or upload url.    While rust and python aren't that different in terms of expertise here, if we can make something in python that works will probably post that before doing the rust fix.  Mostly because the former would encourage more people to contribute, esp if there are more rosetta stones (which roblox desperately needs).

hopefully can update again in few days.  if got something wrong or something else that could benefit making this as solid as 'rojo sync', would appreciate any info no matter how easily communicated.

thx

**Comment by LPGhatguy** [comment]
I don't think `rojo upload` is broken. Lots of projects use it successfully, here is one that I loosely maintain that used it around a week ago to successfully upload a place: https://github.com/rojo-rbx/desert-bus-2077

I agree that we should improve our reporting where we can, but we just don't get any information back from Roblox to report.

**Comment by pracplayopen** [comment]
based on procedure including your comments above, it does not work per your instructions.

i guess you're arguing that maybe sometimes it doesn't work (it's never worked even when we use it on a brand new place, and even when we can use the api w/same two bits of information- placeid and security code- outside of rojo).

anyways based on the response to this and the two PRs, rojo doesn't seem like a professional-level tool.   not saying it's your fault- if roblox doesn't provide high quality interfaces that is good feedback too).

closing this issue for obvious reasons. thanks for your efforts.
