### ISSUE TITLE
Rojo Connecting doesn't work.

### ISSUE THREAD

**Issue by Bulldo344** [rojo-rbx/rojo#428]
Whenever I launch Rojo, and try to connect it; it says this error;

![image](https://user-images.githubusercontent.com/53837083/121200436-ba5cb780-c841-11eb-9a4a-1579002120a4.png)

**Comment by LPGhatguy** [comment]
Hello, thanks for filing an issue.

This is a duplicate of #400. It's a user configuration issue that has a better error message starting in Rojo 7.
