### ISSUE TITLE
HumanoidDescription properties 'Pants' and 'Shirt' are often synced incorrectly

### ISSUE THREAD

**Issue by 1ForeverHD** [rojo-rbx/rojo#429]
Hi, when syncing HumanoidDescriptions with 6.0.0, the Shirt and Pants values will often sync incorrect number values, demonstrated here:
https://giant.gfycat.com/DismalWelcomeGalapagostortoise.mp4

For instance, after becoming a rbxmx file and then synced back into studio:
- A Pants value of ``6689349892`` becomes ``-1900584700``
- A Shirt value of ``6689453618`` becomes ``-1900480974``
- A Pants value of ``158324370`` stays the same
- A Shirt value of ``5976655115`` becomes ``1681687819``

The same issue occurs when publishing an asset via continuous integration and using Rojo 6.0.2.

Any fix/solution to solving this will be greatly appreciated! HumanoidDescriptions are a necessary part of our project, and we can't go partially-managed either as everything is published to an asset (i.e. a MainModule for an admin commands system).

**Comment by magnalite** [comment]
This seems to affect any int64 property. They seem to get treated as 32 bit integers. For xml files an overflown number is written to the place. For binary files the value seems to be replaced by 0. 

Attached is a min repro project which attempts to sync an IntValue with the value 2147483648. 
[rojo-bug.zip](https://github.com/rojo-rbx/rojo/files/6626031/rojo-bug.zip)

**Comment by kennethloeffler** [comment]
This is a problem in rbx-dom's reflection generation code - `Int64` types are incorrectly reflected as `Int32`. This issue should probably be moved and triaged there.

**Comment by LPGhatguy** [comment]
Let's keep this issue here but open a companion issue in rbx-dom. We should backport a fix for old rbx_reflection and release a Rojo 6.2.0 with a fix!

**Comment by LPGhatguy** [comment]
Should be fixed in 6.2.0!

**Comment by 1ForeverHD** [comment]
Works great now, thanks very much for the quick response (and loving the 6.2 UI)!

![image](https://user-images.githubusercontent.com/51117782/121473533-bacc8e00-c9ba-11eb-8275-fd47e368294c.png)

One minor thing: when syncing in a HumanoidDescription for the first time, the following warning appears:

![image](https://user-images.githubusercontent.com/51117782/121473663-eb142c80-c9ba-11eb-8e2a-e6012bdcf6d9.png)

**Comment by LPGhatguy** [comment]
I think we could push another update to 6.x to fix the `SourceAssetId` issue. I'm not sure we will; it doesn't really impact anything. It should be covered in 7.0 which is around the corner :D

**Comment by 1ForeverHD** [comment]
Okay awesome, look forwards to it!
