### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by GrandMasterPaint** [rojo-rbx/rojo#432]
[WARN ] $path referred to a path that could not be turned into an instance by Rojo
[ERROR] Rojo crashed!
[ERROR] This is probably a Rojo bug.
[ERROR] 
[ERROR] Please consider filing an issue: https://github.com/rojo-rbx/rojo/issues
[ERROR] 
[ERROR] Details: $className or $path must be specified
[ERROR] in file src\snapshot_middleware\project.rs on line 159
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
[WARN ] $path referred to a path that could not be turned into an instance by Rojo
[ERROR] Rojo crashed!
[ERROR] This is probably a Rojo bug.
[ERROR] 
[ERROR] Please consider filing an issue: https://github.com/rojo-rbx/rojo/issues
[ERROR] 
[ERROR] Details: $className or $path must be specified
[ERROR] in file src\snapshot_middleware\project.rs on line 159
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

**Comment by LPGhatguy** [comment]
Hello, thank you for the issue!

This is a known problem; our error messages have gotten much better in Rojo 7.0.

See #397 and #423 for other reports of the same issue.
