### ISSUE TITLE
Trying to update a script with over 8k lines (almost 9,000) and getting the following issue:

### ISSUE THREAD

**Issue by quujo1** [rojo-rbx/rojo#438]
▼ [Rojo-Warn] Could not apply all changes requested by the Rojo server:
[Rojo-Warn] - Update properties on GameScript: Source (x2)

Is there any way to fix this?

**Comment by LPGhatguy** [comment]
Hello, thanks for the report!

This is a Roblox limitation, sadly. You can see #328 and #199 for previous reports of the same issue. With the changes in Rojo 6.0, it seems like this error message has become more confusing. I am going to keep this issue open as part of trying to make it better.

Plugins cannot create scripts larger than around 200 kB. That's pretty big! There are two things you can do here:

1. Break apart your script! Regardless of Roblox or Rojo's limitations, putting everything into one giant script is not ideal. You'll eventually run into Roblox's other limits, like limits on upvalues and locals. It's also very difficult to manage massive single files in general.
2. Use `rojo build` to build your place file initially. If you're frequently editing this file, this won't help much. However, for infrequently edited large files, Rojo can _build_ a place or model file with scripts this large, it just can't live sync them using `rojo serve`.

**Comment by boatbomber** [comment]
Resolved in 7.4.0 by using `ScriptEditorService:UpdateSourceAsync`.
