### ISSUE TITLE
Rojo crashing when attempting to sync character models

### ISSUE THREAD

**Issue by jheinem1** [rojo-rbx/rojo#439]
When attempting to start Rojo in a project with two `.rbxm` files, Rojo promptly crashed. As nothing had been added other than the models since the project was last synced, I've identified them as the issue. The two models (attached to this issue) were exported using Roblox Studio's export to file with no modifications.

Error Message:
```
[INFO ] Unknown binary chunk name SSTR
[ERROR] Rojo crashed!
[ERROR] This is probably a Rojo bug.
[ERROR] 
[ERROR] Please consider filing an issue: https://github.com/rojo-rbx/rojo/issues
[ERROR] 
[ERROR] Details: called `Result::unwrap()` on an `Err` value: InvalidTypeError(28)
[ERROR] in file C:\Users\runneradmin\.cargo\registry\src\github.com-1ecc6299db9ec823\rbx_binary-0.5.0\src\deserializer.rs on line 270
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

RBXM Files:
[Models.zip](https://github.com/rojo-rbx/rojo/files/6759016/Models.zip)

Some additional information:
- Running the latest version of rojo through vscode
- Project was initially created through roblox-ts's project initialization, not Rojo's
- Running Windows 10 version 2004 on a 64-bit system

**Comment by jheinem1** [comment]
Will add that this issue isn't present in the exported `.rbxmx` files and is probably just due to the back references in the welds.

**Comment by LPGhatguy** [comment]
Hello, thank you for filing an issue!

This is a known limitation in Rojo 6. Our support in Rojo 6 for the binary model format (rbxm, rbxl) is very limited. We have improved it dramatically in Rojo 7.

Because we're already there and just about ready to stabilize Rojo 7, I am going to close this issue.
