### ISSUE TITLE
Defining a BasePart's BrickColor in project.json breaks studio plugin

### ISSUE THREAD

**Issue by ShaneButt** [rojo-rbx/rojo#440]
Repro: Modify the Baseplate inside a Rojo project.json file to have an explicitly typed BrickColor property.

Serving rojo won't produce an error (as expected, there is shouldn't be one), connecting the plugin in studio is where the following error arises:
user_rojo.rbxm.Rojo.RbxDom:25: attempt to index nil with 'Color'

**Comment by boatbomber** [comment]
This is an rbx dom issue, and is tracked here:
https://github.com/rojo-rbx/rbx-dom/issues/319
