### ISSUE TITLE
Loading rojo built places loads baseplate without color

### ISSUE THREAD

**Issue by ShaneButt** [rojo-rbx/rojo#443]
VERSION: 7.0.0-alpha.4

This is fixed upon syncing - even if the project.json is unchanged between the build and syncing. Not sure if this is an intended feature or not but it seems like unusual behaviour.

![Before syncing](https://cdn.discordapp.com/attachments/596685628792373264/861946364572598292/unknown.png)
![After syncing](https://cdn.discordapp.com/attachments/596685628792373264/861946379806048316/unknown.png)

Above images depict the issue discussed, first image is prior to syncing; second one is after. The texture *does* exist before syncing and is coloured appropriately (tried with a white colour and it loads in correctly). This seems to only affect Parts as the Texture's colour does translate to the build file correctly (tried 1,1,1 and 0,0,0 and both work).

This happens to all Parts that rojo manages in the project.json file.

**Comment by LPGhatguy** [comment]
Thanks for the bug report!

Do you have a project zip that you can share so that we can reproduce the issue?

**Comment by ShaneButt** [comment]
Sure! Attached below is a project made from `rojo init` and then modifying the `default.project.json` to reproduce the bug/issue.

Also, for this project here is [before sync](https://prnt.sc/192s5ud) and [after sync](https://prnt.sc/192sauf) comparison just like above - black upon opening in studio, fixed and coloured when synced with rojo.

[RojoBugReport.zip](https://github.com/rojo-rbx/rojo/files/6772078/RojoBugReport.zip)

**Comment by kennethloeffler** [comment]
I've isolated the `Part.Color` issue to XML builds. However, a binary build of this project exhibits a different problem with `Part.Position`: this property seems to always end up with a value of `0, 0, 0`. On the left is a `rbxl`, while on the right is a `rbxlx`:

![image](https://user-images.githubusercontent.com/13822714/125536611-e6c40f4a-b462-46c6-8b98-a3dc5cee638c.png)

Maybe we should create another issue to track this other bug?

**Comment by LPGhatguy** [comment]
Solved with the above linked issues from a couple months ago!
