### ISSUE TITLE
OptionalCoordinateFrame is being removed from rbxmx files

### ISSUE THREAD

**Issue by eAi** [rojo-rbx/rojo#448]
I understand this may be a somewhat known issue - but I'm not quite clear what the situation is with it.

We generate a place file from a set of rbxmx files. These rbxmx files have been generated by remodel. Roblox Studio generates the OptionalCoordinateFrame elements, which remodel then outputs to the rbxmx files, but when rojo generates the place file, it removes the OptionalCoordinateFrame. This means that we can get spurious changes to the rbxmx files (which we check into git).

Is the current situation just a stop-gap until full support has been added for this? I've read the related issues for rbx-dom, but it's not quite clear to me as a (relative) layman whether when these issues are resolved that this issue will also be resolved? 

https://github.com/rojo-rbx/rbx-dom/issues/193

**Comment by kennethloeffler** [comment]
rbx-dom does fully support properties of this type, but no Rojo release can currently read or write them because the dependencies haven't been bumped yet! In contrast, Remodel just had them upgraded yesterday . If you need Rojo to do this, you need to edit its `cargo.toml` to use the latest rbx-dom library versions and built it from source:

```toml
rbx_binary = "0.6.2"
rbx_dom_weak = "2.2.0"
rbx_reflection = "4.1.0"
rbx_reflection_database = "0.2.1"
rbx_xml = "0.12.2"
```

**Comment by kennethloeffler** [comment]
Forgot one thing: you'll also need to replace Rojo's `plugin/rbx_dom_lua` with rbx-dom's and build and install a new copy of Rojo's plugin. Alternatively, you can just wait for the Rojo 7 release which should be coming very soon! :D

**Comment by eAi** [comment]
Thanks - for now I’ve written a post-process script that’s strips out these elements. Not sure if that’s going to cause issues as I’m not entirely sure what this element does. If it does cause issues I’ll follow your steps - many thanks for detailing them.

**Comment by kennethloeffler** [comment]
The type exists because of [Roblox Studio's new pivot points feature](https://devforum.roblox.com/t/pivot-points-studio-beta/1180689). If you're not using them, then simply stripping them out should be fine.

**Comment by boatbomber** [comment]
Rojo has been upgraded with the latest dom and Rojo 7 has been released.
