### ISSUE TITLE
VSC not synchronization to roblox script

### ISSUE THREAD

**Issue by qw1324** [rojo-rbx/rojo#452]
I have a problem 
![image](https://user-images.githubusercontent.com/49418651/126524695-11d72555-069b-467f-9ff6-631c6b06f7c3.png)
how can i fix it

**Comment by LPGhatguy** [comment]
You have the "Two-Way Sync (EXPERIMENTAL!)" feature enabled in your plugin. Turn it off, it's experimental for a reason!

**Comment by qw1324** [comment]
ok thx I will try it
