### ISSUE TITLE
Rojo plugin giving errors in Roblox Studio.

### ISSUE THREAD

**Issue by VirtualPixl** [rojo-rbx/rojo#454]
I keep getting this error:
```
 17:24:45.779  Unhandled promise rejection:

HTTP 400:
{"kind":"BadRequest","details":"Wrong session ID"}

user_Rojo.rbxmx.Rojo.Promise:81 function new
user_Rojo.rbxmx.Rojo.Promise:166 function andThen
user_Rojo.rbxmx.Rojo.Plugin.ApiContext:192 function write
user_Rojo.rbxmx.Rojo.Plugin.ServeSession:217 function __onInstanceChanged
user_Rojo.rbxmx.Rojo.Plugin.ServeSession:59 function onInstanceChanged
user_Rojo.rbxmx.Rojo.Plugin.InstanceMap:203 function __maybeFireInstanceChanged
user_Rojo.rbxmx.Rojo.Plugin.InstanceMap:187
  -  Edit
```
Why am I getting it?

**Comment by LPGhatguy** [comment]
Hello, thank you for filing an issue.

Can you provide more details about what you're doing when you get this error?

This error should only pop up when the Rojo server restarts in the middle of the Roblox Studio plugin sending a request. The plugin wants to ensure that it's talking to the same server from request to request, and this error means that it has noticed that the server is now a different server.

**Comment by VirtualPixl** [comment]
I have no idea. It seems to be not happening now.

**Comment by LPGhatguy** [comment]
Because I see `__onInstanceChanged`, I'm going to assume that you have an experimental feature enabled, two way sync. You should turn that off, it's labeled as experimental for a reason, etc.

I'm going to close this issue as it's something we'll revisit when we resume work on it.
