### ISSUE TITLE
Syncing an UIStroke from a rbxmx, doesnt set the correct RGB values

### ISSUE THREAD

**Issue by VerdommeMan** [rojo-rbx/rojo#469]
When syncing an rbxmx with a UIStroke, it doesnt set the right RGB values for that UIStroke.

For example syncing [test.zip](https://github.com/rojo-rbx/rojo/files/6969960/test.zip) (when unzipped),
creates an UIStroke which has always the RGB values of (0,0,0)

Rojo & plugin V6.2.0

**Comment by nezuo** [comment]
This appears to be fixed on `v7.0.0-rc.1`.
