### ISSUE TITLE
Rojo with Team Create (Not commit files automatically?)

### ISSUE THREAD

**Issue by Sxribe** [rojo-rbx/rojo#471]
Hi,

my team is trying to use Rojo while working together on a team-create project. We're looking for a way to get Rojo to not overwrite each others' files while we are working together. Since as roblox game files cannot be checked into source control for merging and whatnot (as far as I know), is there a way to get Rojo to not commit files to ROBLOX? Sort of how editing scripts works right now with the Drafts window during team-create. Or perhaps there is another better solution for this?

**Comment by Kampfkarren** [comment]
> Since as roblox game files cannot be checked into source control for merging and whatnot 

They definitely can be, you can have a place be partially managed (Rojo only updates some of your game, see https://github.com/Kampfkarren/zombie-strike)) or fully managed.

Rojo as a concept just does not lend well to multiple people doing stuff at the exact same time on Team Create.

**Comment by unix-system** [comment]
The way to achieve this is to have separate places where you're working on the same codebase, and then merge it into your production / staging environment from the appropriate branch in Git *after* merge.

The problem you're encountering here is you're trying to do SCM with Roblox TeamCreate - this doesn't really work because TeamCreate has no respect for source control, nor will it.

**Comment by Sxribe** [comment]
> The way to achieve this is to have separate places where you're working on the same codebase, and then merge it into your production / staging environment from the appropriate branch in Git *after* merge.
> 
> The problem you're encountering here is you're trying to do SCM with Roblox TeamCreate - this doesn't really work because TeamCreate has no respect for source control, nor will it.

Yep, this is what we've been doing so far, and I guess it works pretty okay 👍
