### ISSUE TITLE
"thread 'main' has overflowed its stack" when attempting to build plugin

### ISSUE THREAD

**Issue by PhoenixWhitefire** [rojo-rbx/rojo#477]
I was trying to build Clonetrooper1019's [.VMF Importer](https://github.com/CloneTrooper1019/Roblox-Plugins/tree/main/VMFImporter) plugin using Rojo. I've never used Rojo before, but after adding it to my Path account variable and all that other stuff, I clicked the Terminal>Run Active File option in VSCode with the folder set to the downloaded VMFImporter plugin's main folder. And then it showed

thread 'main' has overflowed its stack

in the terminal. I'm not sure if I'm doing something wrong, and I probably made a stupid mistake somewhere, but I'm kinda stuck. I can't find any resources showing how to build plugins with Rojo. Using Command Prompt as well as Powershell just does the same thing.

**Comment by LPGhatguy** [comment]
These project files were not updated for Rojo 6.0; they try to include themselves when you build them, which results in this error.

We get a lot of reports about these projects in particular. I've contacted Clonetrooper about fixing the projects or providing more detailed instructions a couple times, I will follow up again.
