### ISSUE TITLE
BUG: Not converting init.lua to module scripts

### ISSUE THREAD

**Issue by Alvin-He** [rojo-rbx/rojo#485]
According to the rojo documentation, when there's a file named init.lua in a folder. It will turn that folder into a module script. However, that's not the case on my Windows 10. I used rojo build to gererate a build.rbxlx file. After I opened it, *I found that I have a lot of folders containing a module script called **init**; instead of the module script that I expected.* I tried using the live sync, redowloading both roblox&vscode extensions and I still have the same result. I didn't find any errors massages from rojo.
I'm using rojo 6.2.0 (vscode extension 1.13.3)

VSCode file tree:
![InkedInkedCapture_LI](https://user-images.githubusercontent.com/71620129/135568119-c4a10a5d-8f08-4406-9f79-e5cba415427b.jpg)

The out put of roblox: 
![Capture](https://user-images.githubusercontent.com/71620129/135567903-a65c4c4c-b979-4d07-9df1-99acb33e67fd.PNG)

**Comment by Kampfkarren** [comment]
![image](https://user-images.githubusercontent.com/3190756/135576279-246e20d0-1b12-4335-90b0-a3253ca773f4.png)


Looks like you have a space in the name, can you confirm you don't?

**Comment by Alvin-He** [comment]
I removed the space and it's working accordingly now, thanks.
