### ISSUE TITLE
RBXM Models: Unknown Binary Chunk Name SSTR

### ISSUE THREAD

**Issue by Nidoxs** [rojo-rbx/rojo#488]
When attempting to sync in .rbxm models using the release candidate of Rojo version 7, there seems to be an error with syncing in roblox models.

Error message / ouptut is as follows:
![image](https://user-images.githubusercontent.com/75750304/137591015-722a6f6a-64c6-4f4c-ba09-2d05b4642f98.png)

The models in question:
![image](https://user-images.githubusercontent.com/75750304/137591045-2f400ea9-0d4c-4c85-baaf-f78cbc598606.png)

**Comment by LPGhatguy** [comment]
I see `Unknown binary chunk name SSTR` and `rbx_binary-0.5.0` here. This tells me that this is not Rojo 7. This is Rojo 6, which does not support binary models.

I am going to close this issue; if you would like to have it reopened, please run `rojo --version` and share the output to show that you are running the correct version of Rojo.
