### ISSUE TITLE
Root Folder in default.project.json

### ISSUE THREAD

**Issue by 78josh5** [rojo-rbx/rojo#492]
Hello,

I have a project set up to use Rojo, but I would like to be able to use the root folder to store some .lua files rather than create an `src` folder. Is there any way in which I can set up `StarterPlayerScripts` to use the root folder of my project?

**Comment by LPGhatguy** [comment]
This is not generally supported by Rojo. If you have multiple scripts, it is recommended that you store your project in a different folder than all of those scripts.

Previously, you could use `"$path": "."`, but this was removed in Rojo 6 as it gained new meaning.
