### ISSUE TITLE
Support for .luau extension

### ISSUE THREAD

**Issue by GlowingUmbreon** [rojo-rbx/rojo#499]
Recently the LuaU repository has changed the primary extension to .luau (see: Roblox/luau#97).
It may take a while for the .luau extension to pick up support in the development community but now since it is now the primary extension for the luau repository it would be ideal to add support for it in rojo.

**Comment by LPGhatguy** [comment]
Let's plan to have this in right after 7.0 stable!

**Comment by insyri** [comment]
Is there a tracked PR for this issue? If not, I can pick this up across the Rojo ecosystem.

**Comment by Kampfkarren** [comment]
7.0.0 is out, so you should be able to just go for it.

**Comment by ambers-careware** [comment]
Any updates? Writing a new library with heavy use of strict mode / type annotations, and was wanting to use .luau to make the file type distinct from .lua

**Comment by imacodr** [comment]
Should be coming next update.

**Comment by LPGhatguy** [comment]
Fixed by #552.
