### ISSUE TITLE
Add New Baseplate

### ISSUE THREAD

**Issue by havi11** [rojo-rbx/rojo#505]
I'm tired of the old baseplate, can you add the option for the new baseplate?
![image](https://user-images.githubusercontent.com/85591146/145132598-5d4c0fbc-d291-468d-9a9a-e8985e98e629.png)

**Comment by LPGhatguy** [comment]
The new baseplate does look cool, but it's a lot to include in a project. I think it's out of scope for Rojo to be a full-featured project generator.

For the time being, I think the default place project will stay as it is.
