### ISSUE TITLE
After Using Rbxlx To Rojo, I get errors. I tried starting the server, but I get this

### ISSUE THREAD

**Issue by 830008** [rojo-rbx/rojo#509]
![Code_CsZYuPxJbf](https://user-images.githubusercontent.com/55303069/145654298-a48d3b45-6044-4432-989e-c6412fcc84f8.png)

**Comment by LPGhatguy** [comment]
This is a user configuration error that was resolved in the Roblox OS Discord. Error message has been improved in Rojo 7.0.
