### ISSUE TITLE
UDim2 in JSON Model

### ISSUE THREAD

**Issue by 3gabyxD** [rojo-rbx/rojo#513]
i cant change Size or Position property of a frame, nothing happens when i save

**Comment by LPGhatguy** [comment]
Hello! Thank you for filing an issue (and apologies for the delay in responding!)

Can you provide more information about this issue? When trying to reproduce this issue, it appears that Rojo does correctly sync UDim2 properties.

If you are still running into this issue on the latest version of Rojo, currently 7.1.1, we can reopen this issue and look into this more.
