### ISSUE TITLE
Attribute Support

### ISSUE THREAD

**Issue by fuzzy-bit** [rojo-rbx/rojo#514]
In my module loading framework, I use attributes to load modules in order. This is currently impossible in Rojo, and I think it should be implemented in one way or another. A good way to implement attributes for scripts would be to have a JSON file with the same name as the file (w/o extension) and associate them that way. Project files could also disable this feature.

**Comment by Ozzypig** [comment]
Duplicate of #262

**Comment by fuzzy-bit** [comment]
Ah, didn't see.
