### ISSUE TITLE
Rojo upload error

### ISSUE THREAD

**Issue by Masenyy** [rojo-rbx/rojo#515]
When I try and push code to Github then automatically upload to my Exprience on roblox. I get this error: 
![image](https://user-images.githubusercontent.com/26825940/147413527-c5064d33-3bea-4b36-bd16-4df6cfd76048.png)

And this is my  ci.yaml
![image](https://user-images.githubusercontent.com/26825940/147413542-31f4288f-1719-4fff-b19f-95eb83876180.png)

**Comment by Masenyy** [comment]
Here is a second error I got:
![image](https://user-images.githubusercontent.com/26825940/147415778-8e8821c3-7adf-4076-9e28-2e4b390b9644.png)

**Comment by unix-system** [comment]
This is not caused by Rojo, and appears to be an issue with your CI environment, or perhaps an outage on Roblox / the DNS provider.
