### ISSUE TITLE
Rojo doubling every folder in default.project.json.

### ISSUE THREAD

**Issue by OverseersMight** [rojo-rbx/rojo#516]
I just recently started using rojo, but any folders specified in `default.project.json` are made twice in the studio explorer and I have no idea why...
My VSCode explorer:
![image](https://user-images.githubusercontent.com/55365576/147489872-0f20de66-3d35-4ffe-a7f7-ceb1ced13b59.png)

```json
{
  "name": "Game",
  "tree": {
    "$className": "DataModel",

    "ServerScriptService": {
      "$className": "ServerScriptService",
      "$path": "src/ServerScriptService",

      "Loaders": {
        "$className": "Folder",
        "$path": "src/ServerScriptService/Loaders",

        "KronosEvolved - Initalizer": {
          "$className": "Folder",
          "$path": "src/ServerScriptService/Loaders/KronosEvolved - Initalizer"
        }
      },
      
      "Unused (all disabled)": {
        "$className": "Folder",
        "$path": "src/ServerScriptService/Unused (all disabled)"
      }
   }
  }
}
```
In game explorer:
![image](https://user-images.githubusercontent.com/55365576/147489854-b4135d9f-a1b5-4ec9-8e5f-b60d099739df.png)
Unsure if this is a user error or a bug.
Anyone know the reason as to why I am receiving this unexpected behavior?

**Comment by Kampfkarren** [comment]
Are you sure you don't accidentally have two Rojo servers running?

**Comment by OverseersMight** [comment]
I just restarted my computer and immediately launched VSCode and Roblox Studio, rojo immediately created the same thing as shown above.

**Comment by OverseersMight** [comment]
I am using the extension to manage everything for me and running windows 11, if that helps in the troubleshooting process.

**Comment by LPGhatguy** [comment]
You are telling Rojo to load everything twice in your project!

Delete all these redundant paths:

```diff
    "ServerScriptService": {
      "$className": "ServerScriptService",
      "$path": "src/ServerScriptService",

-      "Loaders": {
-        "$className": "Folder",
-        "$path": "src/ServerScriptService/Loaders",
-
-        "KronosEvolved - Initalizer": {
-          "$className": "Folder",
-          "$path": "src/ServerScriptService/Loaders/KronosEvolved - Initalizer"
-        }
      },
```

**Comment by OverseersMight** [comment]
Thank you, this makes soo much more sense now.
