### ISSUE TITLE
Two way sync Crash after submit from Studio

### ISSUE THREAD

**Issue by Francois-CoteDulude-SuperSocial** [rojo-rbx/rojo#519]
[ERROR rojo] Rojo crashed!
[ERROR rojo] This is probably a Rojo bug.
[ERROR rojo] 
[ERROR rojo] Please consider filing an issue: https://github.com/rojo-rbx/rojo/issues
[ERROR rojo] 
[ERROR rojo] Details: called `Result::unwrap()` on an `Err` value: Os { code: 5, kind: PermissionDenied, message: "Accès refusé." }
[ERROR rojo] in file src\change_processor.rs on line 226
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

**Comment by xynnylol** [comment]
That is something to do with access permissions. PermissionDenied is when an app doesn't have the access rights to read or write to a certain file.

**Comment by LPGhatguy** [comment]
We have a lot of work to do on two-way sync's foundations, so I'm going to close this since the code will be rewritten as it stabilizes.
