### ISSUE TITLE
Feature request: a way to create a new lua script file in the external editor when a new script is created in studio.

### ISSUE THREAD

**Issue by CertifiedRice** [rojo-rbx/rojo#522]
Most people when making scripts tend to put them into an object in the workspace, a way to sync up newly created scripts in the studio so that you can edit them in the external editor without having to sync it up.

**Comment by Kampfkarren** [comment]
This is part of what two way sync is meant to accomplish, I'd imagine.

**Comment by Kampfkarren** [comment]
It's still in development, but the point is this is just a part of it.
