### ISSUE TITLE
VSCode plugin is at v6

### ISSUE THREAD

**Issue by smokhov** [rojo-rbx/rojo#523]
Just did a fresh install via VSCode and got Rojo 6. From reading the docs and the repo it seems 7.0.0 is out. When will the VSCode plugin will catch up? It seems there are some incompatibilties.

**Comment by LPGhatguy** [comment]
You can choose what version of Rojo to use from the VS Code Rojo plugin by going to your settings. We should update the default at some point, but there's no blockers stopping you from using it!
