### ISSUE TITLE
WrapTarget.HSRAssetId causes `rojo build` to fail if outputting to binary format

### ISSUE THREAD

**Issue by NobleDraconian** [rojo-rbx/rojo#525]
Currently, as of `7.0.0`, if a project has any `WrapTarget` instances, it will cause `rojo build` to spit an error if attempting to output to a binary format:
![image](https://user-images.githubusercontent.com/26460940/154766163-8fd0632b-3964-4f2b-b396-450f08334827.png)

This issue does *not* occur if writing to XML format:
![image](https://user-images.githubusercontent.com/26460940/154766202-fd9f20b5-af89-499f-bbae-c15373fe65a8.png)

![image](https://user-images.githubusercontent.com/26460940/154766322-11949128-9722-4038-9df1-dad22c3a21cc.png)

**Comment by unix-system** [comment]
Unable to reproduce this. Can you send the exact model that you're using, if possible?

**Comment by NobleDraconian** [comment]
Hey unix! Here's the repro:
[Rojo_BugRepro.zip](https://github.com/rojo-rbx/rojo/files/8555383/Rojo_BugRepro.zip)

**Comment by Dekkonot** [comment]
Unable to reproduce this issue in the latest build of Rojo, I suspect it was a failure in our reflection database.
