### ISSUE TITLE
Studio disconnecting every now running Ubuntu/Grapejuice

### ISSUE THREAD

**Issue by imacodr** [rojo-rbx/rojo#526]
Every now and then I have experienced Rojo disconnecting out of nowhere. There isn't really a pattern. I've been running Studio on Ubuntu with [Grapejuice](https://gitlab.com/brinkervii/grapejuice).

Running Rojo 7.0.0 although while I was using v6 it still happened.

![image](https://user-images.githubusercontent.com/60328723/156940126-cc761f74-9f42-44e3-bcc4-533f09fe7beb.png)

**Comment by LPGhatguy** [comment]
Rojo doesn't do anything special with HTTP connections. Using Grapejuice is a specific enough setup that I don't know if there's anything we can do on our side.
