### ISSUE TITLE
Feature request: json files for models and objects

### ISSUE THREAD

**Issue by CertifiedRice** [rojo-rbx/rojo#529]
It would be pretty useful to have a feature where you can use JSON files to create objects/models in the studio with ROJO. 
The JSON would have properties for every property in the model/and or object/part(For example, Color, Size, and pos) 

It would be cool if this could be a feature sometime in the future!

**Comment by Kampfkarren** [comment]
You already can.

https://rojo.space/docs/v6/sync-details/#json-models

**Comment by CertifiedRice** [comment]
nice ok
