### ISSUE TITLE
How to rebuild from source

### ISSUE THREAD

**Issue by Thyssenkrupp234** [rojo-rbx/rojo#533]
With the latest version of Rojo, it gives errors while trying to do things, such as installing the plugin. The binary was built on Catalina, which only provides support for catalina and up. It isn't your job to support older versions (but it is always nice to), so what are the instructions for rebuilding from source? I really need this on 10.13 High Sierra so my old mac can run Rojo, i don't really want to patch Monterey yet.

Thanks!

**Comment by unix-system** [comment]
Sorry about the wait time here!

All you need to do is download `rust` (https://rustup.rs/), clone the repository, navigate to the repository and run `cargo build --release`. You might find it helpful to explicitly define your target via the `--target` flag as `x86_64-apple-darwin`.

> `cargo build --release --target x86_64-apple-darwin`
