### ISSUE TITLE
Unable to open scripts from roblox to visual studio

### ISSUE THREAD

**Issue by Gamerjimjam** [rojo-rbx/rojo#542]
When trying to open scripts externally using visual studio code, nothing happens. There is only an error in the console saying "[Rojo-Warn] Cannot sync non-nil Parent property changes yet". I am super new to rojo, and dont know any fixes or workaround.

**Comment by nezuo** [comment]
This will happen when `Two-Way Sync` and `Open Scripts Externally` are both enabled. It happens because `Open Scripts Externally` unparents the script briefly to force close it in Studio which interferes with two-way sync. I would recommend disabling two-way sync since it an experimental/unstable feature.

**Comment by cyrus01337** [comment]
Can confirm the solution that @nezuo suggested works. While testing I also encountered strange behaviour on Ubuntu where the warning pops up _and_ the editor opens the script. I'm assuming this was not meant to occur and this will/has already been fixed in the new version?

**Comment by Gamerjimjam** [comment]
@nezuo I have two way sync off, and it still doesn't work, it only does with notepad.

**Comment by nezuo** [comment]
@Gamerjimjam, `Open Scripts Externally` opens the file in the default program configured for `.lua`. You can edit this on Windows by going to `Settings > Apps > Default Apps > Choose defaults by file type`, searching for `.lua`, and setting it to your desired editor.

**Comment by Gamerjimjam** [comment]
This opens for all other text editors except visual studio code, even with two way sync on. How do i configure it so that it opens with visual studio code. @nezuo

**Comment by Gamerjimjam** [comment]
It still doesnt work but if i want to create a new script i can just add a new one and move it to my desired location (workspace, replicatedstorage, etc)

**Comment by Vundeq** [comment]
isnt working for me either, two way sync is disabled, default extension for .lua and .luaU is vscode. what do.

**Comment by kennethloeffler** [comment]
> isnt working for me either, two way sync is disabled, default extension for .lua and .luaU is vscode. what do.

Hi @Vundeq, are you serving via the VS Code extension, or from the command line? Does it work if you run `rojo serve` from the command line?

**Comment by advra** [comment]
Just wanted to chime in. I had rojo installed on WSL. But after installing Rojo through aftman directly with windows  binary and running `rojo serve` as mentioned  (after disabled two way sync) opening files in code works!
