### ISSUE TITLE
Rojo errors when trying to use it's commands

### ISSUE THREAD

**Issue by Lemon6K** [rojo-rbx/rojo#543]
When calling any command from Rojo(in F1 menu) in Visual Studio Code, it always returns the same error as a Windows popup:

> An error occurred while starting Rojo: TypeError: Cannot read properties of undefined (reading 'find')

It never happened to me before. Reinstalling Rojo didn't help as well, and it think it has something to do with a new update.

**Comment by Kampfkarren** [comment]
Are you sure this is not an extension bug? Perhaps you want the issue filed there instead?

**Comment by Lemon6K** [comment]
> Are you sure this is not an extension bug? Perhaps you want the issue filed there instead?

Im pretty sure this is an extension bug 'cause it happens with any folder/project opened and the error itself looks like it has something to do with the extension's code

**Comment by Kampfkarren** [comment]
[Might want to file it here then](https://github.com/rojo-rbx/vscode-rojo)
