### ISSUE TITLE
Not showing correct address on serve on the CLI

### ISSUE THREAD

**Issue by WatermelonArray** [rojo-rbx/rojo#555]
I have been using Rojo for a network configuration. Using `rojo serve`, I can specify an address for Rojo to host to. In my case, my local machine's IPv4 address instead of hosting it on `localhost`.

However when successfully hosting to your specified address, the CLI displays incorrect information about where the host is sending data to - it still shows: `Visit http://localhost:34872 in your browser for more information`

This is does not effect my workflow at all but still is a **minor** bug.

Here is an image of the bug using Linux CLI binary Version 7.1.1:
![2022-06-13-123125_1920x1080_scrot](https://user-images.githubusercontent.com/34957838/173347286-db0cd78f-fac7-4ea0-8e1a-e1b8b264ccfc.png)

This should display:
`Visit http://192.168.1.226:34872 in your browser for more information`

---

NOTE:
The port number changes when you specify a port value on the command, but not the address.
![2022-06-13-125831_1920x1080_scrot](https://user-images.githubusercontent.com/34957838/173348040-3c0c914d-00bf-4688-a1d1-170e12f67932.png)

EDIT: Because you are hosting to an address, it is not hosting to localhost. If you try to connect to `localhost:348721`, you simply are unable to establish a connection.

**Comment by LPGhatguy** [comment]
Thank you for the bug report, this is a great catch!

This should be a straightforward fix in `cli/serve.rs`.
