### ISSUE TITLE
Cannot remove directories while Rojo is running

### ISSUE THREAD

**Issue by Anaminus** [rojo-rbx/rojo#560]
1. Create a new file called `run.bat` with the following content:

```batch
@echo off
mkdir test
cd test
rojo init
mkdir src\client\test\foo
start rojo serve
timeout 1
rd src\client\test /s /q
timeout 1
echo Attempting to remove directory
rd src\client\test /s /q
pause

taskkill /F /IM rojo.exe
timeout 1
echo Attempting to remove directory again
rd src\client\test /s /q
if not exist src\client\test echo directory was removed
pause

cd ..
rd test /s /q
```

2. Run the `run.bat` file.
3. On the first pause, observe that the `rd` command errors with "Access is denied."
4. Press any key to continue.
5. On the next pause, observe that the `rd` command was successful.

**Comment by LPGhatguy** [comment]
I am guessing that this happens because of Rojo's file watcher.

I wonder what we can do about this. [notify](https://crates.io/crates/notify) is generally unmaintained, but I don't think another library has popped up in its place.
