### ISSUE TITLE
Sync arbitrary file extensions as plaintext

### ISSUE THREAD

**Issue by OttoHatt** [rojo-rbx/rojo#562]
Rojo already has a way of syncing plaintext files in as `StringValues`. A lot of programs (i.e. dialogue files, markdown) export into plaintext formats that could be with interpreted with a parser in-game. It'd be cool to define a list of file extensions that are resolved as if they were plain `.txt` files.

**Comment by Kampfkarren** [comment]
This presents a real forwards compatibility hazard :(

**Comment by OttoHatt** [comment]
I think a whitelist (maybe as an optional array in the top-level of `.project.json` files) is the only way to go about it? I'm not sure how you'd implement this without it feeling too clunky; it almost crosses into the domain of Remodel as you're effectively processing the contents of files before they're synced in...

For now though, would it be considered adding some files (other than `.txt`) that are imported like plaintext? I think [`.yarn`](https://yarnspinner.dev/) and `.md` would be a good start?

**Comment by Kampfkarren** [comment]
Eventually Rojo plugins intend to fill the space you're talking about, but that's a pretty big architecture.

**Comment by sasial-dev** [comment]
I feel like `LISENCE`/`LISENCE.md` should be sync in as plaintext

**Comment by kennethloeffler** [comment]
This is closed by #813, which will be available in Rojo 7.5.
