### ISSUE TITLE
Experience doesn't have permissions for notification sounds.

### ISSUE THREAD

**Issue by spectraljake** [rojo-rbx/rojo#567]
![image](https://user-images.githubusercontent.com/24721341/176903121-d3b42adb-e73c-4ae9-b208-bf369832f77e.png)
More of a on-site issue rather than a code issue... thanks Roblox 🙄

**Comment by LPGhatguy** [comment]
Hopefully resolved by #566. Looks like we can't use our own sound effect right now, and we'll need to replace it with a generic sound.

**Comment by sasial-dev** [comment]
Fixed in #566 /`7.2.1`
