### ISSUE TITLE
Rojo CLI with WSL in Windows directory does not broadcast file changes

### ISSUE THREAD

**Issue by 8y8x** [rojo-rbx/rojo#571]
I'm not sure if this is an issue with Rojo or WSL, but I'll report it nonetheless.

When I run `rojo serve`, it will not listen for file changes if I am in a Windows directory (/mnt/c/ ...)
I can reconnect, disconnect, and reconnect again using the Studio plugin, but my code will not change, it will stay whatever it was when I started rojo.

This problem does not occur when using WSL in linux directories, and it does not occur when using the Windows binary in Windows directories. Using `--verbose` does not help.

Steps to reproduce:
1. Initialize a new place project in a Windows directory using WSL
2. Serve it and connect to the server via Roblox Studio
3. Try modifying files and watch as the changes do not appear in studio

If it helps, I am using cargo to install and manage rojo.

**Comment by Kampfkarren** [comment]
I use `rojo serve` inside `/mnt/e/` with WSL and have never had problems.

**Comment by Kampfkarren** [comment]
Oooh, are you guys on WSL or WSL 2? I'm on WSL 1.

**Comment by OverHash** [comment]
If you are using WSL 2, you should not be using the C drive for files for WSL.

**Comment by 8y8x** [comment]
If it's a WSL problem then I'll close this issue.

I moved over to windows folders so I could keep my .rbxl place files with my project, but after some more digging I found I can also access WSL2 from the Network tab in Explorer so I'll stick to that. Thanks for the help y'all
