### ISSUE TITLE
`rojo upload` API errors give a 0 exit code

### ISSUE THREAD

**Issue by osyrisrblx** [rojo-rbx/rojo#575]
![image](https://user-images.githubusercontent.com/9200592/178093387-4aee4d88-066b-44e3-ab8b-0f05197e68fb.png)

API response was non-200 (I think?) and `rojo upload` still gave a 0 exit code indicating success.

Using Open Cloud API

Version 7.2.0

**Comment by Boegie19** [comment]
If I try to replicate this issue on my windows pc it always gives me the correct Exit code so if it errors 1 if it succeeds 0

![image](https://user-images.githubusercontent.com/34578426/181496289-6f1f497b-2d33-4b4c-88c9-fd4e248ce9de.png)

So I can't replicate the issue on my pc in the command line.

**Comment by Kampfkarren** [comment]
https://github.com/rojo-rbx/rojo/blob/7aa7a35aa55029225853f66376e8d0804513cdb7/src/main.rs#L74-L77

This should be exiting with code 1. That's odd!

**Comment by Yumacide** [comment]
Works fine on 7.2.1
![image](https://user-images.githubusercontent.com/88495241/182036517-b78298f3-81c2-41f9-b93d-b0074d112f3b.png)

**Comment by osyrisrblx** [comment]
Using aftman. Maybe this is an aftman bug..? I'll experiment.
