### ISSUE TITLE
[Question] Prevent rojo from overwriting objects in a folder which exists only in the studio

### ISSUE THREAD

**Issue by Richard-van-Veldhoven** [rojo-rbx/rojo#583]
# Question

I am trying to put parts inside of a folder in the ROBLOX studio only. However, each time I click on “connect”, all the parts inside of the folder disappear. How would I prevent this from happening?

## A visual example

The folders in Visual Studio Code (empty):
![Folder in VSCode](https://user-images.githubusercontent.com/108716862/179391513-f38078fb-bcce-4277-af56-ed70a96e494f.png)

The folders in the ROBLOX studio:
![Folder in RBLX studio](https://user-images.githubusercontent.com/108716862/179391419-0511e069-4e38-443a-9f2e-a2365e40ef0b.png)
(I want that part to not get deleted and just stay inside of the folder)

## What I tried

1. Have the part stay inside the ROBLOX studio after pressing "connect" using meta files.
2. Have the part sync back to Visual Studio Code instead of it being deleted.
* *I was ultimately unable to get any of these fixes to work.*

---

*Is there any way to have this work like I explained?*

**Comment by Qualadore** [comment]
Have you tried setting [$ignoreUnknownInstance](https://rojo.space/docs/v7/project-format/) to `false`?

**Comment by Richard-van-Veldhoven** [comment]
@Qualadore After some trying, I seem to have fixed it. Thanks a lot!
