### ISSUE TITLE
libssl.so.1.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by cyrus01337** [rojo-rbx/rojo#585]
When running Rojo v7.2.1 from the Visual Studio Code extension, I receive the following on Kubuntu 22.04:
```
/home/cyrus/.config/Code/User/globalStorage/evaera.vscode-rojo/rojo-v7.2.1: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
```
A number of options appear when searching for `libssl` through `apt` (shown below), is there any specific library/package of choice that's recommended for Rojo?
![image](https://user-images.githubusercontent.com/63274991/180334573-66aa8c64-46b0-4523-ad42-d45dcc6a0d3c.png)

**Comment by cyrus01337** [comment]
Update/Note: installing `libssl3`/`libssl-dev`/both does not resolve this.

**Comment by LPGhatguy** [comment]
Hello, thanks for the report!

I think I see the issue here. Rojo 7.2.1 is looking for OpenSSL 1.1, which comes installed on Ubuntu 18.04 LTS machines where we build releases. However, your system (and package manager) seem to come with OpenSSL 3.0, which doesn't seem to get loaded.

We downgraded our CI machines in #561 on June 26th. 7.2.0 was the first release to go live with this change.

If you downgrade to Rojo 7.1.1, does this still happen? I'm not sure if older versions link against a newer OpenSSL or not.

**Comment by LPGhatguy** [comment]
As an alternative workaround, you might be able to install OpenSSL 1.1 on your system: <https://askubuntu.com/a/1407024>

**Comment by Kampfkarren** [comment]
Long term Rojo should be using rustls. From some searching around in Cargo.lock, it looks like its only reqwest, which uses OpenSSL by default. This could be fixed by turning off default features and flipping on `rustls-tls`.

**Comment by cyrus01337** [comment]
I attempted to downgrade the version of Rojo that the extension uses via the target version setting to no avail:
![image](https://user-images.githubusercontent.com/63274991/183301635-e17e4f46-cd36-4e38-b1ec-979f8728f4ac.png)

There was also an attempt at installing OpenSSL v1.1 with the resource sent which failed [with the given errors.](https://hastebin.com/kivosagogu.properties)

Are there any other options?

**Comment by LPGhatguy** [comment]
It looks like the way to link OpenSSL statically changed at some point, from setting an environment variable to the optional feature `native-tls-vendored` on reqwest. I think this might be a better approach than trying to jump ship to rustls just yet.

Once the builds are up, you should try out this release: https://github.com/rojo-rbx/rojo/releases/tag/v7.2.1-static-openssl

It should work on systems that have a mismatched OpenSSL version or even no OpenSSL at all.

**Comment by LPGhatguy** [comment]
Nevermind. It looks like downgrading the build machines means that Foreman (and proabably Wally) no longer runs on them, a knock-on effect of #561.

**Comment by cyrus01337** [comment]
@LPGhatguy Are you referring to all builds or strictly Windows?

**Comment by Boegie19** [comment]
@cyrus01337 Seems like the release action broke made a pull request to fix it if you want to do it before that you would have to  build from source or use a fork.

**Comment by LPGhatguy** [comment]
I bumped the minimum version of Ubuntu from 18.04 to 20.04 and restarted builds for the static OpenSSL build. It looks like the Linux build succeeded this time around:

https://github.com/rojo-rbx/rojo/releases/tag/v7.2.1-static-openssl

**Comment by cyrus01337** [comment]
Have had some woes with Grapejuice working so testing this has taken some time. Apologies in advance, will get results out soon as.

**Comment by cyrus01337** [comment]
It has been a month, the version works as expected. :)
