### ISSUE TITLE
feature request: Ability to lock rojo projects to certain places.

### ISSUE THREAD

**Issue by NoSharp** [rojo-rbx/rojo#591]
Hello,
I'd like to suggest a feature that'd prevent a rojo project from being used on a place that's not specified in the project.json file.
My motive for this is there's been many times where I have overwritten places by having vscode and rojo running on the wrong project.
I apologise if this is a duplicate or something already implmeneted.

Thank you for reading.

**Comment by Kampfkarren** [comment]
Use `$servePlaceIds`, documented here: https://rojo.space/docs/v7/project-format/#project-file

**Comment by NoSharp** [comment]
🤦‍♂️ Thank you!
