### ISSUE TITLE
Minimum plugin UI size is too big

### ISSUE THREAD

**Issue by Qualadore** [rojo-rbx/rojo#592]
My goal is to maximize my viewport size, and the plugin's minimum length and width is longer and wider than the minimums of Studio's builtin widgets. This causes my panels to become bigger when I merge the plugin widget into them.

I think minimum size is set on [line 195](https://github.com/rojo-rbx/rojo/blob/62eb4f026f7a81967b7a0cf89747fb2ace686c59/plugin/src/App/init.lua).

![RobloxStudioBeta_Qox8hBLP7w](https://user-images.githubusercontent.com/93345551/181083618-612293b5-719f-427a-b38d-2bf2c0f4c5c2.png)
![RobloxStudioBeta_RbzJHXsTru](https://user-images.githubusercontent.com/93345551/181084178-43ad4baf-cb65-4de0-aca0-e21980e67ca1.png)

**Comment by LPGhatguy** [comment]
This makes sense. If you would file a PR to change the maximum size to match the built-in panels, I think we could merge that to fix this case.

**Comment by boatbomber** [comment]
Our UI is not gonna look nice at that tiny size. That's a 41% decrease. Things just won't fit correctly anymore. Our UI won't _break_, but it's gonna feel cramped and things will end up scrolling and being annoying to read.

**Comment by boatbomber** [comment]
Not sure why you went down to 175px, the Output window's minimum is much larger than that.
![image](https://user-images.githubusercontent.com/40185666/182760423-17cbfd81-07e3-4d41-bff6-91c790eac42b.png)

**Comment by boatbomber** [comment]
The output widget minimum width is 300... exactly what Rojo's is.
![image](https://user-images.githubusercontent.com/40185666/182760642-33388f39-013a-462e-95de-2c79c8626fa0.png)

**Comment by boatbomber** [comment]
I agree we could lower the minimum height at least. That just means more scrolling, but that's not a bit deal the way unreadable text is.

**Comment by Qualadore** [comment]
Made it 300x120 now in line with Output's height.
