### ISSUE TITLE
Two-Way Sync Crash

### ISSUE THREAD

**Issue by HwangJeongIn** [rojo-rbx/rojo#595]
when i edit script from client(roblox studio), crash occurs in a specific case

```
[ERROR rojo] Rojo crashed!
[ERROR rojo] This is probably a Rojo bug.
[ERROR rojo] 
[ERROR rojo] Please consider filing an issue: https://github.com/rojo-rbx/rojo/issues
[ERROR rojo] 
[ERROR rojo] Details: called `Result::unwrap()` on an `Err` value: Os { code: 5, kind: PermissionDenied, message: "Access is denied." }
[ERROR rojo] in file src\change_processor.rs on line 226
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

![image](https://user-images.githubusercontent.com/36975010/181471504-e2db3eb1-7e71-46bb-b27c-3ee93e56abdc.png)

![image](https://user-images.githubusercontent.com/36975010/181472241-3c908a81-6718-4137-b973-96b96b6740f9.png)

'TestModuleScript', 'TestScript' : when i edit from rojo or roblox studio, they are ok

'Server' : when i edit from roblox studio, changes are not applied on rojo
'TestModuleScript_FolderVer', 'TestScript_FolderVer' : when i edit from roblox studio, crash occurs

**Comment by LPGhatguy** [comment]
Thank you for the bug report!

Two-way sync is still very early, and this part of the code is likely to be rewritten from scratch. For now, I'm going to close this issue as something we're not planning on fixing directly right now.
