### ISSUE TITLE
HTTPError: NetFail after disconnecting and then reconnecting

### ISSUE THREAD

**Issue by RileyS07** [rojo-rbx/rojo#597]
I have two separate project files and I found this bug while interacting with them.

Reproduction steps:
1) Connect with one project file.
2) Disconnect from the plugin in Roblox studio.
3) Disconnect from within the code editor (VSC for me).
4) Connect to the other project file in the code editor but not in Roblox studio.

This produces an HTTPError: NetFail in the original place even though it is not connected to anything after step two.

**Comment by Boegie19** [comment]
I think issue is already fixed see #579
