### ISSUE TITLE
Fix not using servePlaceIds footgun

### ISSUE THREAD

**Issue by Boegie19** [rojo-rbx/rojo#601]
As said in #285 not using servePlaceIds is a footgun
Step 1: give every project a project id this get added to then place when you build or serve to a place
Step 2: if you serve it should give you a popup if you are sure you want to add this place to your project (This would for come you nuking your an other project)
Step 3: Add the project id to the top level object as a Atribute (Allows us to save there permission given in step 2)  (The discussion will then become would we allow multiple project ids for 1 game)

allow studio if there is a placeID to add the placeID to servePlaceIds (if we do not deprecate this for the 3 steps above)

Step 4: This behaver is turned on by default (if you want the old behaver aka the I don't care behaver you can turn it of in your project.json file)

I think that this is the best option if anyone has an better idea to let a system like servePlaceIds work on both Local and team create places please react under here.

This will allow or the following 2 tings
1 It will ensure you get a popup if you try to sync to the wrong studio instance or wrong place
2 it would allow for auto syncing to work without nuking stuff also on local files

**Comment by boatbomber** [comment]
As said in #285, we don't want to create noisy warnings in most cases. We have a confirmation stage with diff visualization, which was the solution to #285 and therefore this issue can be closed as well. With regard to auto syncing, that's something we want with `rojo open`, not serve pace ids.
