### ISSUE TITLE
ChatVersion property of TextChatVersion doesn't change in Studio.

### ISSUE THREAD

**Issue by kineticwallet** [rojo-rbx/rojo#604]
I tried to change the ChatVersion of TextChatVersion over Rojo in my .project.json file, but it didn't change. I tried to use the both layouts like in the documentation. I get no errors in my IDE/VScode, only a warning in Studio that it could not apply the changes of ChatVersion.
> 1)
```
"TextChatService": {
 "$className": "TextChatService",
 $properties": {
  "ChatVersion": "TextChatService"
 }
}
```
> 2)
```
"TextChatService": {
 "$className": "TextChatService",
 $properties": {
  "ChatVersion": {"Enum": 1}
 }
}
```
Pls correct me if both of these layouts are wrong.

**Comment by Kampfkarren** [comment]
Does rojo build work properly?

**Comment by kineticwallet** [comment]
Yes with the 1. Layout the property changes after building it. But on live syncing with an active project and even the builded version it doesn't change.

**Comment by LPGhatguy** [comment]
It looks like that property may not be scriptable, which means that live sync won't be able to touch it: https://robloxapi.github.io/ref/class/TextChatService.html#member-ChatVersion

The second version should work if you use `rojo build`.

**Comment by kineticwallet** [comment]
ok 👍
