### ISSUE TITLE
Rename `Common` to `Shared` in the default rojo project

### ISSUE THREAD

**Issue by nezuo** [rojo-rbx/rojo#605]
This is what `rojo init` generates by default:
```json
"ReplicatedStorage": {
  "Common": {
    "$path": "src/shared"
  }
},
```
The name of the folder should match the name of the `shared` directory.

If this gets the go-ahead I can make a PR.

**Comment by LPGhatguy** [comment]
This makes sense to me, these names should match.

That said, do you think there is a better naming scheme we can use for this folder?

**Comment by nezuo** [comment]
Nothing comes to mind but all the projects I've seen have used `Shared`.
