### ISSUE TITLE
`SoundService.RespectFilteringEnabled` should default to `true`

### ISSUE THREAD

**Issue by Qualadore** [rojo-rbx/rojo#608]
`default.project.json`
```json
{
	"name": "",
	"tree": {
		"$className": "DataModel"
	}
}
```
Execute `rojo build --output place.rbxl` and observe that `SoundService.RespectFilteringEnabled` is disabled even though it's the default in Studio.

**Comment by LPGhatguy** [comment]
In general, Rojo does not currently prescribe _any_ defaults for a project file. In the given project, `SoundService` will not even exist in the place.

This has been the case with other properties, like `FilteringEnabled` when we had to turn it on manually.

One reason why Rojo does not change any defaults is the same reason that Roblox doesn't: it would break existing projects. If a place currently doesn't have `RespectFilteringEnabled` on, and Rojo silently turns it on for them when they upgrade, they might not be super happy! Especially with Foreman causing semi-automatic tooling upgrades to happen in CI, this would not be fun.

This is something that we can revisit in the future, but for now, we will not be prescribing defaults.
