### ISSUE TITLE
Inserting a UI with an .rbxm file results a Rojo Error via Plugin

### ISSUE THREAD

**Issue by s1imdev** [rojo-rbx/rojo#620]
Hello, I made a **Game Startup GUI** and I just finished it. Since my game's codebase is constructed with Rojo, I saved the file as a **_.rbxm_** file and tried to implement the file into ReplicatedFirst which holds the main LocalScript which manages and makes the UI interactive. So as I insert the file into any directory synced w/ Rojo, it results in an error I have not encountered ever since I had Rojo. 

**_Error(Came from a notification from the plugin):_**
```
cloud_6415005344.Rojo.RbxDom.customProperties:15: invalid argument #1 to 'pairs' (table expected, got string)
```

Image:
https://cdn.discordapp.com/attachments/596685628792373264/1007222069269889034/unknown.png

**Comment by Boegie19** [comment]
upstream issue with rbx dom 
https://github.com/rojo-rbx/rbx-dom/pull/235 if accepted would fix this issue.

**Comment by LPGhatguy** [comment]
> this issue is most likely caused by an project.json or meta.json file with the Attribute in it that is not valid

Rojo already validates these things, statically. This PR will silence the error but won't solve the issue.

**Comment by Boegie19** [comment]
Then that would mean the validation is off on rojos end some how. since it expects an table of string with as value an attribute but it only gets a string.

**Comment by Boegie19** [comment]
@1xozf Mind sending us the file that  has this issue so that we can see what the issue is and how we can fix it?

**Comment by Boegie19** [comment]
This is an issue with rojo 7.1.1 and older version 7.2.1 and above don't have this issue
