### ISSUE TITLE
Rojo does not build model pivots correctly when no PrimaryPart is set

### ISSUE THREAD

**Issue by Rocky28447** [rojo-rbx/rojo#628]
When attempting to build a project file that includes a model saved as a .rbxm with:

1) A pivot point offset from its center
2) No PrimaryPart set

Rojo will not set the pivot point of the model correctly in the resulting .rbxl

Below is a zip file containing a .rbxm which contains 2 identical models that demonstrate the issue. One has a PrimaryPart set and one does not. Inserting this file into studio directly, you'll see 2 identical models. Including it in a rojo build, you'll see 2 identical models with 2 different pivots.

[FloatingRock.zip](https://github.com/rojo-rbx/rojo/files/9353761/FloatingRock.zip)

**Comment by kennethloeffler** [comment]
@Dekkonot would you be okay if we just hack a `Model.NeedsPivotMigration` insertion into `RojoTree::insert_instance` until we address rojo-rbx/rbx-dom#385?

**Comment by Dekkonot** [comment]
I would be more than okay with that for this release. It's important to get it working and we'll have it fixed properly soon enough anyway.

**Comment by kennethloeffler** [comment]
> I would be more than okay with that for Rojo 7.4.1. It's important to get it working and we'll have it fixed properly soon enough anyway.

Should we just put this change on the 7.4.x branch or do we want it on master too? I'd like to square away the rbx-dom issue before 7.5, so I think it should just be on 7.4.x

**Comment by Dekkonot** [comment]
Just 7.4.x seems fine! Makes it less pressing to fix it too since it won't be code we'll potentially forget.

**Comment by kennethloeffler** [comment]
This is closed by #865 (I properly linked this issue with the correct keyword in the PR, what are you doing github)
