### ISSUE TITLE
plugin stuck on loading spinner when no server active

### ISSUE THREAD

**Issue by blinkybool** [rojo-rbx/rojo#636]
Sometime I forget to start the rojo server before I click "Connect" on the rojo plugin.
The plugin then gets stuck on the loading spinner, and I can't figure out how to make it stop trying to connect without restarting Roblox Studio. Even if I start the server it's still stuck on the loading spinner.

**Comment by boatbomber** [comment]
Beyond fixing this bug, I think it would be valuable to have the Connecting page have more than just a spinner. A single line of text informing the user what's currently going on would go a long way here.

**Comment by boatbomber** [comment]
I take it back. The spinner only ever shows while the plugin is hitting the endpoint for the first time, so there's no need for text because it will always just say the one thing. I thought more was happening under the hood during that time.

**Comment by boatbomber** [comment]
Do you have a consistent repro? Whenever there is no server, it doesn't get stuck but rather shows a helpful message.

![image](https://github.com/rojo-rbx/rojo/assets/40185666/5489e8a2-753c-4fed-94ba-dcb63b7b2477)
