### ISSUE TITLE
Syncing script with children crashes extensions

### ISSUE THREAD

**Issue by HedTB** [rojo-rbx/rojo#643]
If you have the two-way sync mode enabled and try to edit a file placed in a folder named `init.lua`, the extension will crash when attempting to write back to the file system. Here's the full error:
![image](https://user-images.githubusercontent.com/73802888/196497178-ede1a143-0f20-4420-a958-9ac7925731c9.png)

**Comment by HedTB** [comment]
Perhaps irrelevant, but my guess is that it's trying to edit `House.lua` ("House" is the name of the folder), instead of the `init.lua` file placed inside the folder.

**Comment by LPGhatguy** [comment]
Hello, thanks for filing an issue!

Two-way sync is still experimental and is not fully implemented. I think we have a couple other reports of similar issues.
