### ISSUE TITLE
Bug with path with a space

### ISSUE THREAD

**Issue by PastaLaPate** [rojo-rbx/rojo#646]
For person have a windows username with a space like 'John Doe' Rojo have a error when he want execute cmd commands

**Comment by Boegie19** [comment]
@PastaLaPate 
You can use " around the path name aka `rojo build "./John Doe" --output test.rbxl `

**Comment by PastaLaPate** [comment]
yes but this bug is when i want install rojo

**Comment by LPGhatguy** [comment]
When are you encountering this error? Are you using the Rojo VS Code extension?

Rojo has no built-in installation. When running commands, you'll need to quote paths with spaces in them, like Boegie19 mentioned.

**Comment by PastaLaPate** [comment]
I have this error when I install rojo and I have the vs code extension

**Comment by Boegie19** [comment]
Mind posting the error you get here.

**Comment by Barocena** [comment]
Fixed
https://github.com/rojo-rbx/vscode-rojo/pull/78
