### ISSUE TITLE
Font Face doesn't sync correctly

### ISSUE THREAD

**Issue by NecroticNanite** [rojo-rbx/rojo#650]
Hi, so I've been creating some new UI screens, and I noticed that if I do a clean sync the Font Face property reverts to Arial (Legacy) and the font weight is lost.

For example:
```
<Font name="FontFace">
	<Family><url>rbxasset://fonts/families/GothamSSm.json</url></Family>
	<Weight>900</Weight>
	<Style>Normal</Style>
</Font>
```

If I import (via Rojo) a rbxmx with a font face defined this way (which is how an exported Roblox TextLabel looks now), it will import as Arial (Legacy) with no weight.

If I re-export that same UI element, it will save the change to Arial.

This is obviously a huge problem for our workflow, as we have multiple people working from Git using Rojo, and not being able to rely on export/import flows to cleanly re-create the UI elements (often in a different place) is problematic.

I'm guessing this used to be fine because Roblox probably retained legacy font data in the export, but they must have removed that at some point.

For example, an older screen that still works has the Enum value still defined (as well as the font face):
```
<token name="Font">18</token>
<Font name="FontFace">
	<Family><url>rbxasset://fonts/families/GothamSSm.json</url></Family>
	<Weight>500</Weight>
	<Style>Normal</Style>
	<CachedFaceId><url>rbxasset://fonts/GothamSSm-Medium.otf</url></CachedFaceId>
</Font>
```

A clean re-import of that screen appears correctly.

**Comment by LPGhatguy** [comment]
Being worked on in <https://github.com/rojo-rbx/rbx-dom/pull/248>

**Comment by noahrepublic** [comment]
Will this be released in the next version or as soon as it is fixed?

**Comment by Barocena** [comment]
It will require a new Rojo release

**Comment by NecroticNanite** [comment]
I think the question was more is this going to be released ASAP as a
hotfix, or wait for a new major or minor version with additional changes.

**Comment by jonnyunderwater** [comment]
We're looking forward to this getting resolved! We wrote a work around, but it's super inconvenient since we have a lot of guis that get updated weekly. Thanks in advance for fixing it!!

**Comment by medallyon** [comment]
Indeed this is also impacting us on a broader scale, would be nice to see this fixed sooner rather than later 🙏
