### ISSUE TITLE
`Lighting.ClockTime` can't be configured

### ISSUE THREAD

**Issue by ghost** [rojo-rbx/rojo#655]
```json
{
	"name": "Example",
	"tree": {
		"$className": "DataModel",
		"Lighting": {
			"$className": "Lighting",
			"$properties": {
				"ClockTime": 6
			}
		}
	}
}
```

`Lighting.ClockTime` will appear as `14` in the output of `rojo build`.

`Lighting.TimeOfDay` can be set to achieve equivalent behavior as a workaround.

**Comment by eAi** [comment]
This doesn't appear to happen for me in the Rojo 7.2.2-uplift.release.3 version.
