### ISSUE TITLE
Rojo appears to generate invalid binary files when a Lighting object is added

### ISSUE THREAD

**Issue by eAi** [rojo-rbx/rojo#656]
With the Rojo 7.2.2-uplift.release.3 version (built by @LPGhatguy I believe?), generating an rbxl file using this config produces a file that Roblox Studio fails to load and that when published, fails to start on Roblox:

```
{
	"name": "Game",
	"tree": {
		"$className": "DataModel",
		"Workspace": {
			"Lighting": {
				"$className": "Lighting",
				"$properties": {
					"ClockTime": 6
				}
			}
		}
	}
}
```

Removing the Lighting section resolves this. Building as rbxlx also resolves this (and the Lighting instance appears correctly). Specifying the Lighting section using an rbxmx file has the same result - it doesn't work.

I think this worked before this version as we had a similar workflow on another project and didn't have any issues.

Here are rbxlx and rbxl files built using this: [Rbxl and Rbxlx Files with Lighting instance.zip](https://github.com/rojo-rbx/rojo/files/10861664/Rbxl.and.Rbxlx.Files.with.Lighting.instance.zip)

Perhaps related to https://github.com/rojo-rbx/rojo/issues/655 (which I can't reproduce in this version)

**Comment by Dekkonot** [comment]
Expected behavior is that having Lighting under Workspace will create an invalid file.
