### ISSUE TITLE
`Unknown property Workspace.StreamingIntegrityMode`

### ISSUE THREAD

**Issue by schmatz** [rojo-rbx/rojo#657]
If you attempt to use the "StreamingIntegrityMode" property of Workspace with Rojo 7.2.1, it throws this error. This is because that property was added after the release was done. [This commit](https://github.com/rojo-rbx/rbx-dom/commit/50812007b5d7a0244ca257d61e5dd12b94f4f30a) introduced it into the reflection database in October 2022. 

The fix here may involve bumping the version of `rbx_reflection_database` in cargo.toml to `0.2.5` and running a release. Not sure if there are other dependencies that would also need to get updated.

**Comment by LPGhatguy** [comment]
Thanks for filing an issue. The reflection database is pretty old and needs a new release.

In the meantime, you can set the property with the explicit property syntax to make any errors go away.

<https://rojo.space/docs/v7/project-format/#instance-property-value>

**Comment by schmatz** [comment]
Thanks @LPGhatguy for the workaround!

**Comment by sasial-dev** [comment]
Fixed in `7.3.0`, this issue can be closed.
