### ISSUE TITLE
"Cannot add an instance from a patch that has no parent" After duplicating file

### ISSUE THREAD

**Issue by ChipioIndustries** [rojo-rbx/rojo#658]
I got this error after duplicating a file in VSCode. I had just disconnected Rojo in Studio about 30 seconds before. It doesn't seem like anything actually broke as a result but I figured I'd drop it in here just in case it's helpful.
![image](https://user-images.githubusercontent.com/53354220/222596760-c2f1037a-af24-42e3-906f-d5776b1c7c61.png)

**Comment by FiercestNewt** [comment]
Can confirm, just got the same issue as soon as I created a new file.
![image](https://user-images.githubusercontent.com/90056568/230274545-f72fcbdd-323f-4eb8-a1ae-8b9a97905813.png)

**Comment by boatbomber** [comment]
Given that your repro includes disconnecting, I wonder if this is solved by #675?

**Comment by boatbomber** [comment]
I forgot to test this until now, but yes, it's been resolved. Nice!
