### ISSUE TITLE
The new Studio plugin still displays version 7.2.1

### ISSUE THREAD

**Issue by sscoville-rbx** [rojo-rbx/rojo#665]
I just pulled the `Rojo.rbxm` from the `7.3.0` release and it still displays `7.2.1`

![2023-04-24 at 2 21 PM](https://user-images.githubusercontent.com/47334847/234095295-1f7c18db-f651-405e-b56a-b79e7fa2522a.jpg)

**Comment by gagbaghdas** [comment]
Pinging here. I can't install 7.3.0 version. The website version is still 7.2.0, the attached file is 2.1.0 too

**Comment by boatbomber** [comment]
Closed by https://github.com/rojo-rbx/rojo/pull/669
