### ISSUE TITLE
The "Stop Sync" button should be visible even if its image fails to load

### ISSUE THREAD

**Issue by Ozzypig** [rojo-rbx/rojo#690]
If you are unlucky enough to be using Rojo when Roblox's asset backend goes down at just the wrong time, you may find that the ❌ button to stop syncing isn't visible as it is an image. Unlike the other text-based buttons in Rojo, this is a pretty significant usability issue. The button is still pressable in its normal location, but there is otherwise no visible indication that space is clickable.

![image](https://github.com/rojo-rbx/rojo/assets/1464027/23b5bbab-f368-4e3b-9ea3-87c6e37b5480)

If the image fails to load, some kind of backup should be used:

- the text "Stop Sync" or similar
- the &times; character
- an image texture that's available offline, such as:
  - `rbxasset://textures/ui/CloseButton.png`
  - `rbxasset://textures/ui/CloseButton_dn.png`
![image](https://github.com/rojo-rbx/rojo/assets/1464027/e3201b07-3f41-4c41-b0db-454df26ee066)

**Comment by boatbomber** [comment]
Interesting that the Rojo logo loaded but not the close button.

Is there any reliable way for us to tell if the image loaded properly? I know `ImageLabel.IsLoaded` exists but I'm uncertain about its reliability during an outage.

**Comment by kennethloeffler** [comment]
I think we could totally just use an emoji all the time, ❌ or something
