### ISSUE TITLE
Cannot rename instances

### ISSUE THREAD

**Issue by PneumaOfficial** [rojo-rbx/rojo#694]
Hello, I am attempting to name instances in my default.project.json file. I get this warning:
![image](https://github.com/rojo-rbx/rojo/assets/39502544/c91cac79-581b-497c-9f23-bdbae1a7dd1a)
This is what I'm attempting:
![image](https://github.com/rojo-rbx/rojo/assets/39502544/df771b3c-e667-438a-b8a1-9bee90b97ead)

**Comment by kennethloeffler** [comment]
Hey there, this is the intended behavior (see #413). If you want the instance's name to be `toolkit`, change the `randomuniquename` key to `toolkit`.
