### ISSUE TITLE
Expand diff of `Source` modifications in initial sync diff viewer

### ISSUE THREAD

**Issue by JohnnyMorganz** [rojo-rbx/rojo#700]
I'm liking the recent new feature to view a diff of changes before accepting the initial sync - it helps to confirm that everything is as expected.

Would it be possible to potential expand the view on `Source` changes for scripts? It is difficult to see what's changed in the following UI:

![image](https://github.com/rojo-rbx/rojo/assets/19635171/298cea6f-e08b-4ec8-a2c9-4f0644bbdee1)

It would be nice to be able to expand this (potentially even into a text-diff viewer, not sure if that's possible), so that I can confirm that the change is correct

**Comment by boatbomber** [comment]
This is something I definitely want to support. I originally made the diff view to fill a couple use cases, namely to prevent accidentally syncing the wrong place and overwriting work as well as being aware of Rojo's current sync status.
Future versions should definitely support more complex inspection like this.

**Comment by boatbomber** [comment]
I don't think there's enough room in this UI to display the information you want. It's designed to show property changes, which are generally only a handful of characters long. I think we can special case string properties like Source to have a popout button to view a full size diff window.

> not sure if that's possible
Neil Fraser, the wonderful mind behind Google Docs, created and open sourced a JS diff-patch-match utility. It was then translated to Lua by Duncan Cross. I believe that I can adapt that for Luau (respecting the license, of course) and use that for really rich semantic diffs for Rojo users.

I call dibs on first crack at this issue!

**Comment by boatbomber** [comment]
Working prototype! Long way to go though.
![image](https://github.com/rojo-rbx/rojo/assets/40185666/c8431e6f-ac15-4db7-84fe-f4ddfea0a63f)

**Comment by boatbomber** [comment]
https://github.com/rojo-rbx/rojo/pull/748
