### ISSUE TITLE
Click to select item in initial sync diff viewer

### ISSUE THREAD

**Issue by JohnnyMorganz** [rojo-rbx/rojo#707]
It would be nice if the instances in the diff viewer were clickable which would focus the selection onto that item.

For example, in the sync view below, I would like to click on "Part" to find out which part exactly it was added to
![image](https://github.com/rojo-rbx/rojo/assets/19635171/84fa6726-1932-42ff-abe8-b5a2ad8e4a1f)

**Comment by boatbomber** [comment]
What would you expect to happen if you click on a new addition that has no Instance yet?

**Comment by boatbomber** [comment]
Additionally, clicking is currently used to open the dropdown of changes. We can use right clicking for selection, perhaps.

**Comment by boatbomber** [comment]
After trying a few methods, the one I found to be the easiest to use:

Left clicking on an instance that has changes will open the dropdown, same as before. Right clicking on it will select the Instance. For an instance that has no changes to show, left or right clicking will select it.

**Comment by boatbomber** [comment]
After review, the interaction model has been redesigned as follows:

Double clicking selects the Instance, if the Instance exists. Single clicking opens the changes list, if changes exist.

Tooltips indicate which actions are available for the underlying DOM element.
