### ISSUE TITLE
Removing/Renaming a file causes patch viewer to crash

### ISSUE THREAD

**Issue by Dekkonot** [rojo-rbx/rojo#710]
When renaming a file that's tracked by Rojo, the patch viewer breaks. I'm not sure when this behavior was introduced but it was probably recently.

This can be easily reproduced:
- Create a new project using `rojo init`
- Add a folder or text file to one of the created folders
- Sync to Studio using the plugin
- Open patch viewer
- Rename the previously created file/folder
- Observe that your plugin is now locked up

If the patch viewer is not open, the rest of the plugin will continue to function but the patch viewer will no longer function.

**Comment by boatbomber** [comment]
I have determined the cause. The remove list in a patch contains either string IDs or Instances, but when writing the patch visualizers I forgot and only handled Instances.

**Comment by boatbomber** [comment]
Oh, this gets tricky. When viewing the patch that was just applied, the instanceMap will no longer have a mapping for that ID, since it was just removed.

**Comment by boatbomber** [comment]
This means that removing an instance is not visualizable in this current form. Here's what I get when removing instead of renaming.

![image](https://github.com/rojo-rbx/rojo/assets/40185666/5e6d9b14-2479-4c7e-b910-a1df9826aee0)

Renaming is just a remove and an addition.

**Comment by boatbomber** [comment]
The only way to be able to display information that has since been deleted is to store it, but I really don't want Rojo to need to store tree info on every object you have just in case you delete/rename it...

**Comment by boatbomber** [comment]
I'm going to solve this in two PRs, since the string/instance handling is one fix and the tracking post-removal is a whole other big problem

**Comment by boatbomber** [comment]
I'm going to create a second issue since these are two distinct problems.
