### ISSUE TITLE
The `rojo serve` process fails to end on M1 MacBook

### ISSUE THREAD

**Issue by vocksel** [rojo-rbx/rojo#711]
I've been encountering an issue on my MacBook where running `rojo serve`, cancelling the process with Ctrl+C, then running `rojo serve` again errors from the address still being in use.

Repro:
```
➜  starkid git:(matter) ✗ rojo --version
Rojo 7.3.0
➜  starkid git:(matter) ✗ rojo serve
Rojo server listening:
  Address: localhost
  Port:    34872

Visit http://localhost:34872/ in your browser for more information.
^C
➜  starkid git:(matter) ✗ rojo serve
Rojo server listening:
  Address: localhost
  Port:    34872

Visit http://localhost:34872/ in your browser for more information.
[ERROR rojo] Rojo crashed!
[ERROR rojo] This is probably a Rojo bug.
[ERROR rojo] 
[ERROR rojo] Please consider filing an issue: https://github.com/rojo-rbx/rojo/issues
[ERROR rojo] 
[ERROR rojo] Details: error binding to 127.0.0.1:34872: error creating server listener: Address already in use (os error 48)
[ERROR rojo] in file /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.14.26/src/server/server.rs on line 79
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
➜  starkid git:(matter) ✗ pkill rojo
➜  starkid git:(matter) ✗ rojo serve
Rojo server listening:
  Address: localhost
  Port:    34872

Visit http://localhost:34872/ in your browser for more information.
```

Note that killing the process via `pkill` seems to clear up the address, and running `rojo serve` after this point works as expected.

I first encountered this issue with the [VSCode extension](https://marketplace.visualstudio.com/items?itemName=evaera.vscode-rojo), though it looks like this is a bug in Rojo itself.

Exact specs are: 
- Model: MacBook Pro, 14-inch, 2021
- Chip: Apple M1 Pro
- OS: macOS Ventura 13.4.1

**Comment by kennethloeffler** [comment]
Hi vocksel, 

Are you running Rojo using Foreman? The symptoms here look similar to a longstanding bug in Foreman: https://github.com/Roblox/foreman/issues/45.

**Comment by vocksel** [comment]
Sounds like it, will close this out. Thanks for pointing me in the right direction
