### ISSUE TITLE
Changes that fail to apply should be indicated in the patch visualizer somehow

### ISSUE THREAD

**Issue by Dekkonot** [rojo-rbx/rojo#712]
Right now, patches can fail to apply fully. This happens e.g. when trying to sync `Lighting.Technology`.

PR #692 adds an indicator that the sync info label can be clicked to view a patch and also indicate when a change failed to apply. The patch visualization however has no indication of what change failed. I think it'd be helpful to have it be indicated somehow.

Right now, we emit a warning in the plugin when a change couldn't be made. It would be great to have a GUI visualization as well.

**Comment by boatbomber** [comment]
Work is underway!
![image](https://github.com/rojo-rbx/rojo/assets/40185666/5c6b74e7-1688-46be-b248-a58b75560db5)
