### ISSUE TITLE
Rojo should support tagging instances within partitions

### ISSUE THREAD

**Issue by Validark** [rojo-rbx/rojo#73]
It would be nice to be able to let Rojo automatically `AddTag()` if a `tag` field (string) exists within a partition.

Ideally, it would tag only LuaSourceContainer objects. If it tagged all objects, I might be able to work around that too with enough `init.lua` magic.

Another solution is the `tag` field could be a dictionary with a `name` (string) and `target` or `targetClass` (string ClassName or 'All') option. The default target option could be `all`. Other options would be the name of a class of LuaSourceContainer. I just really can't have `Folder` objects getting Tagged.

I am willing to write this myself and open a pull request if given the go-ahead and desired layout. I am not a rust programmer and know nothing about rust but I will do what I can do.

If I have to use some hacky method to accomplish what I want, it would be nice to know there is a set order in which the partitions are reconciled, like alphabetically for example.
```lua
local AlphabeticalOrder do
	local function Alphabetically(a, b)
		local typeA = type(a)
		local typeB = type(b)

		if typeA == typeB then
			if typeA == "number" then
				return a < b
			else
				return tostring(a):lower() < tostring(b):lower()
			end
		else
			return typeA < typeB
		end
	end

	function AlphabeticalOrder(Dictionary)
		--- Iteration function that iterates over a dictionary in alphabetical order
		-- function AlphabeticalOrder(Dictionary)
		-- @param table Dictionary That which will be iterated over in alphabetical order
		-- A dictionary looks like this: {Apple = true, Noodles = 5, Soup = false}
		-- Not case-sensitive
		-- @author Validark

		local Count = 0
		local Order = {}

		for Key in next, Dictionary do
			Count = Count + 1
			Order[Count] = Key
		end

		table.sort(Order, Alphabetically)

		return function(Table, Previous)
			for i = 0, Count do
				if Order[i] == Previous then
					local Key = Order[i + 1]
					return Key, Table[Key]
				end
			end

			error("invalid key to 'AlphabeticalOrder' " .. tostring(Previous))
		end, Dictionary, nil
	end
end

for i, v in AlphabeticalOrder(info.project.partitions) do
	print(i, v)
end
```

**Comment by LPGhatguy** [comment]
This seems like two different issues to me.

First, Rojo should sync partitions in a defined order. I absolutely agree here -- ideally, that would be the order that they're specified in the JSON, but I don't know if that's possible without quite a bit of work.

Second, you want Rojo to tag objects that it syncs via `CollectionService`, which has an issue here, though it's closed, at #17.

**Comment by Validark** [comment]
I want to tag it with my own tags for my own uses, not for internal Rojo use. For example:
```json
{
	"name": "Class",
	"servePort": 8000,
	"partitions": {
		"Class": {
			"path": "Class",
			"target": "ServerStorage.Repository.Packages.Classes.Class",
			"tag": "ReplicatedLibraries"
		},
		"Main": {
			"path": "ClickDetector",
			"target": "ServerScriptService.ClickDetector",
			"tag": "ServerLibraries"
		}
	}
}
```

**Comment by Validark** [comment]
I don't see this as two issues per se. The thing about ordering was an idea for a compromise that might help solve this issue depending upon which route is taken.

**Comment by LPGhatguy** [comment]
After thinking about it for a few days, instance tagging is definitely a good idea in some form.

I'm not sure if it's very useful to tag all instances of a partition or the partition itself except to work around Rojo, but I do think that having tags in `.model.json` files would be great.

**Comment by LPGhatguy** [comment]
Closing this in favor of #473 for the reasons laid out there.
