### ISSUE TITLE
`Sound.RollOffMinDistance` and `Sound.RollOffMaxDistance` not included in build

### ISSUE THREAD

**Issue by guidojw** [rojo-rbx/rojo#742]
Similar to https://github.com/rojo-rbx/rojo/issues/655 (I have the issue with `Lighting.ClockTime` too), `rojo build` does not include the in my `model.json` files configured `Sound.RollOffMinDistance` and `Sound.RollOffMaxDistance` values anymore. 
~~This started occurring in v7.3.0, in v7.2.1 my published experience would still include these properties correctly.~~

`model.json`:
```json
{
  "className": "Sound",
  "properties": {
    "RollOffMaxDistance": 1000,
    "RollOffMinDistance": 50,
    "SoundId": "rbxassetid://...",
    "Volume": 1
  }
}
```

Figured this out in courtesy of the amazing patch diff view:
![image](https://github.com/rojo-rbx/rojo/assets/35309288/aa9043ae-fdd2-4777-9240-23ee175b84ba)
(This is after publishing the rbxl file built by `rojo build`)

**Comment by Dekkonot** [comment]
I'm not able to replicate this issue. When building the model file you attached, `rojo build` includes the properties in both 7.2.1 and 7.3.0, which means nothing has changed. Are you absolutely sure that you were actually setting these properties correctly before?

After checking, it seems that the serialization of these properties hasn't changed. Neither property serializes or deserializes and it appears as though they never have, as least if [RobloxAPI's ref site](https://robloxapi.github.io/ref/class/Sound.html#member-RollOffMinDistance) is to be believed.

You can verify this yourself by just inserting a `Sound`, settings its `RollOfMaxDistance` and `RollOffMinDistance`, then saving it as an XML model file and opening it in a text editor. Neither of them will save. If you insert a model with those two properties set, they also don't load.

We *can* fix this in `rbx_dom` and we will, but I don't think this is a new problem.

**Comment by Dekkonot** [comment]
With regards to `ClockTime`, a work around right now is to just use `TimeOfDay` instead, but we're aware of that one and will also fix it. :-)
