### ISSUE TITLE
Add StudioTheme Support (For custom Roblox Studio themes)

### ISSUE THREAD

**Issue by RyanLua** [rojo-rbx/rojo#754]
Currently as it stands, Rojo uses preset colors for its light and dark theme which cause inconsistencies if you are using a custom Roblox Studio theme.

![image](https://github.com/rojo-rbx/rojo/assets/80087248/3aea528d-7396-4e11-9926-90879be7645a)

My proposal is [StudioTheme's GetColor method](https://create.roblox.com/docs/reference/engine/classes/StudioTheme#GetColor) so the color is in consistent with Roblox Studio's theme.

Example of my open-source plugin, [Signs](https://github.com/RyanLua/Signs) (which uses StudioTheme):
![image](https://github.com/rojo-rbx/rojo/assets/80087248/06727fd9-eec4-4d02-bed4-5cdc68552d00)

**Comment by RyanLua** [comment]
> Are you using [Custom Theme Patcher](https://github.com/rbxrootx/Roblox-Studio-CustomTheme-Patcher) or another method of getting a custom theme? Looking to replicate this for testing.

I am using the Custom Theme Patcher you linked.

**Comment by Zenthial** [comment]
Seems to crash my studio every time I try it. Still gonna go ahead and make this change based on your Signs impl
