### ISSUE TITLE
Rojo will not sync Script source, even after plugin says its synced

### ISSUE THREAD

**Issue by LokiGitHubb** [rojo-rbx/rojo#762]
I have a script ,for a tank. i made edits to it, and connected the server. The rojo plugin said that the script source was modified when it was not.
The end of script in vscode:
![image](https://github.com/rojo-rbx/rojo/assets/140853603/79ef4a23-13a0-4193-b0aa-d57b52fd7530)

my rojo plug in when connecting:
![image](https://github.com/rojo-rbx/rojo/assets/140853603/478181cb-0f83-4305-a47c-7dbc319446b1)

after i pressed accept and looked at the script source in the roblox script editor:
![image](https://github.com/rojo-rbx/rojo/assets/140853603/da1812f0-9eef-4ab7-a983-cc99a5dadaee)

Is this a bug?

Edit: Heres the scripts metadata if that will help:
![image](https://github.com/rojo-rbx/rojo/assets/140853603/b8db0f77-f08d-4718-917c-9abb883512e9)

**Comment by boatbomber** [comment]
Does this happen in the latest version of the plugin? I notice you're on an outdated one. Try using latest from here: https://www.roblox.com/library/13916111004/Rojo

**Comment by LokiGitHubb** [comment]
i got it already:
![image](https://github.com/rojo-rbx/rojo/assets/140853603/66eddaa9-24a8-49f6-90f7-9b9a474321a1)

**Comment by LokiGitHubb** [comment]
I am going to regenerate the project with rbxl to rojo il be back

Edit: it still dosnt work

**Comment by LokiGitHubb** [comment]
i found out rojo was adding a folder named seat instead of using the existing seat:

Heres my vscode explorer:
![image](https://github.com/rojo-rbx/rojo/assets/140853603/e240d649-bde7-4d49-bb13-02ba505dd181)

here are the 2 meta files:
Top:
![image](https://github.com/rojo-rbx/rojo/assets/140853603/6460268f-a30f-412f-b651-3e4ed4ac07e6)

Bottom:
![image](https://github.com/rojo-rbx/rojo/assets/140853603/39163fd1-6e4b-4f4f-9e53-b2a0d5bb611a)

**Comment by Dekkonot** [comment]
That is expected behavior when ignoring unknown descendants; Rojo will assume anything not in the tree is meant to be there and won't take ownership of the existing tree even if it looks right.

**Comment by LokiGitHubb** [comment]
Solved! just the meta file not named properly
