### ISSUE TITLE
Rojo should remove Carriage Returns when syncing on Windows

### ISSUE THREAD

**Issue by ambergamefam** [rojo-rbx/rojo#776]
Today when I tried to sync into my project's team create place, I encountered an interesting issue—Rojo wants to modify every single source file in the game.

![image](https://github.com/rojo-rbx/rojo/assets/122126644/6b1a4968-6669-4ffa-8f86-9f6b08eabae1)

I was freaking out a bit 😅, but as it turns out, when you sync a Rojo project with Windows, it uses CRLF characters for new lines. I was syncing over a team create place on my Macbook over my coworker's changes earlier.

I think Rojo should always convert CRLF to LF when syncing, or at very least omit these changes in the sync preview. This is because on Roblox's built-in script editor, hitting "Enter" on any device always creates a Line Feed with no Carriage Return character. This is also reflected in the default ModuleScript:
```lua
local module = {}

return module

```

As it turns out, even when *pasting* code with carriage returns into roblox's script editor, the carriage returns are removed. So it seems that the only possible way for a carriage return to end up in a roblox script is by directly modifying the Source property of the script (i.e. syncing via Rojo).

Because Roblox standardizes LF in their own script editor, Rojo should also convert CRLF to LF. On windows, git can be configured with the `core.autocrlf` value, which always uses CRLF locally, and LF on the git repository itself. VS Code has CRLF enabled by default for new files on windows as well, so even if a git repo uses Line Feeds, it will be converted to CRLF on windows.

I actually looked through some free models, and you can easily identify which ones were synced using a Rojo codebase by searching for a "\13\10" character sequence in the script Source properties. When copying/pasting the code in rojo-synced code to another module, it gets sanitized back to LF.

**Comment by Dekkonot** [comment]
That's unexpected behavior on Roblox's end, though I guess good for them.

A glance at the middleware we use for syncing scripts indicates we don't do any transformations on their source. I'm inclined to not start, since it's a dangerous game to start editing the source of things as they're synced.

Have you considered setting up a `.editorconfig` file for your workspace instead? It's what I would recommend for multi-OS teams.

**Comment by ambergamefam** [comment]
Will look into a `.editorconfig` file, thanks!

If this isn't something that should be supported by Rojo, do you think omitting CRLF -> LF conversions from the sync preview would be viable just for UX purposes? That way, it's easier to overview the actual things that have changed in the repository when syncing changes, rather than seeing that every single file has changed and getting a scare like I did today 😄

**Comment by boatbomber** [comment]
What does your git diffs look like, if people are committing various line endings? Isn't this an issue outside of Rojo too?

I'd be open to an "ignore whitespace" toggle as that's a common feature for diff view in general.

**Comment by ambergamefam** [comment]
> What do your git diffs look like, if people are committing various line endings? Isn't this an issue outside of Rojo too?
> 
> I'd be open to an "ignore whitespace" toggle as that's a common feature for diff view in general.

No, this is just an issue with Rojo. On windows, git by default has `core.autocrlf` configured to be true, which essentially always translates the line endings to LF when pushing to the repository, and translates back to CRLF when pulling from the repository. So git diffs look normal

I figured since it's standard to translate this in git, and even in Roblox Studio's editor itself, it would make sense for Rojo to also translate line endings. I personally don't see the downsides of that, but really the only usability issue here is that the sync preview is showing changes on every single line of source code when syncing between operating systems, which makes it impossible to see the _actual_ changes that are going on.

**Comment by kennethloeffler** [comment]
I think it makes a lot of sense for Rojo to normalize line endings to LF, at *least* for script sources, and especially after #817. It should be mostly invisible - realistically, the difference will only be noticeable when checking place or model files containing scripts generated by Rojo into source control.

Additionally, `ScriptEditorService:UpdateSourceAsync`, which the Rojo plugin uses to set script `Source` properties as of 7.4.0-rc3, now normalizes to LF. When script files have CRLF endings, their contents are placed into snapshots as-is, which then causes the Rojo plugin to attempt pointless changes for every connect, and causes serve and build results to differ. To avoid these behaviors, Rojo must normalize script sources at some point before emitting snapshots.

This are similar concerns for any kind of textual source file that has its contents snapshotted as-is. Right now, the only other such file type is `.txt`, but `StringValue.Value` doesn't have any restrictions on its value (it accepts any byte sequence, as far as I know). So, this case only affects multi-OS teams (*for now...*), but it could still be plenty annoying!

We could address these issues by normalizing to LF endings in every snapshot middleware that emits content that is read directly from source files (just `.txt` and `.lua`, for now). I think it'd be appropriate to add a `fs::read_to_string` equivalent to memofs that also normalizes to LF, so any middleware that needs to do this can share. 

@Dekkonot, I think line endings probably also impact tree diffing and syncback over on the Uplift Games fork. When a diff compares instances instigated by a textual source file, the two sides may only differ by line endings, but the result will still indicate changes. When syncback writes to a textual source, it may alter line endings. I ran into similar issues on an earlier two-way sync prototype.

While it's possible for a user to work around all this by enforcing LF endings through other means, I still think it's rather poor usability, and I don't think line ending awareness is very dangerous or adds too much complexity

**Comment by Dekkonot** [comment]
I think having normalization live in memofs is... fine. I'm not in love with adding hidden behavior to it, but we're realistically the only consumer anyway so it's whatever since we'll be aware of it and it's desirable for us. I'm not too worried about syncback since it'll sync back either way, it just might result in the program doing some extra work.

I've had this on my mind off and on since August when I initially commented on it, and I think I've come around to fixing it on our end. It's not the end of the world either way, but it's probably a good idea to keep it in line with what Roblox does.
