### ISSUE TITLE
Couldn't install Rojo with Aftman: Error: Command failed: aftman add rojo-rbx/rojo [INFO aftman::tool_storage] Installing tool: rojo-rbx/rojo Aftman error: Failed to create Aftman alias Caused by: 0: failed to copy file from C:\Users\xiiic\.aftman\bin\aftman.exe to C:\Users\xiiic\.aftman\bin\rojo.exe 1: The process cannot access the file because it is being used by another process. (os error 32)

### ISSUE THREAD

**Issue by HydraEH30** [rojo-rbx/rojo#778]
like bro. and plus i have no idea what is aftman is...

**Comment by Dekkonot** [comment]
Not an issue with Rojo, Aftman is a separate program that the VSCode extension suggests if you don't have Rojo installed. Ask in the Open Source Server linked on [rojo.space](https://rojo.space/) or on [Aftman's repo](https://github.com/LPGhatguy/aftman).
