### ISSUE TITLE
rojo roblox plugin doesn't display the version correctly

### ISSUE THREAD

**Issue by TheFortex** [rojo-rbx/rojo#780]
~~my rojo is stuck on version 7.2.1 and I can't upgrade to v7.3.0. I tried changing the tool in my aftman file from `rojo = "rojo-rbx/rojo@7.2.1"` to `rojo = "rojo-rbx/rojo@7.3.0"` but that just made it say I have version 7.3.0 despite me not getting any of the new features or the roblox plugin updating to that plugin as well. I'm not sure if the version is not released yet and that's why it's not updating automatically but I'm using a rojo explorer plugin and it started requiring me to use rojo 7.3.0 but I just can't do it.~~

~~any help?~~

**Comment by Cool-Bu1lder** [comment]
have you run `aftman install`, then `rojo init`?

**Comment by boatbomber** [comment]
Known issue in the current release, and has already been resolved on master. Thanks for reporting though!
