### ISSUE TITLE
Rojo doesn't clone the font of UI

### ISSUE THREAD

**Issue by vitu0089** [rojo-rbx/rojo#799]
The title describes it all, I've been looking around online for a fix for this issue, but it keeps sending me to the wrong sites with the wrong answers, so I'm assuming this is a bug.

**Comment by Dekkonot** [comment]
Can you confirm whether this happens in [Rojo `7.4.0-rc2`](https://github.com/rojo-rbx/rojo/releases/tag/v7.4.0-rc2)? It has a more up to date backend implementation so it may solve your issue.

**Comment by NotNikko** [comment]
I've had a similar issue happening. It'll change all the fonts from whatever they are for example Poppins, to Arial (Legacy).

**Comment by boatbomber** [comment]
Can anyone confirm if this happens with the latest [release](https://github.com/rojo-rbx/rojo/releases/tag/v7.4.0)?
