### ISSUE TITLE
SecurityCapabilities is not implemented (Model support)

### ISSUE THREAD

**Issue by PeccNeck** [rojo-rbx/rojo#802]
# The issue

Truthfully, I didn't realize this was a rbx\_dom\_lua issue until after writing most of this, but as I've already written it here _and_ this directly affects the Rojo workflow, I'm still going to put it here.

I'm not sure when this became a thing, but Roblox model files (both `.rbxmx` and the binary `.rbxm`) appear to attach a `SecurityCapabilities` property named "Capabilities" to every Instance within the model now. This is neat and all (if not confusing due to the lack of documentation?), but rbx\_dom\_lua and, by extension, Rojo, _really_ do not like to play nice with it.

The Rojo studio plugin will _completely_ error out and require a Studio restart on first sync, and will disconnect if already synced and refuse to reconnect on any subsequent attempts until the "issue" is "resolved" (see below).

# The stack

<details><summary>First sync (hard-error)

`user_RojoManagedPlugin.rbxm.Rojo.Packages.RbxDom.EncodedValue:417: SecurityCapabilities is not implemented`
</summary>

```
  user_RojoManagedPlugin.rbxm.Rojo.Packages.RbxDom.EncodedValue:417: SecurityCapabilities is not implemented
  Stack Begin
  Script 'user_RojoManagedPlugin.rbxm.Rojo.Packages.RbxDom.EncodedValue', Line 417 - function fromPod
  Script 'user_RojoManagedPlugin.rbxm.Rojo.Packages.RbxDom.EncodedValue', Line 513 - function decode
  Script 'user_RojoManagedPlugin.rbxm.Rojo.Plugin.Reconciler.decodeValue', Line 30 - function decodeValue
  Script 'user_RojoManagedPlugin.rbxm.Rojo.Plugin.PatchTree', Line 358 - function build
  Script 'user_RojoManagedPlugin.rbxm.Rojo.Plugin.App.Components.PatchVisualizer', Line 46 - function render
  Script 'user_RojoManagedPlugin.rbxm.Rojo.Packages.Roact.Component', Line 335 - function __mount
  Script 'user_RojoManagedPlugin.rbxm.Rojo.Packages.Roact.createReconciler', Line 408 - function mountVirtualNode
  Script 'user_RojoManagedPlugin.rbxm.Rojo.Packages.Roact.createReconciler', Line 115 - function updateChildren
  Script 'user_RojoManagedPlugin.rbxm.Rojo.Packages.Roact.createReconciler', Line 144 - function updateVirtualNodeWithChildren
  Script 'user_RojoManagedPlugin.rbxm.Rojo.Packages.Roact.createReconciler', Line 368 - function mountFragmentVirtualNode
  Script 'user_RojoManagedPlugin.rbxm.Rojo.Packages.Roact.createReconciler', Line 412 - function mountVirtualNode
  Script 'user_RojoManagedPlugin.rbxm.Rojo.Packages.Roact.createReconciler', Line 115 - function updateChildren
  Script 'user_RojoManagedPlugin.rbxm.Rojo.Packages.Roact.createReconciler', Line 149 - function updateVirtualNodeWithRenderResult
  Script 'user_RojoManagedPlugin.rbxm.Rojo.Packages.Roact.Component', Line 338 - function __mount
  Script 'user_RojoManagedPlugin.rbxm.Rojo.Packages.Roact.createReconciler', Line 408 - function mountVirtualNode
  Script 'user_RojoManagedPlugin.rbxm.Rojo.Packages.Roact.createReconciler', Line 115 - function updateChildren
  Script 'user_RojoManagedPlugin.rbxm.Rojo.Packages.Roact.createReconciler', Line 149 - function updateVirtualNodeWithRenderResult
  Script 'user_RojoManagedPlugin.rbxm.Rojo.Packages.Roact.Component', Line 338 - function __mount
  Script 'user_RojoManagedPlugin.rbxm.Rojo.Packages.Roact.createReconciler', Line 408 - function mountVirtualNode
  Script 'user_RojoManagedPlugin.rbxm.Rojo.Packages.Roact.createReconciler', Line 115 - function updateChildren
  Script 'user_RojoManagedPlugin.rbxm.Rojo.Packages.Roact.createReconciler', Line 144 - function updateVirtualNodeWithChildren
  Script 'user_RojoManagedPlugin.rbxm.Rojo.Packages.Roact.RobloxRenderer', Line 214 - function mountHostNode
  Script 'user_RojoManagedPlugin.rbxm.Rojo.Packages.Roact.createReconciler', Line 404 - function mountVirtualNode
  Script 'user_RojoManagedPlugin.rbxm.Rojo.Packages.Roact.createReconciler', Line 115 - function updateChildren
  Script 'user_RojoManagedPlugin.rbxm.Rojo.Packages.Roact.createReconciler', Line 149 - function updateVirtualNodeWithRenderResult
  Script 'user_RojoManagedPlugin.rbxm.Rojo.Packages.Roact.Component', Line 501 - function __resolveUpdate
  Script 'user_RojoManagedPlugin.rbxm.Rojo.Packages.Roact.Component', Line 439 - function __update
  Script 'user_RojoManagedPlugin.rbxm.Rojo.Packages.Roact.Component', Line 162 - function setState
  Script 'user_RojoManagedPlugin.rbxm.Rojo.Plugin.App.Page', Line 27
  Script 'user_RojoManagedPlugin.rbxm.Rojo.Packages.Flipper.Signal', Line 37 - function fire
  Script 'user_RojoManagedPlugin.rbxm.Rojo.Packages.Flipper.SingleMotor', Line 35 - function step
  Script 'user_RojoManagedPlugin.rbxm.Rojo.Packages.Flipper.BaseMotor', Line 33
  Stack End
```

</details>

<details><summary>Subsequent sync attempts

`[Rojo-Warn] Precommit hook errored: user_RojoManagedPlugin.rbxm.Rojo.Packages.RbxDom.EncodedValue:417: SecurityCapabilities is not implemented`
`[Rojo-Warn] Disconnected from an error: -- Promise.Error(ExecutionError) --`
</summary>

```
  [Rojo-Warn] Precommit hook errored: user_RojoManagedPlugin.rbxm.Rojo.Packages.RbxDom.EncodedValue:417: SecurityCapabilities is not implemented
  [Rojo-Warn] Disconnected from an error: -- Promise.Error(ExecutionError) --
[Rojo-Warn] 
[Rojo-Warn] The Promise at:
[Rojo-Warn] 
[Rojo-Warn] user_RojoManagedPlugin.rbxm.Rojo.Plugin.ServeSession:142 function start
[Rojo-Warn] user_RojoManagedPlugin.rbxm.Rojo.Plugin.App:537 function startSession
[Rojo-Warn] user_RojoManagedPlugin.rbxm.Rojo.Plugin.App:618 function onConnect
[Rojo-Warn] user_RojoManagedPlugin.rbxm.Rojo.Packages.Roact.SingleEventManager:80
[Rojo-Warn] 
[Rojo-Warn] ...Rejected because it was chained to the following Promise, which encountered an error:
[Rojo-Warn] 
[Rojo-Warn] 
[Rojo-Warn] The Promise at:
[Rojo-Warn] 
[Rojo-Warn] user_RojoManagedPlugin.rbxm.Rojo.Plugin.ServeSession:145
[Rojo-Warn] user_RojoManagedPlugin.rbxm.Rojo.Packages.Promise:172 function runExecutor
[Rojo-Warn] user_RojoManagedPlugin.rbxm.Rojo.Packages.Promise:181
[Rojo-Warn] 
[Rojo-Warn] ...Rejected because it was chained to the following Promise, which encountered an error:
[Rojo-Warn] 
[Rojo-Warn] user_RojoManagedPlugin.rbxm.Rojo.Packages.RbxDom.EncodedValue:417: SecurityCapabilities is not implemented
[Rojo-Warn] user_RojoManagedPlugin.rbxm.Rojo.Packages.RbxDom.EncodedValue:417 function fromPod
[Rojo-Warn] user_RojoManagedPlugin.rbxm.Rojo.Packages.RbxDom.EncodedValue:513 function decode
[Rojo-Warn] user_RojoManagedPlugin.rbxm.Rojo.Plugin.Reconciler.decodeValue:30 function decodeValue
[Rojo-Warn] user_RojoManagedPlugin.rbxm.Rojo.Plugin.Reconciler.reify:83 function reifyInner
[Rojo-Warn] user_RojoManagedPlugin.rbxm.Rojo.Plugin.Reconciler.reify:24 function reify
[Rojo-Warn] user_RojoManagedPlugin.rbxm.Rojo.Plugin.Reconciler.applyPatch:68 function applyPatch
[Rojo-Warn] user_RojoManagedPlugin.rbxm.Rojo.Plugin.Reconciler:67 function applyPatch
[Rojo-Warn] user_RojoManagedPlugin.rbxm.Rojo.Plugin.ServeSession:309
[Rojo-Warn] user_RojoManagedPlugin.rbxm.Rojo.Packages.Promise:172 function runExecutor
[Rojo-Warn] user_RojoManagedPlugin.rbxm.Rojo.Packages.Promise:181
[Rojo-Warn] 
[Rojo-Warn] Promise created at:
[Rojo-Warn] 
[Rojo-Warn] user_RojoManagedPlugin.rbxm.Rojo.Plugin.ServeSession:299
[Rojo-Warn] user_RojoManagedPlugin.rbxm.Rojo.Packages.Promise:172 function runExecutor
[Rojo-Warn] user_RojoManagedPlugin.rbxm.Rojo.Packages.Promise:299
[Rojo-Warn] 
```

</details>

## The "temporary fix"
Technically, this can be resolved by manually importing the models, or by commenting out these unsupported values, but for obvious reasons these are less than ideal; both put unnecessary liability on developers, and with the latter, it's not only impossible with `.rbxm`, but it also causes a different issue of failure to apply changes to rear its ugly head (which is oddly resolved by disconnecting and then reconnecting?)

## Other comments
Ideally, best resolution would be proper implementation in rbx\_dom\_lua, but until that happens, it would at least be nice to not have Rojo entirely crash when trying to import a model just because of _one unsupported property_. This only happens when trying to import brand new instances, too; it's still able to sync if the Instances are already present in-game.

And unrelated, but I am somewhat curious on what this property even is? As I mentioned, documentation seems to be entirely nonexistent, and it doesn't seem to be set to anything besides 0. I'd love to hear a surface-level explanation if it's ever documented.

**Comment by Dekkonot** [comment]
> Ideally, best resolution would be proper implementation in rbx_dom_lua, but until that happens, it would at least be nice to not have Rojo entirely crash when trying to import a model just because of one unsupported property.

What actually needs to happen is for us to distinguish between unknown and unimplemented datatypes in rbx_dom_lua, ha ha. This is my fault because I added the error without thinking too much about what the consequence was for Rojo; my intention was to communicate that the data type didn't have a codec, but that's not a good way to do so. We should probably not be passing unscriptable properties to Rojo's plugin, but that's not an excuse and going forward I'll do a better job.

Ken has fixed it in rbx_dom_lua, and it'll make its way over here soon. We'll make a new release candidate shortly after it does.

> And unrelated, but I am somewhat curious on what this property even is? As I mentioned, documentation seems to be entirely nonexistent, and it doesn't seem to be set to anything besides 0. I'd love to hear a surface-level explanation if it's ever documented.

We know relatively little about it, but from what I was told, it's eventually going to be for permissions for things like plugins and free models to prevent abusive behavior. I doubt Roblox will ever release official documentation but we'll try to document it eventually once we have some more ideas as to what the permissions are (right now they're zeroed out by Studio, so they don't do anything).

**Comment by kennethloeffler** [comment]
> We should probably not be passing unscriptable properties to Rojo's plugin, but that's not an excuse and going forward I'll do a better job.

I don't think scriptability has much to do with this. The stack trace shows that the cause of this this error was the patch visualizer attempting to decode a `SecurityCapabilities` in the initial patch. While not sending the property at all would have prevented this from happening, Rojo server has always sent unscriptable properties, and I don't think it's a bad thing... it allows the plugin to know whether it is unable to set a desired property, and to surface this information to the user. 

> [...] communicate that the data type didn't have a codec
I think absence of a coder/decoder is enough here, maybe we could just add another error variant to `decodeValue` for this case?
