### ISSUE TITLE
[Rojo-Warn] Disconnected from an error: The parent property of Workspace and Run Service is locked

### ISSUE THREAD

**Issue by MasterXertz** [rojo-rbx/rojo#820]
Every time I build my project, I get the following error in Roblox Studio:
![image](https://github.com/rojo-rbx/rojo/assets/21991416/79d4ee8a-1e90-4a95-b35b-a34fc70e604f)

I also get this error in Visual Studio Code when building my project which I know has other issues open for it atm:
![image](https://github.com/rojo-rbx/rojo/assets/21991416/bc9b3373-5714-4681-a4ae-0f79b0e2f31f)

I am on a MacOS Sonoma 14.1, Apple M1 Max, 16" Macbook Pro, 32 GB Ram.

Rojo version:  UpliftGames__rojo-7.3.0-uplift.12.pre.4

These errors are very frustrating as I can't sync VSCode with Roblox Studio therefore making it difficult to test and debug my code efficiently without having to rebuild every time I make changes and come across another error. 

I'm hoping someone can guide me in the right direction to solve this :) Thank you in advance.

**Comment by Dekkonot** [comment]
First thing's first, we don't provide support for forked versions of the program! In the future, test on the latest release (7.4.0-rc3 is stable despite being a RC) and then report.

Secondly, this is a problem with your project. You'll want to make sure you have RunService parented to the DataModel in your project file.

**Comment by MasterXertz** [comment]
@Dekkonot Oh, good to know, thank you for clarifying on both items. Very much appreciated.
