### ISSUE TITLE
Some directories are locked while being watched by Rojo

### ISSUE THREAD

**Issue by iimurpyh** [rojo-rbx/rojo#828]
I am unable to delete or move some directories in Explorer while Rojo is watching them.
If a folder is synced (i.e. it is added to the sourcemap) and contains another folder, attempting to modify it gives me a permissions error.
I have permission to edit these files, so I assume the error is because of a folder getting locked.
I am on Windows 10 release 22H2 using Rojo version 7.4.0-rc3.

In this video I create a directory called `a` inside `src/Server` and create a directory inside `a` called `b`. Once `rojo serve` is ran, trying to delete or move `a` gives me a permissions error.
Trying to delete `Server` itself also causes an error, but deleting `b` does not because it contains no other directories. If I make a folder in `src` with another folder in it, I can delete that fine because it isn't added to the sourcemap.
(This is just what I have noticed, I might be wrong about the exact conditions.)

https://github.com/rojo-rbx/rojo/assets/51100244/492854b0-9173-408b-9ec8-8f5818cb6ddb

**Comment by Dekkonot** [comment]
We believe this was resolved in a recent change we made to our file watcher, but I'll leave this open until we cut a release with it just to make sure.

**Comment by boatbomber** [comment]
We've cut a [release](https://github.com/rojo-rbx/rojo/releases/tag/v7.4.0), so this can be closed.
