### ISSUE TITLE
Rojo crashes when I try to connect.

### ISSUE THREAD

**Issue by izesw** [rojo-rbx/rojo#852]
Rojo crashes whenever I try to press the connect button from the roblox plugin. It gives me the error message "Details: called `Result::unwrap()` on an `Err` value: Os { code: 5, kind: PermissionDenied, message: "Access is denied." }"

**Comment by Dekkonot** [comment]
Just to clarify: are you using the latest version of Rojo (7.4) and do you have two way sync enabled in the settings?
