### ISSUE TITLE
*.meta.json doesn't enforce ignoreUknownInstances

### ISSUE THREAD

**Issue by Loomiquu** [rojo-rbx/rojo#853]
As stated in the title, using meta files doesn't enforce the ignoreUknownInstances flag and proceeds to remove uknown instances

![image](https://github.com/rojo-rbx/rojo/assets/107811831/eb635147-62ab-492f-aa57-705ed19344ca)
![image](https://github.com/rojo-rbx/rojo/assets/107811831/94b45616-a094-4e44-a223-2ad741e04b98)

**Comment by kennethloeffler** [comment]
You have a typo. You've written `ignoreUknownInstances`, but the correct spelling is `ignoreUnknownInstances`.

Don't worry, it can happen to the best of us! 😄
