### ISSUE TITLE
The "rojo" executable remains open after closing VS Code.

### ISSUE THREAD

**Issue by SeesilSylavin** [rojo-rbx/rojo#877]
I've encountered an issue where the "rojo" executable remains open after syncing a project, preventing me from making changes to the project folder.

**To Reproduce:**
1. Open a project.
2. Start syncing.
3. While syncing, close VS Code.
4. Observe that the "rojo" executable remains open.

This issue only occurs when closing VS Code while syncing via the extension. It doesn't happen when syncing via the command line.
I'm using the latest versions of both the extension and Rojo.

**Comment by Dekkonot** [comment]
Do you have the Luau LSP extension installed in VSCode?

If so, this is an issue with the LSP.

**Comment by SeesilSylavin** [comment]
Ah, I see. I tried again and the problem was gone. Sorry about that!
