### ISSUE TITLE
Packages built with Rojo have script differences even if they are identical

### ISSUE THREAD

**Issue by Helloburp** [rojo-rbx/rojo#878]
Hiya, I'm using Rojo to build packages for my game, but I've noticed that when bringing them to Roblox and viewing script changes, every line of each script (except for the last line) has changes.

This happens whether:
- I am comparing a rojo-built .rbxm to a published package that was created in Studio, OR
- I am comparing a rojo-built .rbxm to a published package that I built from rojo.

It's not a huge issue, but is inconvenient for tracking changes for version control in my non-rojo projects.

Example of the script comparison:
![image](https://github.com/rojo-rbx/rojo/assets/25129751/cddb5b2d-7419-480a-a934-a71a88e12caa)

**Comment by kennethloeffler** [comment]
This seems related to rojo-rbx/rojo#776, which we've recently closed out and will ship in Rojo 7.4.1 (hopefully today!). Once we ship Rojo 7.4.1, we'll check back here to ensure your issue is resolved.

**Comment by kennethloeffler** [comment]
@Helloburp alright, we've just published [Rojo 7.4.1](https://github.com/rojo-rbx/rojo/releases/tag/v7.4.1). Can you try out this version and see if you're still experiencing this problem?

**Comment by Helloburp** [comment]
> @Helloburp alright, we've just published [Rojo 7.4.1](https://github.com/rojo-rbx/rojo/releases/tag/v7.4.1). Can you try out this version and see if you're still experiencing this problem?

Looks like that fixed it! Thank you.
