### ISSUE TITLE
Rojo doesn't apply font type from .rbmx files

### ISSUE THREAD

**Issue by vitu0089** [rojo-rbx/rojo#879]
When saving UI for thr game, rojo will import everything in except for the font type, which we have to apply afterwards. It's a huge hazzle, and nothing shows up when I search for it. The font used was "Gotham"

**Comment by Dekkonot** [comment]
Can you confirm you're using either version 7.4 or 7.4.1?

**Comment by vitu0089** [comment]
![image](https://github.com/rojo-rbx/rojo/assets/86110418/430fdf93-d7ec-40bb-80fc-61931254a54a)
![image](https://github.com/rojo-rbx/rojo/assets/86110418/99d7c1c3-9668-4032-a701-26ad0d1cc221)

Not sure.

**Comment by Dekkonot** [comment]
In Roblox studio, what version does the extension display?

**Comment by vitu0089** [comment]
![image](https://github.com/rojo-rbx/rojo/assets/86110418/b46c7af9-3592-43c5-85cb-817a283df644)
![image](https://github.com/rojo-rbx/rojo/assets/86110418/ee18a7c1-f28a-45d2-8834-1b7ded7a452d)
![image](https://github.com/rojo-rbx/rojo/assets/86110418/9986da52-247b-4ac1-87bf-fc5c190207ac)

**Comment by vitu0089** [comment]
When looking it up in the toolbox to see if you've got a new version, it shows this
![image](https://github.com/rojo-rbx/rojo/assets/86110418/b31e353a-fc47-4316-b76f-617be763e1dc)

**Comment by vitu0089** [comment]
Awesome, why doesn't it show up in the toolbox?

**Comment by vitu0089** [comment]
Fair enough, I believe I've only got one more question. Will the updated roblox client work with the VSCode server?

**Comment by Dekkonot** [comment]
You'll have to check what version of Rojo's server you have installed. If it's the most recent version, it will he fine.

This is separate from the Rojo extension in VSCode, and I'm not sure what the best way for you to check is.

**Comment by vitu0089** [comment]
Perfect, thank you very much :)
