### ISSUE TITLE
`rojo sourcemap` occasionally outputs invalid JSON

### ISSUE THREAD

**Issue by ffrostfall** [rojo-rbx/rojo#888]
Occasionally when using Rojo, it will output invalid JSON such as the following: https://i.imgur.com/zLURlf5.png 
![image](https://github.com/rojo-rbx/rojo/assets/80861876/72e81d21-82f4-4674-9bfa-f0504018e26d)
![image](https://github.com/rojo-rbx/rojo/assets/80861876/1fcda75e-df73-48e5-b000-8ab2334e0631)

---

This seems to only happen in watch mode. Regenerating the sourcemap manually always seemingly fixes it

**Comment by kennethloeffler** [comment]
Can you also include a zip of the project where you've run into this problem, your operating system, and Rojo version?

**Comment by kennethloeffler** [comment]
Wasn't able to repro, and I think this is probably due to a problem in the Luau Language Server
