### ISSUE TITLE
Rojo breaks outbound studio Roblox API requests

### ISSUE THREAD

**Issue by NoSharp** [rojo-rbx/rojo#892]
# Description:
After connecting to a project with Rojo (7.4.0-Boatly)
Builtin API requests start failing in the studio.

(table offsets redacted)
```
  23:32:54.540  Failed builtin_GameSettings.rbxm.GameSettings.Pages.PermissionsPage.Controllers.GamePermissionsController:138: HttpResponse = { responseTimeMs : 164.4284725189209, responseCode : 400, responseBody : { errors : table: 0x0 }, requestOptions : { Url : https://develop.roblox.com/v1/universes/16736583703, Method : GET } }  -  Edit
  23:32:55.573  Failed builtin_GameSettings.rbxm.GameSettings.Pages.MonetizationPage.Controllers.MonetizationController:155: HttpResponse = { responseTimeMs : 166.5041446685791, responseCode : 400, responseBody : { errors : table: 0x0 }, requestOptions : { Url : https://develop.roblox.com/v1/universes/16736583703/configuration/vip-servers, Method : GET } }  -  Edit
```

Datastores also start failing.
```
DataStoreService: N/A: HTTP 404 (Not Found) API: UpdateAsync, Data Store: PlayerData  -  Studio
  23:32:46.804  [ProfileService]: DataStore API error [Store:"PlayerData";Key:"PLAYER_1437722989"] - "HTTP 404 (Not Found)"  -  Server
```

This seems to be an issue in Rojo versions later than 5. I was able to test with the Rojo 5 Studio plugin and this didn't happen.

# Reproduction:
Create a Rojo project, connect your project to the plugin, and your api access will start failing.

**Comment by kennethloeffler** [comment]
Are you able to reproduce this with normal, mainline Rojo (not boatly)? Rojo boatly is a separate project.

Assuming you can - using your reproduction steps, I can't reproduce this behavior on Rojo 7.4.0 or Rojo 7.4.1 on macOS or Windows with the latest Roblox Studio. Can you provide some more information on what your setup is?

**Comment by NoSharp** [comment]
Thanks for your response,
Yes I was able to reproduce this without boatly and it's been a longstanding (around 3 month) issue for me with Rojo, forcing me to downgrade to Rojo 6 (I apologise I confused the versions in my initial bug report).
Rojo 6 continues to work, Rojo 7 is breaking.
I'm running on Windows 11.

Solution
I've just tested it by using the rbxm file from the latest github releases and now it works fine.
It's just the cloud/marketplace version of the plugin which causes this issue, I suspect perhaps it's a roblox issue.
I'll close this now, thank you for yourhelp.

**Comment by kennethloeffler** [comment]
Okay, I'm glad you got it sorted! This behavior is pretty weird and we've never seen it before - do let us know if you run into it again.

**Comment by theMattCode** [comment]
I get the same error. Also running Windows 11.
Tried different methods to install Rojo plugin into Studio (rojo plugin install, Rojo.rbxm).
Everytime I open a place it works fine. Once I connect Rojo even the Game settings won't work anymore.
Disconnecting the plugin doesn't solve it. Closing the place and reopening it makes it work again.

Example error after connecting Rojo and a click on Game settings:
```
 Failed builtin_GameSettings.rbxm.GameSettings.Src.Controllers.GameInfoController:209: HttpResponse = {
	handleRetryErrorMessage = "4xx error response. Rejecting request.",
	requestErrorMessage = "Http request to https://games.roblox.com/v1/games/[REDACTED]/media rejected because request did not succeed.",
	requestOptions = {
		Method = "GET",
		Url = "https://games.roblox.com/v1/games/[REDACTED]/media"
	},
	responseBody = { errors = {{ code = 2, message = "The requested universe does not exist." }} },
	responseCode = 404,
	responseTimeMs = 213.89126777648926
```
