### ISSUE TITLE
High CPU usage and file not syncing when drafts mode is enabled

### ISSUE THREAD

**Issue by quinoaa** [rojo-rbx/rojo#897]
When I create a new file when using roblox-TS, rojo doesn't sync the content of the new script.

I get an empty script and there is a high CPU usage.

When setting the plugin to trace mode, I get the following message spammed in the console
![image](https://github.com/rojo-rbx/rojo/assets/67757267/194e4f94-5147-43cf-a2d3-108050c1d106)

**Comment by kennethloeffler** [comment]
Can you provide which version of Rojo you're seeing this behavior on, your Rojo plugin settings (particularly if Two-Way Sync is enabled), your operating system, and more about the steps you're taking to get it to happen? I don't think we've seen this reported before, but I'd love to get to the bottom of it!

**Comment by quinoaa** [comment]
I'm using Rojo 7.4.1 and Windows 11 with atlas OS and I don't think I have changed the settings a lot

It seems like the issue only occurs when script draft mode is enabled with team create, new script doesn't get created but editing existing script works fine
I disabled draft mode and everything seems to work fine now

Thanks a lot for the response !

![image](https://github.com/rojo-rbx/rojo/assets/67757267/445c7f43-1a02-4b91-9c5b-f322dd0ab99e)

**Comment by kennethloeffler** [comment]
Thanks for the extra information - we'll have to see if there's anything Rojo can do differently to play nice with drafts mode. It's uncommon for people to actually want to use Rojo and drafts together, but Rojo should definitely still function properly when the feature is enabled!

**Comment by kennethloeffler** [comment]
Scratch that - we could work around this by parenting instances before setting other properties, but I still think Roblox should fix this!

**Comment by kennethloeffler** [comment]
This should now be fixed: https://devforum.roblox.com/t/when-drafts-mode-is-enabled-instantiating-a-script-setting-its-source-with-scripteditorserviceupdatesourceasync-then-setting-its-parent-fails/2941974/3
