### ISSUE TITLE
'rojo new' command

### ISSUE THREAD

**Issue by LPGhatguy** [rojo-rbx/rojo#91]
It'd be great to have a single command to create a new place or model project.

The new form of `rojo init` _almost_ accomplishes this, but doesn't do things like create a `src` directory for you.

**Comment by Kampfkarren** [comment]
Should it include a .luacheckrc?

**Comment by LPGhatguy** [comment]
I'm not sure about the scope of this command! My initial thought is that it should only generate the actual files needed for a place/model project, but it could also include a `.luacheckrc`.

**Comment by LPGhatguy** [comment]
Complete in `master` by just expanding the `rojo init` command.
