### ISSUE TITLE
Error creating server listener on :34872

### ISSUE THREAD

**Issue by RhysFaber** [rojo-rbx/rojo#923]
Error binding to 127.0.0.1:34872: 
Error creating server listener: Only one usage of each socket address (protocol/network address/port) is normally permitted.
in file C:\Users\runneradmin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\hyper-0.14.27\src\server\server.rs on line 79
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

**Comment by Dekkonot** [comment]
This isn't a bug with Rojo. Like the error says, there's only one program that can run for each port on a given network.

You can change which port Rojo is connecting to via the `--port` CLI flag or via the `servePort` field on projects files.

Going to close this, but feel free to reply if you have any questions.
