### ISSUE TITLE
Allow publishing existing place file with 'rojo upload'

### ISSUE THREAD

**Issue by LPGhatguy** [rojo-rbx/rojo#94]
Right now, `rojo upload` generates the place file that it uploads for you. Since not all instances are supported by Rojo right now, this severely limits the kinds of places that can be automatically deployed.

It should accept an optional parameter, maybe `--place`, that is a path to an existing place file to upload instead of generating a new one.

**Comment by Kampfkarren** [comment]
I'm wondering if its within scope for Rojo to become the new [Ropp](https://github.com/Kampfkarren/ropp) in this regard.

**Comment by LPGhatguy** [comment]
I believe this would be better off implemented in a tool that is not Rojo. I've been considering this functionality as part of https://github.com/rojo-rbx/remodel/issues/16 instead.
