### ISSUE TITLE
Is it possible to edit the properties of a value in studio and have the changes go into the Rojo UI?

### ISSUE THREAD

**Issue by Pymon02** [rojo-rbx/rojo#941]
My Value in studio:
![image](https://github.com/user-attachments/assets/d88e18cf-8e67-4d8f-8d5d-51f6cc8a2717)

In vscode:
![image](https://github.com/user-attachments/assets/666ef8e4-083e-480f-8810-84bdc127522f)

**Comment by Dekkonot** [comment]
Not at this moment, though the feature is planned. You'll have to copy and paste things manually for now, or save to file depending upon how you want to handle it.
