### ISSUE TITLE
Wally package causes folders in rbxl/rbxm files built by Rojo to have Archivable set to false

### ISSUE THREAD

**Issue by 100BlueStarwars** [rojo-rbx/rojo#957]
When trying to build a rbxl (or rbxm) using Rojo while the package "aloroid/gorp-ecr@0.2.0-rc3" is installed, all folders created by Rojo will have Archivable set to false

I've created a repository producing this issue for you to use:
https://github.com/100BlueStarwars/rojo-archivable-issue

**Comment by kennethloeffler** [comment]
Thanks for the report! This was an issue in rbx-dom (a suite of libraries that Rojo uses to build files, among other things) which I documented a little while ago at https://github.com/rojo-rbx/rbx-dom/issues/418. We've just put together a fix, so it will be resolved in the next Rojo release. I'll leave this issue open until we do that.
