### ISSUE TITLE
Support `$schema` field in `*.project.json` files

### ISSUE THREAD

**Issue by LouieK22** [rojo-rbx/rojo#972]
Right now, if a JSON schema field is set in `default.project.json`, Rojo will error due to failing to parse the project file:
```json
{
	"$schema": "https://raw.githubusercontent.com/rojo-rbx/vscode-rojo/refs/heads/master/schemas/project.template.schema.json",
	...
}
```
e.g.
```
PS C:\Users\louie\[...]\repro> rojo build development.project.json --output dev.rbxl
[ERROR rojo] Rojo requires a project file, but no project file was found in path C:\Users\[...]\development.project.json
        See https://rojo.space/docs/ for guides and documentation.
```

Using a JSON schema is useful as it provides autocomplete and validation within the text editor. While the vscode extension does embed a schema (after all, that's where this schema comes from), not every uses or wants to use the extension.

**Comment by Dekkonot** [comment]
We can support this field in all of the JSON objects (.meta.json and .model.json). Easy enough.

**Comment by Brijeshthummar02** [comment]
i will work on the issue.
