### ISSUE TITLE
Rojo deleted my script both for VS Code and for Roblox Studio

### ISSUE THREAD

**Issue by PatoFlamejanteTV** [rojo-rbx/rojo#980]
I was making a module for generating GUIs, Rojo was stopped, and when i turned it back, my script was turned into a old version of the script, even using `Ctrl + Z` nothing was changed.

Can someone help me? I lost ~99% of my script because of Rojo.

My script after Rojo messed up:
![image](https://github.com/user-attachments/assets/6e6bbc4e-7073-49b1-a6f1-99168f069fa1)

**Comment by Dekkonot** [comment]
Rojo doesn't do any modification to your file system unless you have two way sync enabled. Did you?

**Comment by PatoFlamejanteTV** [comment]
Yes, i have this option turned on. Sorry, i forgot to mention :(

**Comment by Dekkonot** [comment]
There's not much we can do in that case. If you had Studio open on Team Create, you can potentially get your scripts back via their drafts system, but if not then... I'm very sorry.

There is a reason that two way sync is marked as experimental. It's because things like this might happen.

**Comment by PatoFlamejanteTV** [comment]
I'm ok with that, probably that script was with bugs, and anyway I would have to redo it from scratch, but it still makes sense the option is marked as experimental.
