### ISSUE TITLE
Rojo Not Working With Fusion

### ISSUE THREAD

**Issue by Slimified** [rojo-rbx/rojo#984]
Hey, I am trying to require Fusion in a script using Rojo, and it recognizes normal, regular module scripts, but does not recognize fusion, whether it is a .rbxm or .rbxmx file. It knows that Fusion is a module script, but requiring it is not working and does not provide intellisense or autocomplete, which it is in Roblox Studio.

**Comment by Dekkonot** [comment]
Rojo does not provide any intellisense, full stop; this is likely an issue with Luau LSP or whatever else your editor is using.

**Comment by Slimified** [comment]
It is Luau Language Server by JohnnyMorganz. Is there any way to fix this?

**Comment by Dekkonot** [comment]
You will have to ask on the repository for Luau LSP. You can find that here: https://github.com/JohnnyMorganz/luau-lsp
