### ISSUE TITLE
any support for intellij?

### ISSUE THREAD

**Issue by danneboii206** [rojo-rbx/rojo#996]
Will there any be any support for any other IDEs? I like how IntelliJ looks more ;c

**Comment by Barocena** [comment]
Extension is for vscode only, but you can use the rojo CLI with any IDE you want

**Comment by danneboii206** [comment]
what is rojo cli im new

**Comment by Barocena** [comment]
https://rojo.space/docs/v7/getting-started/new-game/#live-syncing-into-studio

You can checkout the docs, and also for more information you can join to the Roblox OSS discord (link is at the footer of the website)
